'use client';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import {useCallback,useEffect,useState} from 'react';
import {ArrowLeft,CarFront,ChevronLeft,ChevronRight,Download,LogOut,MapPin,RefreshCw,Search,UserRound,UsersRound,X} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Skeleton} from '@/components/ui/skeleton';

type Resource='drivers'|'vehicles';
type Item={external_id:string;callsign:string|null;display_name?:string;first_name?:string|null;last_name?:string|null;mobile?:string|null;email?:string|null;registration?:string|null;make?:string|null;model?:string|null;colour?:string|null;passenger_capacity?:number|null;vehicle_type?:string|null;plate_number?:string|null;company:string|null;status:string;suspended:boolean;capabilities:unknown[];raw_payload:unknown;synced_at:string};
type ResponseData={items:Item[];total:number;page:number;pageSize:number;companies:string[];summary:{total:number;active:number;suspended:number;lastSynced:string|null};error?:string;needsConfiguration?:boolean};

export default function FleetApp({resource}:{resource:Resource}){
 const router=useRouter();
 const drivers=resource==='drivers',title=drivers?'Drivers':'Vehicles',Icon=drivers?UsersRound:CarFront;
 const [items,setItems]=useState<Item[]>([]),[loading,setLoading]=useState(true),[syncing,setSyncing]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[query,setQuery]=useState(''),[search,setSearch]=useState(''),[status,setStatus]=useState('All'),[company,setCompany]=useState('All'),[companies,setCompanies]=useState<string[]>([]),[page,setPage]=useState(1),[pageSize,setPageSize]=useState(20),[total,setTotal]=useState(0),[summary,setSummary]=useState<ResponseData['summary']>({total:0,active:0,suspended:0,lastSynced:null}),[selected,setSelected]=useState<Item|null>(null);
 const load=useCallback(async()=>{setError('');try{const params=new URLSearchParams({page:String(page),pageSize:String(pageSize),status,company});if(search)params.set('search',search);const response=await fetch(`/api/admin/${resource}?${params}`,{cache:'no-store',credentials:'same-origin'});if(response.status===401||response.status===403){router.push('/admin-login');return}const data=await response.json() as ResponseData;if(!response.ok)throw new Error(data.error);setItems(data.items);setTotal(data.total);setSummary(data.summary);setCompanies(data.companies||[]);if(data.page!==page)setPage(data.page)}catch(reason){setError(reason instanceof Error?reason.message:`Unable to load ${title.toLowerCase()}.`)}finally{setLoading(false)}},[company,page,pageSize,resource,router,search,status,title]);
 useEffect(()=>{const timer=setTimeout(()=>{setSearch(query.trim());setPage(1)},300);return()=>clearTimeout(timer)},[query]);
 useEffect(()=>{const timer=setTimeout(()=>void load(),0);return()=>clearTimeout(timer)},[load]);
 async function sync(){setSyncing(true);setError('');setNotice('');try{const response=await fetch(`/api/admin/${resource}`,{method:'POST',credentials:'same-origin'});if(response.status===401||response.status===403){router.push('/admin-login');return}const data=await response.json() as {saved?:number;received?:number;error?:string};if(!response.ok)throw new Error(data.error);setNotice(`${data.saved||0} ${title.toLowerCase()} synchronized from Autocab.`);await load()}catch(reason){setError(reason instanceof Error?reason.message:'Unable to synchronize with Autocab.')}finally{setSyncing(false)}}
 const totalPages=Math.max(1,Math.ceil(total/pageSize)),first=total?(page-1)*pageSize+1:0,last=Math.min(page*pageSize,total);
 function exportCsv(){const columns=drivers?['ID','Callsign','Name','Mobile','Email','Company','Status']:['ID','Callsign','Registration','Make','Model','Colour','Capacity','Type','Company','Status'];const rows=items.map(item=>drivers?[item.external_id,item.callsign,item.display_name,item.mobile,item.email,item.company,item.status]:[item.external_id,item.callsign,item.registration,item.make,item.model,item.colour,item.passenger_capacity,item.vehicle_type,item.company,item.status]);const csv=[columns,...rows].map(row=>row.map(cell=>`"${String(cell??'').replaceAll('"','""')}"`).join(',')).join('\n');const link=document.createElement('a');link.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));link.download=`autocab-${resource}-page-${page}.csv`;link.click();URL.revokeObjectURL(link.href)}
 return <main className="admin-shell fleet-admin"><header className="brandbar"><Link className="brand" href="/"><span className="brandmark">N<span>+</span></span><span>NEED A CAB <b>PLUS</b></span></Link><AdminNav active={resource}/><Link className="admin-link" href="/api/admin/logout"><LogOut size={16}/>Sign out</Link></header><div className="admin-body"><div className="admin-title"><div><span className="eyebrow">AUTOCAB FLEET</span><h1>{title}</h1><p className="muted">{drivers?'Drivers synchronized securely from the Autocab API.':'Cars and fleet details synchronized securely from the Autocab API.'}</p></div><Button onClick={()=>void sync()} disabled={syncing}><RefreshCw className={syncing?'spin':''}/>{syncing?'Synchronizing…':'Sync from Autocab'}</Button></div>
  <section className="fleet-summary"><article><Icon/><span>Total {title.toLowerCase()}</span><strong>{summary.total}</strong></article><article><span className="fleet-dot active"/><span>Active</span><strong>{summary.active}</strong></article><article><span className="fleet-dot suspended"/><span>Suspended</span><strong>{summary.suspended}</strong></article><article><RefreshCw/><span>Last synchronized</span><strong className="fleet-date">{summary.lastSynced?new Date(summary.lastSynced).toLocaleString('en-GB'):'Never'}</strong></article></section>
  <section className="fleet-toolbar"><label><Search/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder={drivers?'Search name, callsign, phone or email…':'Search callsign, registration, make or model…'}/></label><select aria-label="Status" value={status} onChange={event=>{setStatus(event.target.value);setPage(1)}}><option>All</option><option>Active</option><option>Suspended</option></select><select aria-label="Company" value={company} onChange={event=>{setCompany(event.target.value);setPage(1)}}><option>All</option>{companies.map(item=><option key={item}>{item}</option>)}</select><span/>{drivers&&<Link href="/admin/live-map" className="fleet-live-map-link"><MapPin size={14}/>Live Map</Link>}<Button variant="outline" onClick={()=>void load()}><RefreshCw/>Refresh</Button><Button variant="outline" onClick={exportCsv}><Download/>Export</Button></section>
  {error&&<div className="fleet-alert error-message"><span>{error}</span>{error.includes('action key')&&<Link href="/admin/configuration">Open API configuration</Link>}</div>}{notice&&<p className="saved-message">{notice}</p>}
  <section className="fleet-table"><header><strong>{total} <span>records</span></strong></header>{loading?<div className="loading-list"><Skeleton className="h-16 w-full"/><Skeleton className="h-16 w-full"/></div>:items.length===0?<div className="booking-empty"><Icon/><strong>No {title.toLowerCase()} synchronized yet</strong><span>Configure the Autocab endpoint, then select Sync from Autocab.</span></div>:<div className="booking-table-wrap"><table><thead>{drivers?<tr><th>Callsign</th><th>Name</th><th>Mobile</th><th>Email</th><th>Company</th><th>Status</th></tr>:<tr><th>Callsign</th><th>Registration</th><th>Vehicle</th><th>Colour</th><th>Capacity</th><th>Type</th><th>Company</th><th>Status</th></tr>}</thead><tbody>{items.map(item=><tr key={item.external_id} onClick={()=>setSelected(item)}>{drivers?<><td><button type="button">{item.callsign||item.external_id}</button></td><td>{item.display_name||'—'}</td><td>{item.mobile||'—'}</td><td>{item.email||'—'}</td><td>{item.company||'—'}</td><Status item={item}/></>:<><td><button type="button">{item.callsign||item.external_id}</button></td><td>{item.registration||'—'}</td><td>{[item.make,item.model].filter(Boolean).join(' ')||'—'}</td><td>{item.colour||'—'}</td><td>{item.passenger_capacity??'—'}</td><td>{item.vehicle_type||'—'}</td><td>{item.company||'—'}</td><Status item={item}/></>}</tr>)}</tbody></table></div>}<footer className="booking-pagination"><label>Rows per page:<select value={pageSize} onChange={event=>{setPageSize(Number(event.target.value));setPage(1)}}><option value="10">10</option><option value="20">20</option><option value="50">50</option><option value="100">100</option></select></label><span>{first}–{last} of {total}</span><button disabled={page<=1} onClick={()=>setPage(value=>value-1)} aria-label="Previous page"><ChevronLeft/></button><button disabled={page>=totalPages} onClick={()=>setPage(value=>value+1)} aria-label="Next page"><ChevronRight/></button></footer></section>
  <footer className="admin-footer"><Link className="text-link" href="/admin"><ArrowLeft/>Back to bookings</Link></footer></div>{selected&&<FleetDetails item={selected} drivers={drivers} close={()=>setSelected(null)}/>}</main>
}

function AdminNav({active}:{active:Resource}){return <nav className="admin-nav"><Link href="/admin">Bookings</Link><Link className={active==='drivers'?'active':''} href="/admin/drivers">Drivers</Link><Link className={active==='vehicles'?'active':''} href="/admin/vehicles">Vehicles</Link><Link href="/admin/live-map">Clear Map</Link><Link href="/admin/configuration">Configuration</Link></nav>}
function Status({item}:{item:Item}){return <td><span className={`fleet-status ${item.suspended?'suspended':'active'}`}>{item.suspended?'Suspended':item.status||'Active'}</span></td>}
function FleetDetails({item,drivers,close}:{item:Item;drivers:boolean;close:()=>void}){const rows=drivers?[['Callsign',item.callsign],['Name',item.display_name],['Mobile',item.mobile],['Email',item.email],['Company',item.company],['Status',item.status]]:[['Callsign',item.callsign],['Registration',item.registration],['Make',item.make],['Model',item.model],['Colour',item.colour],['Passenger capacity',item.passenger_capacity],['Vehicle type',item.vehicle_type],['Plate number',item.plate_number],['Company',item.company],['Status',item.status]];return <div className="booking-modal-bg" onMouseDown={event=>{if(event.currentTarget===event.target)close()}}><section className="fleet-modal"><header><div>{drivers?<UserRound/>:<CarFront/>}<h2>{drivers?item.display_name:item.registration||item.callsign}</h2></div><button onClick={close} aria-label="Close"><X/></button></header><div><dl>{rows.map(([label,value])=><div key={String(label)}><dt>{label}</dt><dd>{value??'—'}</dd></div>)}</dl><h3>Capabilities</h3><div className="capability-list">{item.capabilities?.length?item.capabilities.map((entry,index)=><span key={index}>{typeof entry==='object'?JSON.stringify(entry):String(entry)}</span>):<span>None received</span>}</div><details className="raw-booking"><summary>Complete Autocab JSON</summary><pre>{JSON.stringify(item.raw_payload,null,2)}</pre></details></div></section></div>}
