const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),ts=require('typescript');
function load(path,deps={}){const mod={exports:{}};new Function('require','module','exports',ts.transpileModule(fs.readFileSync(path,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText)(id=>deps[id]||require(id),mod,mod.exports);return mod.exports}
const rules={companyId:1,paymentMethod:'cash',cashAccountCustomerId:222,accountCustomerId:111,bookingCapabilities:[7,42,9],priorityDelayMinutes:0,minPrebookMinutes:45};
function route(overrides={}){const calls=[],customerCalls=[];const value=load('app/api/admin/capability-quote-test/route.ts',{
 '@/lib/app-configuration':{loadBookingPolicy:async()=>rules},'@/lib/autocab-api':{bookingQuote:async body=>{calls.push(body);const discounted=body.capabilities.includes(42);return {outward:{price:discounted?8:10,cost:6,bookingCost:5,pricingTariff:discounted?'Discounted Fare':'Standard'}}}},'@/lib/autocab-booking-request':{readAutocabCosts:value=>value.outward},'@/lib/smart-fare':load('lib/smart-fare.ts'),'@/lib/autocab-quote-request':load('lib/autocab-quote-request.ts'),'@/lib/prebook-time':{firstPrebookTime:()=>Date.parse('2026-10-06T12:00:00Z')},'@/lib/quotes':{calculateQuote:async input=>{customerCalls.push(input);return {service:input.service,basePence:1000,upliftPence:200,totalPence:1200,percent:20,demand:input.service,scheduledAt:input.scheduledAt,autocabRequest:{capabilities:[9]}}},loadQuotePolicy:async()=>({pricePath:'outward.price',priceUnit:'gbp',serviceCapabilities:{asap:[],priority:[],prebook:[],guarantee:[]},smartFareCapabilities:[42]})},'@/lib/quote-policy':{readFare:value=>Math.round(value.outward.price*100)},'@/lib/security':{isAdmin:async()=>true,sameOrigin:()=>true,unavailable:error=>{throw error}},...overrides});return {value,calls,customerCalls}}
const address=text=>({address:text,fullAddress:{text,coordinate:{latitude:50.37,longitude:-4.14},zoneId:1},placeID:null,customAddressID:null});
test('customer preview uses the booking engine and returns the service addition separately from the raw quote',async()=>{
 const {value,calls,customerCalls}=route();
 const response=await value.POST(new Request('https://admin.needacabplus.app/api/admin/capability-quote-test',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({pickup:address('Public Station'),destination:address('Public Hospital'),service:'guarantee',paymentMethod:'cash'})}));
 const body=await response.json();assert.equal(response.status,200);assert.equal(customerCalls.length,1);assert.equal(customerCalls[0].service,'guarantee');assert.equal(customerCalls[0].paymentMethod,'cash');assert.equal(customerCalls[0].scheduledAt,'2026-10-06T12:00:00.000Z');
 assert.equal(body.customerFare.basePence,1000);assert.equal(body.customerFare.upliftPence,200);assert.equal(body.customerFare.totalPence,1200);assert.deepEqual(body.customerFare.capabilities,[9]);assert.equal(body.control.pricePence,1000);assert.deepEqual(calls[0].capabilities,[]);assert.equal(body.bookingCreated,false);
 assert.equal('token' in body.customerFare,false);assert.equal('autocabRequest' in body.customerFare,false);
});
test('Pre-book receives a scheduled quote independently from Guarantee',async()=>{
 const {value,customerCalls}=route();
 const response=await value.POST(new Request('https://admin.needacabplus.app/api/admin/capability-quote-test',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({pickup:address('Public Station'),destination:address('Public Hospital'),service:'prebook',paymentMethod:'cash'})}));
 assert.equal(response.status,200);assert.equal(customerCalls[0].service,'prebook');assert.equal(customerCalls[0].scheduledAt,'2026-10-06T12:00:00.000Z');
});
test('absent or null capability requests one quote with an empty capability list, regardless of configured defaults',async()=>{
 for(const capabilityId of [null,undefined]){
  const {value,calls}=route();
  const response=await value.POST(new Request('https://admin.needacabplus.app/api/admin/capability-quote-test',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({capabilityId,pickup:address('Public Station'),destination:address('Public Hospital'),service:'asap',paymentMethod:'cash'})}));
  assert.equal(response.status,200);const body=await response.json();
  assert.equal(calls.length,1);assert.deepEqual(calls[0].capabilities,[]);assert.equal(calls[0].customerId,222);
  assert.equal(body.capabilityId,null);assert.equal(body.bookingCreated,false);assert.equal(body.control.pricePence,1000);assert.deepEqual(body.control.capabilities,[]);assert.equal(body.discounted,undefined);
 }
});
test('zero remains invalid and never reaches Autocab',async()=>{
 const {value,calls}=route();const response=await value.POST(new Request('https://admin.needacabplus.app/api/admin/capability-quote-test',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({capabilityId:0,pickup:address('Public Station'),destination:address('Public Hospital')})}));
 assert.equal(response.status,400);assert.equal(calls.length,0);
});
test('A/B quote removes capability 42 from control, adds it to test and creates no booking',async()=>{const {value,calls}=route();const response=await value.POST(new Request('https://admin.needacabplus.app/api/admin/capability-quote-test',{method:'POST',headers:{'Content-Type':'application/json','Origin':'https://admin.needacabplus.app'},body:JSON.stringify({capabilityId:42,pickup:address('65 Salcombe Road, Plymouth'),destination:address('77 Embankment Road, Plymouth'),service:'priority',paymentMethod:'cash'})}));assert.equal(response.status,200);const body=await response.json();assert.equal(body.bookingCreated,false);assert.deepEqual(calls.map(call=>call.capabilities),[[7,9],[7,9,42]]);assert.equal(body.control.pricePence,1000);assert.equal(body.discounted.pricePence,800);assert.equal(body.control.tariff.pricingTariff,'Standard');assert.equal(body.discounted.tariff.pricingTariff,'Discounted Fare')});
test('unauthenticated comparison stops before any quote call',async()=>{let called=false;const {value}=route({'@/lib/security':{isAdmin:async()=>false,sameOrigin:()=>true,unavailable:error=>{throw error}},'@/lib/autocab-api':{bookingQuote:async()=>{called=true}}});const response=await value.POST(new Request('https://admin.needacabplus.app/api/admin/capability-quote-test',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'}));assert.equal(response.status,403);assert.equal(called,false)});
