import {z} from 'zod';
import {randomUUID} from 'node:crypto';
import {sameOrigin} from '@/lib/security';
import {loadIdentityPolicy} from '@/lib/app-configuration';
import {database} from '@/lib/database';
import {decryptCredentials} from '@/lib/credentials';
import {setCustomerSession} from '@/lib/customer-auth';
import {pendingChallenge,beginChallenge,normalizePhone,AuthError,requestAuthLimit} from '@/lib/customer-verification';
export async function POST(request:Request){if(!sameOrigin(request))return Response.json({error:'Invalid origin'},{status:403});try{await requestAuthLimit(request);const {phone}=z.object({phone:z.string().max(30)}).strict().parse(await request.json()),number=normalizePhone(phone),row=await pendingChallenge();if(row.code_hash)throw new AuthError('Verify the current code first.');const payload=decryptCredentials(row.payload_encrypted),policy=await loadIdentityPolicy();if(row.customer_id||policy.registrationOtp)return Response.json(await beginChallenge(row.purpose,number,payload,row.customer_id));if(row.purpose!=='social')throw new AuthError('Invalid verification request.');const db=await database().connect(),id=randomUUID();try{await db.query('BEGIN');const claimed=await db.query('UPDATE customer_auth_challenges SET consumed_at=now() WHERE id=$1 AND consumed_at IS NULL AND expires_at>now() RETURNING id',[row.id]);if(!claimed.rowCount)throw new AuthError('Sign-in expired.');await db.query('INSERT INTO customer_accounts(id,email,password_hash,full_name,phone) VALUES($1,$2,$3,$4,$5)',[id,payload.email,payload.passwordHash,payload.fullName,number]);await db.query('INSERT INTO customer_identities(provider,subject,customer_id) VALUES($1,$2,$3)',[payload.provider,payload.subject,id]);await db.query('COMMIT')}catch(e){await db.query('ROLLBACK');throw e}finally{db.release()}await setCustomerSession(id);return Response.json({ok:true})}catch(e){return Response.json({error:e instanceof AuthError?e.message:'Unable to save your phone number.'},{status:e instanceof AuthError?e.status:400})}}
