'use client';
import {oauthMessages} from '@/lib/oauth-errors';
import Link from 'next/link';
import {FormEvent,Suspense,useEffect,useState} from 'react';
import {useRouter,useSearchParams} from 'next/navigation';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
function CustomerLoginForm(){
 const router=useRouter(),params=useSearchParams();
 const [mode,setMode]=useState<'login'|'register'>('login'),[stage,setStage]=useState<'credentials'|'phone'|'verify'>(params.get('phone')?'phone':params.get('verify')?'verify':'credentials'),[busy,setBusy]=useState(false),[error,setError]=useState(params.get('error')?(oauthMessages[params.get('error')!]||oauthMessages.provider):''),[message,setMessage]=useState(''),[providers,setProviders]=useState({google:false,apple:false});
 const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[fullName,setFullName]=useState(''),[phone,setPhone]=useState(''),[code,setCode]=useState('');
 useEffect(()=>{fetch('/api/customer/auth/options',{cache:'no-store'}).then(r=>r.json() as Promise<{google:boolean;apple:boolean}>).then(setProviders).catch(()=>{})},[]);
 function finish(){const target=params.get('returnTo');router.push(target?.startsWith('/')&&!target.startsWith('//')&&!target.includes('\\')?target:'/');router.refresh()}
 async function perform(action:string,body:unknown){setBusy(true);setError('');setMessage('');try{const r=await fetch('/api/customer/auth/'+action,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),data=await r.json() as {error?:string;verificationRequired?:boolean;phoneRequired?:boolean;maskedPhone?:string};if(!r.ok)throw Error(data.error||'Unable to continue.');if(data.verificationRequired){setStage(data.phoneRequired?'phone':'verify');setCode('');setMessage(data.phoneRequired?'Add your mobile number to complete your account.':'Verification code sent to '+(data.maskedPhone||'your mobile')+'.')}else finish()}catch(e){setError(e instanceof Error?e.message:'Unable to continue.')}finally{setBusy(false)}}
 function submit(e:FormEvent){e.preventDefault();void perform(stage==='verify'?'verify':stage==='phone'?'phone':mode,stage==='verify'?{code}:stage==='phone'?{phone}:mode==='login'?{email,password}:{email,password,fullName,phone})}
 return <main className="customer-auth-shell"><section className="customer-auth-card"><Link className="brand login-brand" href="/"><span className="brandmark">N<span>+</span></span><span>NEED A CAB <b>PLUS</b></span></Link><h1>{stage==='verify'?'Verify your mobile':stage==='phone'?'Your mobile number':mode==='login'?'Welcome back.':'Create your account.'}</h1>
 {stage==='credentials'&&<><div className="customer-auth-tabs"><button className={mode==='login'?'active':''} onClick={()=>setMode('login')}>Sign in</button><button className={mode==='register'?'active':''} onClick={()=>setMode('register')}>Create account</button></div><div className="social-signin">{(['google','apple'] as const).map(provider=>providers[provider]?<a className="social-signin-button" key={provider} href={'/api/customer/auth/oauth/'+provider}>Continue with {provider==='google'?'Google':'Apple'}</a>:<button className="social-signin-button" key={provider} disabled>{provider==='google'?'Google':'Apple'} · not available yet</button>)}</div><p className="muted">Or continue with email</p></>}
 <form onSubmit={submit}>{stage==='credentials'&&<>{mode==='register'&&<><label>Full name<Input required minLength={2} maxLength={100} autoComplete="name" value={fullName} onChange={e=>setFullName(e.target.value)}/></label><label>Mobile number<Input required type="tel" autoComplete="tel" placeholder="+44…" value={phone} onChange={e=>setPhone(e.target.value)}/></label></>}<label>Email address<Input required type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<Input required minLength={mode==='register'?10:1} maxLength={200} type="password" autoComplete={mode==='login'?'current-password':'new-password'} value={password} onChange={e=>setPassword(e.target.value)}/></label></>}
 {stage==='phone'&&<label>Mobile number<Input required type="tel" autoComplete="tel" placeholder="+44…" value={phone} onChange={e=>setPhone(e.target.value)}/></label>}
 {stage==='verify'&&<><p className="muted">Enter the six-digit code sent by SMS. It expires after five minutes.</p><label>Verification code<Input required inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" maxLength={6} value={code} onChange={e=>setCode(e.target.value.replace(/[^0-9]/g,''))}/></label></>}
 {error&&<p className="error-message" role="alert">{error}</p>}{message&&<p role="status">{message}</p>}<Button className="primary-action" disabled={busy}>{busy?'Please wait…':stage==='verify'?'Verify and continue':stage==='phone'?'Continue':mode==='login'?'Sign in':'Create account'}</Button></form>
 {stage==='verify'&&<button type="button" disabled={busy} onClick={()=>void perform('resend',{})}>Resend code (after 60 seconds)</button>}{stage!=='credentials'&&<button type="button" disabled={busy} onClick={()=>{setStage('credentials');setError('');setMessage('')}}>Start again</button>}<Link className="text-link" href="/">← Back to booking</Link></section></main>
}
export default function CustomerLogin(){return <Suspense fallback={<p>Loading…</p>}><CustomerLoginForm/></Suspense>}
