'use client';
import Link from 'next/link';
import {FormEvent,useCallback,useEffect,useMemo,useState} from 'react';
import {useRouter} from 'next/navigation';
import {Elements,PaymentElement,useElements,useStripe} from '@stripe/react-stripe-js';
import {loadStripe} from '@stripe/stripe-js';
import {ArrowLeft,CreditCard,LogOut,Plus,ShieldCheck,Trash2} from 'lucide-react';
import {Button} from '@/components/ui/button';
import type {Customer} from '@/lib/customer-auth';

type Card={id:string;brand:string;last4:string;expMonth:number;expYear:number};
type Wallet={enabled:boolean;publishableKey?:string;cards:Card[];error?:string};
export default function CustomerAccount({customer}:{customer:Customer}){
 const router=useRouter(),[wallet,setWallet]=useState<Wallet|null>(null),[clientSecret,setClientSecret]=useState(''),[error,setError]=useState('');
 const load=useCallback(async()=>{try{const response=await fetch('/api/customer/wallet',{cache:'no-store'}),data=await response.json() as Wallet;if(!response.ok&&!data.cards)throw new Error(data.error||'Unable to load wallet.');setWallet(data);setError(data.error||'')}catch(reason){setError(reason instanceof Error?reason.message:'Unable to load wallet.')}},[]);
 // eslint-disable-next-line react-hooks/set-state-in-effect -- wallet data is loaded from the server after mount
 useEffect(()=>{void load()},[load]);
 async function addCard(){setError('');const response=await fetch('/api/customer/wallet',{method:'POST'}),data=await response.json() as {clientSecret?:string;error?:string};if(!response.ok||!data.clientSecret){setError(data.error||'Unable to start card setup.');return}setClientSecret(data.clientSecret)}
 async function removeCard(id:string){const response=await fetch('/api/customer/wallet',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({paymentMethodId:id})});if(response.ok)await load();else setError('Unable to remove this card.')}
 async function logout(){await fetch('/api/customer/auth/logout',{method:'POST'});router.push('/');router.refresh()}
 const stripePromise=useMemo(()=>wallet?.publishableKey?loadStripe(wallet.publishableKey):null,[wallet]);
 return <main className="customer-account-shell"><header className="brandbar"><Link className="brand" href="/"><span className="brandmark">N<span>+</span></span><span>NEED A CAB <b>PLUS</b></span></Link><button className="admin-link" onClick={logout}><LogOut/>Sign out</button></header><div className="customer-account-body"><Link className="text-link" href="/"><ArrowLeft/>Book a journey</Link><span className="eyebrow">MY ACCOUNT</span><h1>Hello, {customer.fullName.split(' ')[0]}.</h1><p className="muted">Manage your details and payment wallet.</p><section className="account-profile"><div><span>Name</span><strong>{customer.fullName}</strong></div><div><span>Email</span><strong>{customer.email}</strong></div><div><span>Mobile</span><strong>{customer.phone}</strong></div></section><section className="wallet-card"><header><div className="wallet-icon"><CreditCard/></div><div><h2>Payment wallet</h2><p>Every Need A Cab Plus booking is paid securely by card.</p></div><Button onClick={addCard} disabled={!wallet?.enabled}><Plus/>Add card</Button></header><div className="wallet-security"><ShieldCheck/>Card details are handled by Stripe and are never stored by Need A Cab Plus.</div>{error&&<p className="error-message">{error}</p>}{!wallet&&<p className="muted">Loading your cards…</p>}{wallet?.cards.map(card=><article className="saved-card" key={card.id}><CreditCard/><div><strong>{card.brand.toUpperCase()} •••• {card.last4}</strong><span>Expires {String(card.expMonth).padStart(2,'0')}/{String(card.expYear).slice(-2)}</span></div><button onClick={()=>void removeCard(card.id)} aria-label={`Remove card ending ${card.last4}`}><Trash2/></button></article>)}{wallet&&wallet.cards.length===0&&!clientSecret&&<div className="empty-wallet"><CreditCard/><strong>No card saved</strong><span>Add a card before confirming your first booking.</span></div>}{clientSecret&&stripePromise&&<Elements stripe={stripePromise} options={{clientSecret,appearance:{theme:'night',variables:{colorPrimary:'#f2dd4a',colorBackground:'#101311'}}}}><CardSetup onDone={async()=>{setClientSecret('');await load()}}/></Elements>}</section></div></main>
}

function CardSetup({onDone}:{onDone:()=>Promise<void>}){const stripe=useStripe(),elements=useElements(),[busy,setBusy]=useState(false),[error,setError]=useState('');async function submit(event:FormEvent){event.preventDefault();if(!stripe||!elements)return;setBusy(true);setError('');const result=await stripe.confirmSetup({elements,confirmParams:{return_url:`${window.location.origin}/account`},redirect:'if_required'});if(result.error)setError(result.error.message||'Unable to save card.');else await onDone();setBusy(false)}return <form className="stripe-card-form" onSubmit={submit}><PaymentElement options={{layout:'tabs'}}/>{error&&<p className="error-message">{error}</p>}<Button className="primary-action" disabled={!stripe||busy}>{busy?'Saving card…':'Save card'}<ShieldCheck/></Button></form>}
