'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowLeft,ArrowRight,CarFront,Check,CheckCircle2,Clock3,MapPin,Navigation,ShieldCheck,Users,Briefcase,Banknote,Plus,X} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import {Checkbox} from '@/components/ui/checkbox';
import {vehicles,money} from '@/lib/vehicles';

type Stage=0|1|2|3|4;
export default function BookingApp(){
 const [stage,setStage]=useState<Stage>(0),[pickup,setPickup]=useState(''),[destination,setDestination]=useState(''),[viaPoints,setViaPoints]=useState<string[]>([]),[vehicle,setVehicle]=useState('saloon'),[name,setName]=useState(''),[phone,setPhone]=useState(''),[note,setNote]=useState(''),[ack,setAck]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[reference,setReference]=useState('');
 const requestId=useRef(''),pending=useRef(false),heading=useRef<HTMLHeadingElement>(null);
 const selected=vehicles.find(v=>v.id===vehicle)!;
 const next=(s:Stage)=>{setError('');setStage(s)};
 useEffect(()=>{if(stage>0)heading.current?.focus()},[stage]);
 useEffect(()=>{const ctx=(document as Document & {modelContext?:{registerTool:(t:unknown,o:unknown)=>Promise<void>}}).modelContext;if(!ctx?.registerTool)return;const abort=new AbortController();Promise.resolve(ctx.registerTool({name:'stage_trip_addresses',title:'Fill trip addresses',description:'Fill the pick-up and destination in the private booking preview. Does not book a trip or produce a live fare.',inputSchema:{type:'object',properties:{pickup:{type:'string',minLength:5,maxLength:250},destination:{type:'string',minLength:5,maxLength:250}},required:['pickup','destination'],additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:unknown)=>{const x=input as {pickup?:unknown;destination?:unknown};if(typeof x?.pickup!=='string'||typeof x.destination!=='string'||x.pickup.trim().length<5||x.destination.trim().length<5||x.pickup.length>250||x.destination.length>250||x.pickup.trim().toLowerCase()===x.destination.trim().toLowerCase())throw new Error('Two different full addresses are required');setPickup(x.pickup.trim());setDestination(x.destination.trim());setStage(0);setError('');return {staged:true,bookingCreated:false}}},{signal:abort.signal})).catch(()=>{});return()=>abort.abort()},[]);
 function routeNext(){const stops=[pickup,...viaPoints,destination].map(stop=>stop.trim());if(stops.some(stop=>stop.length<5)){setError('Enter a full address for every stop.');return}if(new Set(stops.map(stop=>stop.toLowerCase())).size!==stops.length){setError('Each stop must use a different address.');return}next(1)}
 async function book(){if(pending.current)return;pending.current=true;setBusy(true);setError('');requestId.current||=crypto.randomUUID();try{const r=await fetch('/api/bookings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:requestId.current,pickup,destination,viaPoints,vehicle,name,phone,pickupNote:note,acknowledged:ack})});const data=await r.json() as {id:string;error?:string};if(!r.ok)throw new Error(data.error||'Unable to save your test booking.');setReference(data.id);next(4)}catch(e){setError(e instanceof Error?e.message:'Unable to save your test booking. Please try again.')}finally{pending.current=false;setBusy(false)}}
 function reset(){requestId.current='';setReference('');setViaPoints([]);setAck(false);next(0)}
 return <main className="booking-shell">
 <header className="brandbar"><a className="brand" href="/"><span className="brandmark">N<span>+</span></span><span>NEED A CAB <b>PLUS</b></span></a><a className="admin-link" href="/admin">Admin <ArrowRight size={16}/></a></header>
 <section className="map-surface" aria-label="Plymouth area map"><iframe title="Map of Plymouth, area overview only" src="https://www.openstreetmap.org/export/embed.html?bbox=-4.19%2C50.35%2C-4.09%2C50.40&layer=mapnik"/><div className="map-city"><MapPin size={17}/> Plymouth · area overview</div></section>
 <section className="booking-panel"><div className="mobile-handle"/>
 <div className="panel-top">{stage>0&&stage<4?<button className="back-button" aria-label="Back to previous step" disabled={busy} onClick={()=>next((stage-1) as Stage)}><ArrowLeft size={21}/></button>:<span className="eyebrow">YOUR NEXT JOURNEY</span>}<span className="step-count">{stage===4?'COMPLETE':`0${stage+1} / 04`}</span></div>
 {stage===0&&<><h1 ref={heading} tabIndex={-1}>Where are<br/>we taking you?</h1><p className="muted">Plan your trip with Need A Cab Plus.</p><form onSubmit={e=>{e.preventDefault();routeNext()}}><div className="route-builder"><div className="route-fields"><label><span className="route-dot"/><span className="field-body"><span>Pick-up</span><Input required minLength={5} maxLength={250} placeholder="Enter pick-up address" autoComplete="off" value={pickup} onChange={e=>setPickup(e.target.value)}/></span></label>{viaPoints.map((via,index)=><div key={index} className="via-field"><div className="route-divider"/><label><span className="via-dot"/><span className="field-body"><span>Via point {index+1}</span><Input required minLength={5} maxLength={250} aria-label={`Via point ${index+1}`} placeholder="Add an intermediate stop" autoComplete="off" value={via} onChange={e=>setViaPoints(all=>all.map((item,i)=>i===index?e.target.value:item))}/></span><button type="button" className="remove-via" aria-label={`Remove via point ${index+1}`} onClick={()=>setViaPoints(all=>all.filter((_,i)=>i!==index))}><X size={17}/></button></label></div>)}<div className="route-divider"/><label><span className="route-square"/><span className="field-body"><span>Destination</span><Input required minLength={5} maxLength={250} placeholder="Where to?" autoComplete="off" value={destination} onChange={e=>setDestination(e.target.value)}/></span></label></div><button type="button" className="add-via" disabled={viaPoints.length>=3} aria-label="Add a via point" onClick={()=>setViaPoints(all=>[...all,''])}><Plus size={24}/></button></div>{viaPoints.length>0&&<p className="via-help">Up to 3 intermediate stops can be added.</p>}<div className="time-row"><Clock3 size={19}/><span>Ride now</span><span className="muted">Test journey</span></div><Button type="submit" className="primary-action">Choose a car <ArrowRight size={20}/></Button></form><div className="preview-note"><ShieldCheck size={18}/><span>Private preview · no live cars or charges</span></div><div className="suggested"><span className="eyebrow">TRY A SAMPLE JOURNEY</span><button onClick={()=>{setPickup('2 Masterman Road, Plymouth');setDestination('178 Ladysmith Road, Plymouth');setViaPoints([]);setError('')}}><span className="place-icon"><Navigation size={20}/></span><span><strong>Masterman Road → Ladysmith Road</strong><small>Plymouth · sample addresses</small></span><ArrowRight size={18}/></button></div></>}
 {stage===1&&<><h1 ref={heading} tabIndex={-1}>Choose your ride.</h1><p className="muted">Example categories and fares for this preview.</p><RouteSummary pickup={pickup} viaPoints={viaPoints} destination={destination}/><RadioGroup aria-label="Vehicle category" value={vehicle} onValueChange={setVehicle} className="vehicle-list">{vehicles.map(v=><label key={v.id} className={`vehicle-option ${vehicle===v.id?'selected':''}`}><RadioGroupItem value={v.id} className="sr-only"/><span className="car-icon"><CarFront size={43} strokeWidth={1.4}/></span><span className="vehicle-copy"><strong>{v.name}</strong><small><Users size={13}/>{v.passengers}<Briefcase size={13}/>{v.bags}</small><span>{v.description}</span></span><span className="fare"><strong>{money(v.demoPence)}</strong><small>Example</small></span></label>)}</RadioGroup><p className="notice">These are sample prices, not a live quote. Route pricing and driver availability are not connected yet.</p><Button className="primary-action" onClick={()=>next(2)}>Choose {selected.name}<ArrowRight size={20}/></Button></>}
 {stage===2&&<><h1 ref={heading} tabIndex={-1}>Confirm details.</h1><div className="chosen-car"><CarFront size={82} strokeWidth={1.1}/><div><h2>{selected.name}</h2><span className="muted"><Users size={15}/> {selected.passengers} passengers · {selected.bags} bags</span></div><strong>{money(selected.demoPence)}<small>Example fare</small></strong></div><RouteSummary pickup={pickup} viaPoints={viaPoints} destination={destination}/><form onSubmit={e=>{e.preventDefault();next(3)}} className="details-form"><label>Passenger name<Input required minLength={2} maxLength={100} autoComplete="name" placeholder="Full name" value={name} onChange={e=>setName(e.target.value)}/></label><label>Mobile number<Input required type="tel" pattern="\+?[0-9 ()\-]{7,25}" autoComplete="tel" placeholder="e.g. +44 7700 900000" value={phone} onChange={e=>setPhone(e.target.value)}/></label><div className="payment-row"><Banknote size={22}/><div>Pay your driver<small>Preview only · no payment will be taken</small></div></div><Button type="submit" className="primary-action">Confirm pick-up location<ArrowRight size={20}/></Button></form></>}
 {stage===3&&<><h1 ref={heading} tabIndex={-1}>Your pick-up spot.</h1><p className="muted">Check the address and add a useful landmark.</p><div className="pickup-card"><MapPin size={24}/><div><strong>{pickup}</strong><span>Address as entered · not map-verified</span></div></div><label className="note-label">Pick-up instructions <span className="muted">(optional)</span><Textarea maxLength={300} placeholder="e.g. Main entrance, next to the blue gate" value={note} onChange={e=>setNote(e.target.value)}/></label><div className="booking-total"><span>{selected.name}<small>Sample fare</small></span><strong>{money(selected.demoPence)}</strong></div><label className="ack-row"><Checkbox checked={ack} onCheckedChange={v=>setAck(v===true)}/><span>I understand this is a test booking. No driver will be sent and no payment will be taken.</span></label><Button className="primary-action" disabled={!ack||busy} onClick={book}>{busy?'Saving test booking…':'Confirm test booking'}<Check size={20}/></Button><p className="small-note">Your test booking is saved automatically in the admin panel.</p></>}
 {stage===4&&<><div className="success-icon"><CheckCircle2 size={56} strokeWidth={1.4}/></div><h1 ref={heading} tabIndex={-1}>Test booking<br/>confirmed.</h1><p className="muted">Saved successfully. No driver has been requested.</p><div className="reference"><span>BOOKING REFERENCE</span><strong>NAC-{reference.slice(0,8).toUpperCase()}</strong></div><RouteSummary pickup={pickup} viaPoints={viaPoints} destination={destination}/><div className="booking-total"><span>{selected.name}<small>Example fare · no charge</small></span><strong>{money(selected.demoPence)}</strong></div><Button className="primary-action" onClick={reset}>Plan another trip<ArrowRight size={20}/></Button></>}
 {error&&<p className="error-message" role="alert">{error}</p>}
 </section><div className="map-caption"><span className="brandmark small">N<span>+</span></span><span>Your city.<br/><strong>Your next cab.</strong></span></div>
 </main>
}
function RouteSummary({pickup,viaPoints,destination}:{pickup:string;viaPoints:string[];destination:string}){return <div className="route-summary"><div><span className="route-dot"/><span>{pickup}</span></div>{viaPoints.map((via,index)=><div key={index}><span className="via-dot"/><span><small>Via {index+1}</small>{via}</span></div>)}<div><span className="route-square"/><span>{destination}</span></div></div>}

