'use client';
import Link from 'next/link';
import {useEffect,useRef,useState} from 'react';
import {ArrowLeft,ArrowRight,CarFront,Check,CheckCircle2,Clock3,MapPin,ShieldCheck,Users,Briefcase,CreditCard,House,Star,Pencil,Plus,X,LocateFixed,Sun,Moon,Monitor} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import {Checkbox} from '@/components/ui/checkbox';
import {vehicles,money} from '@/lib/vehicles';
import type {Customer} from '@/lib/customer-auth';
import CustomerLiveMap from './customer-live-map';

type Stage=0|1|2|3|4;
type AddressChoice={address:string;fullAddress:Record<string,unknown>|null;placeID:string|null;customAddressID:string|number|null};
type SavedPlace=AddressChoice&{id:string;kind:'home'|'work'|'favorite';name:string};
type Theme='system'|'light'|'dark';
type Coordinate={latitude:number;longitude:number};
export default function BookingApp({customer}:{customer:Customer|null}){
 const [stage,setStage]=useState<Stage>(0),[pickup,setPickup]=useState(''),[destination,setDestination]=useState(''),[viaPoints,setViaPoints]=useState<string[]>([]),[vehicle,setVehicle]=useState('saloon'),[name,setName]=useState(customer?.fullName||''),[phone,setPhone]=useState(customer?.phone||''),[note,setNote]=useState(''),[ack,setAck]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[reference,setReference]=useState('');
 const [walletState,setWalletState]=useState<'loading'|'ready'|'empty'|'unavailable'>(customer?'loading':'empty');
 const [selectedAddresses,setSelectedAddresses]=useState<Record<string,AddressChoice>>({});
 const [places,setPlaces]=useState<SavedPlace[]>([]),[history,setHistory]=useState<AddressChoice[]>([]),[activeStop,setActiveStop]=useState('pickup'),[placeEditor,setPlaceEditor]=useState<'home'|'work'|'favorite'|null>(null),[showFavorites,setShowFavorites]=useState(false);
 const [theme,setTheme]=useState<Theme>('system'),[locating,setLocating]=useState(false),[sheetExpanded,setSheetExpanded]=useState(false),[currentLocation,setCurrentLocation]=useState<Coordinate|null>(null);
 const [mapPicker,setMapPicker]=useState<'pickup'|'destination'|null>(null),[mapPoint,setMapPoint]=useState<Coordinate|null>(null),[mapChoice,setMapChoice]=useState<AddressChoice|null>(null),[mapResolving,setMapResolving]=useState(false);
 const requestId=useRef(''),pending=useRef(false),heading=useRef<HTMLHeadingElement>(null),dragStart=useRef<number|null>(null),mapSequence=useRef(0);
 const selected=vehicles.find(v=>v.id===vehicle)!;
 const pickupCoordinate=coordinate(selectedAddresses.pickup);
 const next=(s:Stage)=>{setError('');setStage(s)};
 useEffect(()=>{if(stage>0)heading.current?.focus()},[stage]);
 useEffect(()=>{const saved=(localStorage.getItem('nac-theme') as Theme|null)||'system',media=window.matchMedia('(prefers-color-scheme: dark)'),frame=requestAnimationFrame(()=>setTheme(saved));const apply=()=>{document.documentElement.dataset.theme=saved==='system'?(media.matches?'dark':'light'):saved};apply();media.addEventListener('change',apply);return()=>{cancelAnimationFrame(frame);media.removeEventListener('change',apply)}},[]);
 useEffect(()=>{if(!customer)return;let active=true;fetch('/api/customer/wallet',{cache:'no-store'}).then(async response=>{const data=await response.json() as {cards?:unknown[]};if(active)setWalletState(response.ok&&data.cards?.length?'ready':response.ok?'empty':'unavailable')}).catch(()=>{if(active)setWalletState('unavailable')});return()=>{active=false}},[customer]);
 useEffect(()=>{if(!customer)return;let active=true;Promise.all([fetch('/api/customer/places',{cache:'no-store'}),fetch('/api/customer/history',{cache:'no-store'})]).then(async([placesResponse,historyResponse])=>{const saved=await placesResponse.json() as {places?:SavedPlace[]},recent=await historyResponse.json() as {history?:AddressChoice[]};if(active){setPlaces(saved.places||[]);setHistory(recent.history||[])}}).catch(()=>{});return()=>{active=false}},[customer]);
 useEffect(()=>{const ctx=(document as Document & {modelContext?:{registerTool:(t:unknown,o:unknown)=>Promise<void>}}).modelContext;if(!ctx?.registerTool)return;const abort=new AbortController();Promise.resolve(ctx.registerTool({name:'stage_trip_addresses',title:'Fill trip addresses',description:'Fill the pick-up and destination in the private booking preview. Does not book a trip or produce a live fare.',inputSchema:{type:'object',properties:{pickup:{type:'string',minLength:5,maxLength:250},destination:{type:'string',minLength:5,maxLength:250}},required:['pickup','destination'],additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:unknown)=>{const x=input as {pickup?:unknown;destination?:unknown};if(typeof x?.pickup!=='string'||typeof x.destination!=='string'||x.pickup.trim().length<5||x.destination.trim().length<5||x.pickup.length>250||x.destination.length>250||x.pickup.trim().toLowerCase()===x.destination.trim().toLowerCase())throw new Error('Two different full addresses are required');setPickup(x.pickup.trim());setDestination(x.destination.trim());setStage(0);setError('');return {staged:true,bookingCreated:false}}},{signal:abort.signal})).catch(()=>{});return()=>abort.abort()},[]);
 // eslint-disable-next-line react-hooks/exhaustive-deps -- location permission is intentionally requested once per browser session.
 useEffect(()=>{if(sessionStorage.getItem('nac-location-requested'))return;sessionStorage.setItem('nac-location-requested','1');const timer=setTimeout(()=>locatePickup(),700);return()=>clearTimeout(timer)},[]);
 useEffect(()=>{if(stage!==0)return;const keys=['pickup',...viaPoints.map((_,index)=>`via-${index}`),'destination'];if(!keys.every(stop=>selectedAddresses[stop]))return;const stops=keys.map(key=>selectedAddresses[key].address.toLowerCase());if(new Set(stops).size!==stops.length)return;const timer=setTimeout(()=>{setError('');setStage(1)},180);return()=>clearTimeout(timer)},[selectedAddresses,stage,viaPoints]);
 function routeNext(){const stops=[pickup,...viaPoints,destination].map(stop=>stop.trim());if(stops.some(stop=>stop.length<5)){setError('Enter a full address for every stop.');return}const keys=['pickup',...viaPoints.map((_,index)=>`via-${index}`),'destination'];if(keys.some(key=>!selectedAddresses[key])){setError('Choose every address from the search results.');return}if(new Set(stops.map(stop=>stop.toLowerCase())).size!==stops.length){setError('Each stop must use a different address.');return}next(1)}
 function applyChoice(key:string,choice:AddressChoice){if(key==='pickup')setPickup(choice.address);else if(key==='destination')setDestination(choice.address);else if(key.startsWith('via-')){const index=Number(key.slice(4));setViaPoints(all=>all.map((item,i)=>i===index?choice.address:item))}setSelectedAddresses(all=>({...all,[key]:choice}));if(customer&&choice.fullAddress){setHistory(all=>[choice,...all.filter(item=>item.address!==choice.address)].slice(0,10));void fetch('/api/customer/history',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(choice)})}}
 function locatePickup(){if(!navigator.geolocation){setError('Location is not supported by this browser.');return}setLocating(true);setError('');navigator.geolocation.getCurrentPosition(async({coords})=>{const point={latitude:coords.latitude,longitude:coords.longitude};setCurrentLocation(point);try{const response=await fetch(`/api/address/current?latitude=${coords.latitude}&longitude=${coords.longitude}`,{cache:'no-store'}),data=await response.json() as {item?:AddressChoice;error?:string};if(!response.ok||!data.item)throw new Error(data.error||'We could not find your current address.');applyChoice('pickup',data.item)}catch(reason){setError(reason instanceof Error?reason.message:'We could not find your current address.')}finally{setLocating(false)}},reason=>{setLocating(false);setError(reason.code===1?'Allow location access to fill your pick-up automatically.':'We could not read your location. Try again.')},{enableHighAccuracy:true,timeout:12000,maximumAge:30000})}
 async function resolveMapPoint(point:Coordinate){const sequence=++mapSequence.current;setMapPoint(point);setMapResolving(true);setError('');try{const response=await fetch(`/api/address/current?latitude=${point.latitude}&longitude=${point.longitude}`,{cache:'no-store'}),data=await response.json() as {item?:AddressChoice;error?:string};if(sequence!==mapSequence.current)return;if(!response.ok||!data.item)throw new Error(data.error||'No address was found under the pin.');setMapChoice(data.item)}catch(reason){if(sequence===mapSequence.current){setMapChoice(null);setError(reason instanceof Error?reason.message:'No address was found under the pin.')}}finally{if(sequence===mapSequence.current)setMapResolving(false)}}
 function openMapPicker(kind:'pickup'|'destination'){const existing=selectedAddresses[kind],point=coordinate(existing)||pickupCoordinate||{latitude:50.374,longitude:-4.143};setActiveStop(kind);setMapPicker(kind);setMapChoice(existing||null);setMapPoint(point);setError('');if(!existing)void resolveMapPoint(point)}
 function chooseMapAddress(choice:AddressChoice){setMapChoice(choice);const point=coordinate(choice);if(point)setMapPoint(point)}
 function confirmMapAddress(){if(!mapPicker||!mapChoice){setError('Move the map or search for an address first.');return}applyChoice(mapPicker,mapChoice);setMapPicker(null);setSheetExpanded(false)}
 function locateMapPoint(){if(!navigator.geolocation){setError('Location is not supported by this browser.');return}setLocating(true);setError('');navigator.geolocation.getCurrentPosition(({coords})=>{const point={latitude:coords.latitude,longitude:coords.longitude};setCurrentLocation(point);setLocating(false);void resolveMapPoint(point)},reason=>{setLocating(false);setError(reason.code===1?'Allow location access to use your position on the map.':'We could not read your location. Try again.')},{enableHighAccuracy:true,timeout:12000,maximumAge:30000})}
 function setAppTheme(value:Theme){setTheme(value);localStorage.setItem('nac-theme',value);document.documentElement.dataset.theme=value==='system'?(window.matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'):value}
 async function savePlace(choice:AddressChoice){if(!customer||!placeEditor||!choice.fullAddress)return;const response=await fetch('/api/customer/places',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...choice,kind:placeEditor,name:placeEditor==='favorite'?'Favorite':placeEditor==='home'?'Home':'Work'})}),data=await response.json() as {place?:SavedPlace;error?:string};if(!response.ok||!data.place){setError(data.error||'Unable to save this place.');return}setPlaces(all=>data.place!.kind==='favorite'?[data.place!,...all]:[...all.filter(item=>item.kind!==data.place!.kind),data.place!]);setPlaceEditor(null);setShowFavorites(data.place.kind==='favorite')}
 async function book(){if(pending.current)return;pending.current=true;setBusy(true);setError('');requestId.current||=crypto.randomUUID();try{const r=await fetch('/api/bookings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:requestId.current,pickup,destination,viaPoints,vehicle,name,phone,pickupNote:note,acknowledged:ack})});const data=await r.json() as {id:string;error?:string};if(!r.ok)throw new Error(data.error||'Unable to save your test booking.');setReference(data.id);next(4)}catch(e){setError(e instanceof Error?e.message:'Unable to save your test booking. Please try again.')}finally{pending.current=false;setBusy(false)}}
 function reset(){requestId.current='';setReference('');setViaPoints([]);setSelectedAddresses({});setAck(false);setSheetExpanded(false);next(0)}
 return <main className="booking-shell">
 <header className="brandbar"><Link className="brand" href="/"><span className="brandmark">N<span>+</span></span><span>NEED A CAB <b>PLUS</b></span></Link><div className="header-actions"><button type="button" className="theme-toggle" title={`Theme: ${theme}`} aria-label={`Theme: ${theme}. Change theme`} onClick={()=>setAppTheme(theme==='system'?'light':theme==='light'?'dark':'system')}>{theme==='system'?<Monitor/>:theme==='light'?<Sun/>:<Moon/>}</button><Link className="admin-link" href={customer?'/account':'/customer-login'}>{customer?`Hi, ${customer.fullName.split(' ')[0]}`:'Sign in'}<ArrowRight size={16}/></Link></div></header>
 <section className={`map-surface ${mapPicker?'map-picker-active':''}`} aria-label="Live map of available cars in Plymouth"><CustomerLiveMap key={`${mapPicker||'live'}-${mapPicker&&mapPoint?`${mapPoint.latitude}-${mapPoint.longitude}`:''}`} pickup={pickupCoordinate} picker={Boolean(mapPicker)} pickerPoint={mapPoint} userLocation={currentLocation} onPickerMove={point=>void resolveMapPoint(point)}/>{mapPicker&&<button type="button" className={`map-picker-locate ${locating?'locating':''}`} aria-label="Centre map on my location" onClick={locateMapPoint}><LocateFixed/></button>}</section>
 <section className={`booking-panel ${mapPicker?'map-picker-mode':stage===0?(sheetExpanded?'sheet-expanded':'sheet-collapsed'):'sheet-expanded'}`}>{mapPicker?<MapPickerPanel key={`${mapPicker}-${mapChoice?.address||''}`} kind={mapPicker} choice={mapChoice} resolving={mapResolving} onClose={()=>{setMapPicker(null);setError('')}} onSelect={chooseMapAddress} onConfirm={confirmMapAddress}/>:<><button type="button" className="mobile-handle" aria-label={sheetExpanded?'Collapse journey panel':'Expand journey panel'} onClick={()=>setSheetExpanded(value=>!value)} onPointerDown={event=>{dragStart.current=event.clientY;event.currentTarget.setPointerCapture(event.pointerId)}} onPointerUp={event=>{if(dragStart.current!==null){const movement=event.clientY-dragStart.current;if(Math.abs(movement)>18)setSheetExpanded(movement<0);dragStart.current=null}}}/>
 <div className="panel-top">{stage>0&&stage<4?<button className="back-button" aria-label="Back to previous step" disabled={busy} onClick={()=>next((stage-1) as Stage)}><ArrowLeft size={21}/></button>:<span className="eyebrow">YOUR NEXT JOURNEY</span>}<span className="step-count">{stage===4?'COMPLETE':`0${stage+1} / 04`}</span></div>
 {stage===0&&<><p className="trip-instruction">Choose your pick-up and destination.</p><form onSubmit={e=>{e.preventDefault();routeNext()}}><div className="route-builder"><div className="route-fields"><label><span className="route-dot"/><span className="field-body"><span>Pick-up</span><AddressInput label="Pick-up" placeholder="Enter pick-up address" value={pickup} onLocate={locatePickup} onMapPick={()=>openMapPicker('pickup')} locating={locating} onFocus={()=>setActiveStop('pickup')} onChange={value=>{setPickup(value);setSelectedAddresses(all=>{const updated={...all};delete updated.pickup;return updated})}} onSelect={choice=>applyChoice('pickup',choice)}/></span></label>{viaPoints.map((via,index)=><div key={index} className="via-field"><div className="route-divider"/><label><span className="via-dot"/><span className="field-body"><span>Via point {index+1}</span><AddressInput label={`Via point ${index+1}`} placeholder="Add an intermediate stop" value={via} onFocus={()=>setActiveStop(`via-${index}`)} onChange={value=>{setViaPoints(all=>all.map((item,i)=>i===index?value:item));setSelectedAddresses(all=>{const updated={...all};delete updated[`via-${index}`];return updated})}} onSelect={choice=>applyChoice(`via-${index}`,choice)}/></span><button type="button" className="remove-via" aria-label={`Remove via point ${index+1}`} onClick={()=>{setViaPoints(all=>all.filter((_,i)=>i!==index));setSelectedAddresses(all=>Object.fromEntries(Object.entries(all).filter(([key])=>!key.startsWith(`via-`))))}}><X size={17}/></button></label></div>)}<div className="route-divider"/><label><span className="route-square"/><span className="field-body"><span>Destination</span><AddressInput label="Destination" placeholder="Where to?" value={destination} onMapPick={()=>openMapPicker('destination')} onFocus={()=>setActiveStop('destination')} onChange={value=>{setDestination(value);setSelectedAddresses(all=>{const updated={...all};delete updated.destination;return updated})}} onSelect={choice=>applyChoice('destination',choice)}/></span></label></div><button type="button" className="add-via" disabled={viaPoints.length>=3} aria-label="Add a via point" onClick={()=>setViaPoints(all=>[...all,''])}><Plus size={18}/></button></div>{viaPoints.length>0&&<p className="via-help">Up to 3 intermediate stops can be added.</p>}<PlacesPanel customer={Boolean(customer)} places={places} history={history} activeStop={activeStop} editor={placeEditor} showFavorites={showFavorites} onUse={choice=>applyChoice(activeStop,choice)} onEdit={kind=>setPlaceEditor(kind)} onCloseEditor={()=>setPlaceEditor(null)} onToggleFavorites={()=>setShowFavorites(value=>!value)} onSave={savePlace}/><p className="route-continue-note">Choose every address from the results to continue.</p></form><div className="preview-note"><ShieldCheck size={18}/><span>Addresses and zones verified through the live map service</span></div></>}
 {stage===1&&<><h1 ref={heading} tabIndex={-1}>Choose your ride.</h1><p className="muted">Example categories and fares for this preview.</p><div className="time-row"><Clock3 size={19}/><span>Ride now</span><span className="muted">As soon as possible</span></div><RouteSummary pickup={pickup} viaPoints={viaPoints} destination={destination}/><RadioGroup aria-label="Vehicle category" value={vehicle} onValueChange={setVehicle} className="vehicle-list">{vehicles.map(v=><label key={v.id} className={`vehicle-option ${vehicle===v.id?'selected':''}`}><RadioGroupItem value={v.id} className="sr-only"/><span className="car-icon"><CarFront size={43} strokeWidth={1.4}/></span><span className="vehicle-copy"><strong>{v.name}</strong><small><Users size={13}/>{v.passengers}<Briefcase size={13}/>{v.bags}</small><span>{v.description}</span></span><span className="fare"><strong>{money(v.demoPence)}</strong><small>Example</small></span></label>)}</RadioGroup><p className="notice">These are sample prices, not a live quote. Route pricing and driver availability are not connected yet.</p><Button className="primary-action" onClick={()=>next(2)}>Choose {selected.name}<ArrowRight size={20}/></Button></>}
 {stage===2&&<><h1 ref={heading} tabIndex={-1}>Confirm details.</h1><div className="chosen-car"><CarFront size={82} strokeWidth={1.1}/><div><h2>{selected.name}</h2><span className="muted"><Users size={15}/> {selected.passengers} passengers · {selected.bags} bags</span></div><strong>{money(selected.demoPence)}<small>Example fare</small></strong></div><RouteSummary pickup={pickup} viaPoints={viaPoints} destination={destination}/><form onSubmit={e=>{e.preventDefault();next(3)}} className="details-form"><label>Passenger name<Input required minLength={2} maxLength={100} autoComplete="name" placeholder="Full name" value={name} onChange={e=>setName(e.target.value)}/></label><label>Mobile number<Input required type="tel" pattern="\+?[0-9 ()\-]{7,25}" autoComplete="tel" placeholder="e.g. +44 7700 900000" value={phone} onChange={e=>setPhone(e.target.value)}/></label><div className="payment-row"><CreditCard size={22}/><div>Card payment only<small>{!customer?'Sign in or create an account before payment.':walletState==='ready'?'Your saved card will be used at checkout.':walletState==='loading'?'Checking your wallet…':walletState==='empty'?'Add a card before confirming your booking.':'Open Wallet to finish setting up card payments.'}</small></div>{customer&&<Link href="/account">Wallet</Link>}</div>{!customer?<Link className="primary-action" href="/customer-login?returnTo=/">Sign in to continue<ArrowRight size={20}/></Link>:walletState==='ready'?<Button type="submit" className="primary-action">Confirm pick-up location<ArrowRight size={20}/></Button>:<Link className="primary-action" href="/account">{walletState==='loading'?'Checking wallet…':'Add payment card'}<ArrowRight size={20}/></Link>}</form></>}
 {stage===3&&<><h1 ref={heading} tabIndex={-1}>Your pick-up spot.</h1><p className="muted">Check the address and add a useful landmark.</p><div className="pickup-card"><MapPin size={24}/><div><strong>{pickup}</strong><span>Address as entered · not map-verified</span></div></div><label className="note-label">Pick-up instructions <span className="muted">(optional)</span><Textarea maxLength={300} placeholder="e.g. Main entrance, next to the blue gate" value={note} onChange={e=>setNote(e.target.value)}/></label><div className="booking-total"><span>{selected.name}<small>Sample fare</small></span><strong>{money(selected.demoPence)}</strong></div><label className="ack-row"><Checkbox checked={ack} onCheckedChange={v=>setAck(v===true)}/><span>I understand this is a test booking. No driver will be sent and no payment will be taken.</span></label><Button className="primary-action" disabled={!ack||busy} onClick={book}>{busy?'Saving test booking…':'Confirm test booking'}<Check size={20}/></Button><p className="small-note">Your test booking is saved automatically in the admin panel.</p></>}
 {stage===4&&<><div className="success-icon"><CheckCircle2 size={56} strokeWidth={1.4}/></div><h1 ref={heading} tabIndex={-1}>Test booking<br/>confirmed.</h1><p className="muted">Saved successfully. No driver has been requested.</p><div className="reference"><span>BOOKING REFERENCE</span><strong>NAC-{reference.slice(0,8).toUpperCase()}</strong></div><RouteSummary pickup={pickup} viaPoints={viaPoints} destination={destination}/><div className="booking-total"><span>{selected.name}<small>Example fare · no charge</small></span><strong>{money(selected.demoPence)}</strong></div><Button className="primary-action" onClick={reset}>Plan another trip<ArrowRight size={20}/></Button></>}
 </>}{error&&<p className="error-message" role="alert">{error}</p>}
 </section><div className="map-caption"><span className="brandmark small">N<span>+</span></span><span>Your city.<br/><strong>Your next cab.</strong></span></div>
 </main>
}
function MapPickerPanel({kind,choice,resolving,onClose,onSelect,onConfirm}:{kind:'pickup'|'destination';choice:AddressChoice|null;resolving:boolean;onClose:()=>void;onSelect:(choice:AddressChoice)=>void;onConfirm:()=>void}){
 const [search,setSearch]=useState(choice?.address||'');
 return <><button type="button" className="mobile-handle map-picker-handle" aria-label="Close map selection" onClick={onClose}/><div className="panel-top"><button type="button" className="back-button" aria-label="Back" onClick={onClose}><ArrowLeft size={21}/></button><span className="step-count">MAP</span></div><div className="map-picker-copy"><h1>Set your {kind==='pickup'?'pick-up':'destination'}</h1><p>Drag the map to move the pin</p></div><AddressInput label={`Search ${kind}`} placeholder={resolving?'Finding address…':kind==='pickup'?'Search pick-up':'Where to?'} value={search} required={false} onChange={setSearch} onSelect={selected=>{setSearch(selected.address);onSelect(selected)}}/><Button type="button" className="primary-action map-picker-confirm" disabled={resolving||!choice} onClick={onConfirm}>{resolving?'Finding address…':`Confirm ${kind==='pickup'?'pick-up':'destination'}`}<Check size={20}/></Button></>
}
function RouteSummary({pickup,viaPoints,destination}:{pickup:string;viaPoints:string[];destination:string}){return <div className="route-summary"><div><span className="route-dot"/><span>{pickup}</span></div>{viaPoints.map((via,index)=><div key={index}><span className="via-dot"/><span><small>Via {index+1}</small>{via}</span></div>)}<div><span className="route-square"/><span>{destination}</span></div></div>}

function coordinate(choice:AddressChoice|undefined){const point=choice?.fullAddress?.coordinate;if(!point||typeof point!=='object')return null;const value=point as {latitude?:unknown;longitude?:unknown},latitude=Number(value.latitude),longitude=Number(value.longitude);return Number.isFinite(latitude)&&Number.isFinite(longitude)?{latitude,longitude}:null}

function PlacesPanel({customer,places,history,activeStop,editor,showFavorites,onUse,onEdit,onCloseEditor,onToggleFavorites,onSave}:{customer:boolean;places:SavedPlace[];history:AddressChoice[];activeStop:string;editor:'home'|'work'|'favorite'|null;showFavorites:boolean;onUse:(choice:AddressChoice)=>void;onEdit:(kind:'home'|'work'|'favorite')=>void;onCloseEditor:()=>void;onToggleFavorites:()=>void;onSave:(choice:AddressChoice)=>Promise<void>}){
 const home=places.find(place=>place.kind==='home'),work=places.find(place=>place.kind==='work'),favorites=places.filter(place=>place.kind==='favorite');
 if(!customer)return <div className="place-shortcuts guest"><Link href="/customer-login?returnTo=/"><House/><span>Home<small>Sign in to set</small></span></Link><Link href="/customer-login?returnTo=/"><Briefcase/><span>Work<small>Sign in to set</small></span></Link><Link href="/customer-login?returnTo=/"><Star/><span>Favorites<small>Save places</small></span></Link></div>;
 return <section className="customer-places"><span className="places-target">Add to {activeStop==='pickup'?'pick-up':activeStop==='destination'?'destination':'via point'}</span><div className="place-shortcuts"><PlaceButton icon={<House/>} title="Home" place={home} onUse={onUse} onEdit={()=>onEdit('home')}/><PlaceButton icon={<Briefcase/>} title="Work" place={work} onUse={onUse} onEdit={()=>onEdit('work')}/><button type="button" className={showFavorites?'active':''} onClick={onToggleFavorites}><Star/><span>Favorites<small>{favorites.length?`${favorites.length} saved`:'Add places'}</small></span></button></div>{editor&&<SavedPlaceEditor kind={editor} onClose={onCloseEditor} onSave={onSave}/>} {showFavorites&&<div className="favorite-list">{favorites.map(place=><button type="button" key={place.id} onClick={()=>onUse(place)}><Star/><span><strong>{place.name||'Favorite'}</strong><small>{place.address}</small></span></button>)}<button type="button" className="add-favorite" onClick={()=>onEdit('favorite')}><Plus/>Add favorite</button></div>}{history.length>0&&<div className="address-history"><span>Recent places</span>{history.map((item,index)=><button type="button" key={`${item.address}-${index}`} onClick={()=>onUse(item)}><Clock3/><span>{item.address}</span></button>)}</div>}</section>
}
function PlaceButton({icon,title,place,onUse,onEdit}:{icon:React.ReactNode;title:string;place:SavedPlace|undefined;onUse:(choice:AddressChoice)=>void;onEdit:()=>void}){return <div className="place-button-wrap"><button type="button" onClick={()=>place?onUse(place):onEdit()}>{icon}<span>{title}<small>{place?place.address:'Set address'}</small></span></button>{place&&<button type="button" className="edit-place" aria-label={`Change ${title}`} onClick={onEdit}><Pencil/></button>}</div>}
function SavedPlaceEditor({kind,onClose,onSave}:{kind:'home'|'work'|'favorite';onClose:()=>void;onSave:(choice:AddressChoice)=>Promise<void>}){const [value,setValue]=useState('');return <div className="saved-place-editor"><div><strong>Set {kind==='favorite'?'a favorite':kind}</strong><button type="button" onClick={onClose} aria-label="Close"><X/></button></div><AddressInput label={`Set ${kind}`} placeholder="Search for an address" value={value} required={false} onChange={setValue} onSelect={choice=>void onSave(choice)}/></div>}

function AddressInput({label,placeholder,value,onChange,onSelect,onFocus,onLocate,onMapPick,locating=false,required=true}:{label:string;placeholder:string;value:string;onChange:(value:string)=>void;onSelect:(choice:AddressChoice)=>void;onFocus?:()=>void;onLocate?:()=>void;onMapPick?:()=>void;locating?:boolean;required?:boolean}){
 const [items,setItems]=useState<AddressChoice[]>([]),[open,setOpen]=useState(false),[loading,setLoading]=useState(false),[resolving,setResolving]=useState(false),[message,setMessage]=useState('');const selected=useRef(false),sequence=useRef(0);
 useEffect(()=>{
  if(selected.current){selected.current=false;return}
  const query=value.trim(),current=++sequence.current;
  if(query.length<2)return;
  const controller=new AbortController(),timer=setTimeout(async()=>{
   setLoading(true);setMessage('');
   try{const response=await fetch(`/api/address/search?q=${encodeURIComponent(query)}`,{signal:controller.signal,cache:'no-store'}),data=await response.json() as {items?:AddressChoice[]};if(current!==sequence.current)return;const next=response.ok&&Array.isArray(data.items)?data.items:[];setItems(next);setOpen(true);if(!next.length)setMessage('No addresses found')}
   catch(error){if(error instanceof DOMException&&error.name==='AbortError')return;if(current===sequence.current){setItems([]);setOpen(true);setMessage('Address search is temporarily unavailable')}}
   finally{if(current===sequence.current)setLoading(false)}
  },180);
  return()=>{clearTimeout(timer);controller.abort()}
 },[value]);
 async function choose(item:AddressChoice){
  setOpen(false);setMessage('');
  if(item.fullAddress||!item.placeID){selected.current=true;setItems([]);onSelect(item);return}
  setResolving(true);
  try{const response=await fetch(`/api/address/resolve?placeId=${encodeURIComponent(item.placeID)}`,{cache:'no-store'}),data=await response.json() as {item?:AddressChoice;error?:string};if(!response.ok||!data.item)throw new Error(data.error||'Unable to verify this address.');selected.current=true;setItems([]);onSelect(data.item)}
  catch(error){setMessage(error instanceof Error?error.message:'Unable to verify this address.');setOpen(true)}finally{setResolving(false)}
 }
 return <span className={`address-search ${onLocate||onMapPick?'has-actions':''} ${onLocate&&onMapPick?'has-two-actions':''}`}><Input required={required} minLength={required?5:undefined} maxLength={250} aria-label={label} placeholder={placeholder} autoComplete="off" value={value} disabled={resolving} onFocus={()=>{onFocus?.();if(items.length||message)setOpen(true)}} onBlur={()=>setTimeout(()=>setOpen(false),140)} onChange={event=>{sequence.current++;setItems([]);setOpen(false);setLoading(false);setMessage('');onChange(event.target.value)}}/>{onMapPick&&<button type="button" className={`map-input-button ${onLocate?'with-location':''}`} aria-label={`Choose ${label.toLowerCase()} on map`} title="Choose on map" onMouseDown={event=>event.preventDefault()} onClick={onMapPick}><MapPin/></button>}{onLocate&&<button type="button" className={`location-input-button ${locating?'locating':''}`} aria-label="Use my current location" title="Use my current location" disabled={locating} onMouseDown={event=>event.preventDefault()} onClick={onLocate}><LocateFixed/></button>}{(loading||resolving)&&<span className="address-loading">{resolving?'Checking…':'Searching…'}</span>}{open&&(items.length>0||message)&&<span className="address-results">{items.map((item,index)=><button type="button" disabled={resolving} key={`${item.placeID||item.customAddressID||item.address}-${index}`} onMouseDown={event=>event.preventDefault()} onClick={()=>void choose(item)}><MapPin size={16}/><span>{item.address}</span></button>)}{message&&<span className="address-empty">{message}</span>}</span>}</span>
}

