'use client';
import {useEffect,useRef,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {vehicles,money} from '@/lib/vehicles';
import type {Service} from '@/lib/quote-policy';
import type {FareQuote} from '@/lib/quotes';
export type QuoteSelection={quote:FareQuote;token:string};
export default function QuoteChooser({pickup,destination,vias,onChoose}:{pickup:Record<string,unknown>|null;destination:Record<string,unknown>|null;vias:(Record<string,unknown>|null)[];onChoose:(value:QuoteSelection)=>void}){
 const [service,setService]=useState<Service>('priority'),[scheduled,setScheduled]=useState(''),[vehicle,setVehicle]=useState('saloon'),[config,setConfig]=useState<{enabled:boolean;minPrebookMinutes:number;vehicles:string[]}|null>(null),[offer,setOffer]=useState<QuoteSelection|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[expired,setExpired]=useState(false);
 const request=useRef<AbortController|null>(null),sequence=useRef(0);
 useEffect(()=>{const controller=new AbortController();fetch('/api/quotes',{cache:'no-store',signal:controller.signal}).then(async r=>{const data=await r.json() as {enabled:boolean;minPrebookMinutes:number;vehicles:string[];error?:string};if(!r.ok)throw new Error(data.error);setConfig(data)}).catch(e=>{if(!controller.signal.aborted)setError(e.message)});return()=>{controller.abort();request.current?.abort()}},[]);
 useEffect(()=>{if(!offer)return;const timer=setTimeout(()=>setExpired(true),Math.max(0,Date.parse(offer.quote.expiresAt)-Date.now()));return()=>clearTimeout(timer)},[offer]);
 function invalidate(){sequence.current++;request.current?.abort();setOffer(null);setError('');setBusy(false);setExpired(false)}
 async function getFare(){invalidate();const current=sequence.current,controller=new AbortController();request.current=controller;setBusy(true);const timeout=setTimeout(()=>controller.abort(),25000);try{
  const date=scheduled?new Date(scheduled):null;if(service==='guarantee'&&(!date||!Number.isFinite(date.getTime())))throw new Error('Choose your pick-up date and time.');
  const r=await fetch('/api/quotes',{method:'POST',headers:{'Content-Type':'application/json'},signal:controller.signal,body:JSON.stringify({pickup,destination,vias,vehicle,service,scheduledAt:service==='guarantee'?date!.toISOString():null})}),data=await r.json() as QuoteSelection&{error?:string};if(!r.ok)throw new Error(data.error||'Unable to retrieve your fare.');if(current===sequence.current)setOffer(data);
 }catch(e){if(current===sequence.current)setError(controller.signal.aborted?'The quote took too long. Please try again.':e instanceof Error?e.message:'Unable to retrieve fare.')}finally{clearTimeout(timeout);if(current===sequence.current)setBusy(false)}}
 return <div className="live-quote"><div className="quote-services" role="group" aria-label="Taxi service"><button type="button" aria-pressed={service==='priority'} onClick={()=>{invalidate();setService('priority')}}><strong>Priority taxi</strong><small>ASAP · demand-based supplement</small></button><button type="button" aria-pressed={service==='guarantee'} onClick={()=>{invalidate();setService('guarantee')}}><strong>Guarantee taxi</strong><small>Prebook · fare + supplement</small></button></div>
 {service==='guarantee'&&<label>Pick-up date & time<Input type="datetime-local" value={scheduled} onChange={e=>{invalidate();setScheduled(e.target.value)}}/><small>Minimum {config?.minPrebookMinutes??30} minutes ahead. Times are shown in your device’s local timezone.</small></label>}
 <label>Vehicle<select className="quote-vehicle" value={vehicle} onChange={e=>{invalidate();setVehicle(e.target.value)}}>{vehicles.map(v=><option key={v.id} value={v.id} disabled={!config?.vehicles.includes(v.id)}>{v.name} · {v.passengers} seats{config&&!config.vehicles.includes(v.id)?' · unavailable':''}</option>)}</select></label>
 {error&&<p className="error-message" role="alert">{error}</p>}{config&&!config.enabled&&<p>Live fares are temporarily unavailable.</p>}
 {offer&&!expired?<><div className="quote-breakdown"><div><span>Autocab fare</span><strong>{money(offer.quote.basePence)}</strong></div>{<div><span>{offer.quote.service==='priority'?'Priority':'Guarantee'} · {offer.quote.percent}%</span><strong>{money(offer.quote.upliftPence)}</strong></div>}<div><span>Total</span><strong>{money(offer.quote.totalPence)}</strong></div><small>Valid until {new Date(offer.quote.expiresAt).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit',second:'2-digit'})}. Card only.</small></div><Button className="primary-action" onClick={()=>{if(Date.now()>=Date.parse(offer.quote.expiresAt)){setExpired(true);return}onChoose(offer)}}>Choose {service==='priority'?'Priority':'Guarantee'} · {money(offer.quote.totalPence)}</Button></>:<><p className="small-note">{expired?'Your fare expired. Get a new quote to continue.':'The fare is calculated for your route and pick-up time.'}</p><Button className="primary-action" disabled={!config?.enabled||busy} onClick={getFare}>{busy?'Getting Autocab fare…':expired?'Get a new quote':'Get live fare'}</Button></>}
 <p className="small-note">Real fare quote. Booking confirmation remains in test mode: no charge or driver request.</p></div>
}
