import {createHash,createHmac,randomBytes,randomInt,randomUUID,timingSafeEqual} from 'node:crypto';
import {sendSmsMessage,SmsDeliveryError} from './sms-transport';
import {cookies} from 'next/headers';
import {database} from './database';
import {encryptCredentials,decryptCredentials} from './credentials';
import {loadIdentityPolicy,loadSmsPolicy} from './app-configuration';
import {setCustomerSession} from './customer-auth';
export class AuthError extends Error{constructor(message:string,public status=400){super(message)}}
export const hash=(value:string)=>createHash('sha256').update(value).digest('hex');
const secure=process.env.NODE_ENV==='production';
const cookieOptions={httpOnly:true,secure,sameSite:'lax' as const,path:'/',maxAge:1800};
const challengeCookie='nac_verification';
export const OTP_DIGITS=4;
export const OTP_SECONDS=30;
export function normalizePhone(value:string){let phone=value.replace(/[ ()-]/g,'');if(phone.startsWith('00'))phone='+'+phone.slice(2);if(phone.startsWith('0'))phone='+44'+phone.slice(1);if(!/^\+[1-9][0-9]{7,14}$/.test(phone))throw new AuthError('Enter a valid mobile number with country code.');return phone}
function codeHash(id:string,code:string){const secret=process.env.ADMIN_SESSION_SECRET;if(!secret||secret.length<32)throw new AuthError('Verification is not configured.',503);return createHmac('sha256',secret).update(id+':'+code).digest('hex')}
export async function authLimit(key:string,max=10,seconds=900){const result=await database().query('INSERT INTO customer_auth_limits(key,hits,until_at) VALUES($1,1,now()+$2*make_interval(secs=>1)) ON CONFLICT(key) DO UPDATE SET hits=CASE WHEN customer_auth_limits.until_at<=now() THEN 1 ELSE customer_auth_limits.hits+1 END,until_at=CASE WHEN customer_auth_limits.until_at<=now() THEN EXCLUDED.until_at ELSE customer_auth_limits.until_at END RETURNING hits',[hash(key),seconds]);if(result.rows[0].hits>max)throw new AuthError('Too many attempts. Please try again later.',429)}
export async function requestAuthLimit(request:Request){const ip=(request.headers.get('x-forwarded-for')||'unknown').split(',')[0].trim();await authLimit('auth-ip:'+ip,40)}
export async function trustedDevice(customerId:string){const token=(await cookies()).get('nac_trusted_device')?.value;if(!token)return false;return Boolean((await database().query('SELECT 1 FROM customer_trusted_devices WHERE token_hash=$1 AND customer_id=$2 AND expires_at>now()',[hash(token),customerId])).rowCount)}
async function trustDevice(customerId:string){const token=randomBytes(32).toString('base64url');await database().query('INSERT INTO customer_trusted_devices(token_hash,customer_id,expires_at) VALUES($1,$2,now()+make_interval(days=>30))',[hash(token),customerId]);(await cookies()).set('nac_trusted_device',token,{...cookieOptions,maxAge:2592000})}
async function sendCode(phone:string,code:string){const {settings:p,secrets}=await loadSmsPolicy();if(!p.enabled||!p.endpoint)throw new AuthError('SMS verification is not available yet.',503);const legacy='Your Need A Cab Plus verification code is {code}. It expires in 5 minutes.',template=p.template===legacy?'Your Need A Cab Plus verification code is {code}. It expires in {seconds} seconds.':p.template;try{await sendSmsMessage(p,secrets,phone,template.replaceAll('{code}',code).replaceAll('{seconds}',String(OTP_SECONDS)))}catch(error){throw new AuthError(error instanceof SmsDeliveryError?error.message:'SMS verification is not available yet.',503)}}
export async function beginChallenge(purpose:string,phone:string,payload:Record<string,string>,customerId:string|null=null,send=true){phone=phone?normalizePhone(phone):'';if(send){await authLimit('sms-phone:'+phone,5,1800);await authLimit('sms-cooldown:'+phone,1,OTP_SECONDS)}const token=randomBytes(32).toString('base64url'),id=hash(token),code=String(randomInt(0,10**OTP_DIGITS)).padStart(OTP_DIGITS,'0');await database().query('INSERT INTO customer_auth_challenges(id,purpose,customer_id,phone,payload_encrypted,code_hash,expires_at) VALUES($1,$2,$3,$4,$5,$6,now()+make_interval(mins=>10))',[id,purpose,customerId,phone,encryptCredentials(payload),send?codeHash(id,code):null]);try{if(send){await sendCode(phone,code);await database().query('UPDATE customer_auth_challenges SET expires_at=now()+$2*make_interval(secs=>1) WHERE id=$1',[id,OTP_SECONDS])}}catch(e){await database().query('DELETE FROM customer_auth_challenges WHERE id=$1',[id]);throw e}const store=await cookies(),old=store.get(challengeCookie)?.value;if(old)await database().query('UPDATE customer_auth_challenges SET consumed_at=now() WHERE id=$1 AND consumed_at IS NULL',[hash(old)]);store.set(challengeCookie,token,cookieOptions);return {verificationRequired:true,phoneRequired:!send,maskedPhone:phone?'••••'+phone.slice(-4):'',expiresIn:send?OTP_SECONDS:600}}
export async function pendingChallenge(){const token=(await cookies()).get(challengeCookie)?.value;if(!token)throw new AuthError('Start verification again.');const row=(await database().query('SELECT * FROM customer_auth_challenges WHERE id=$1 AND consumed_at IS NULL AND expires_at>now()',[hash(token)])).rows[0];if(!row)throw new AuthError('Verification expired. Please sign in or register again.');return row}
export async function challengeForResend(){const token=(await cookies()).get(challengeCookie)?.value;if(!token)throw new AuthError('Enter your mobile number again.');const row=(await database().query("SELECT * FROM customer_auth_challenges WHERE id=$1 AND consumed_at IS NULL AND created_at>now()-make_interval(mins=>30)",[hash(token)])).rows[0];if(!row)throw new AuthError('Enter your mobile number again.');return row}
export async function completeLogin(customerId:string,phone:string){const policy=await loadIdentityPolicy();if(policy.everyLoginOtp||(policy.newDeviceOtp&&!await trustedDevice(customerId)))return beginChallenge('login',phone,{},customerId,Boolean(phone));await setCustomerSession(customerId);return {ok:true}}
export async function finishChallenge(code:string){const token=(await cookies()).get(challengeCookie)?.value;if(!token)throw new AuthError('Start verification again.');const id=hash(token),db=await database().connect();let customerId:string|undefined;
try{await db.query('BEGIN');const row=(await db.query('SELECT * FROM customer_auth_challenges WHERE id=$1 FOR UPDATE',[id])).rows[0];if(!row||row.consumed_at||new Date(row.expires_at).getTime()<=Date.now()||row.attempts>=5||!row.code_hash)throw new AuthError('Code expired or too many attempts. Start again.');await db.query('UPDATE customer_auth_challenges SET attempts=attempts+1 WHERE id=$1',[id]);const actual=Buffer.from(codeHash(id,code),'hex'),expected=Buffer.from(row.code_hash,'hex');if(actual.length!==expected.length||!timingSafeEqual(actual,expected)){await db.query('COMMIT');throw new AuthError('Incorrect verification code.')}const payload=decryptCredentials(row.payload_encrypted);customerId=row.customer_id||randomUUID();if(!row.customer_id){await db.query('INSERT INTO customer_accounts(id,email,password_hash,full_name,phone,phone_verified_at) VALUES($1,$2,$3,$4,$5,now())',[customerId,payload.email,payload.passwordHash,payload.fullName,row.phone]);if(payload.provider)await db.query('INSERT INTO customer_identities(provider,subject,customer_id) VALUES($1,$2,$3)',[payload.provider,payload.subject,customerId])}else await db.query('UPDATE customer_accounts SET phone=$2,phone_verified_at=now() WHERE id=$1',[customerId,row.phone]);await db.query('UPDATE customer_auth_challenges SET consumed_at=now() WHERE id=$1',[id]);await db.query('COMMIT')}catch(e){await db.query('ROLLBACK');throw e}finally{db.release()}await trustDevice(customerId!);await setCustomerSession(customerId!);(await cookies()).set(challengeCookie,'',{...cookieOptions,maxAge:0});return {ok:true}}
