import {randomUUID} from 'node:crypto';
import {z} from 'zod';
import {getCustomer} from '@/lib/customer-auth';
import {database} from '@/lib/database';
import {sameOrigin,unavailable} from '@/lib/security';

const choice=z.object({address:z.string().trim().min(3).max(250),fullAddress:z.record(z.unknown()),placeID:z.string().nullable().optional()});
const saveSchema=choice.extend({kind:z.enum(['home','work','favorite']),name:z.string().trim().max(50).optional()});
const removeSchema=z.object({id:z.string().uuid()});
function item(row:Record<string,unknown>){return{id:String(row.id),kind:String(row.kind),name:String(row.name||''),address:String(row.address),fullAddress:row.full_address as Record<string,unknown>,placeID:row.place_id?String(row.place_id):null}}

export async function GET(){const customer=await getCustomer();if(!customer)return Response.json({places:[]},{headers:{'Cache-Control':'no-store'}});try{const result=await database().query('SELECT id,kind,name,address,full_address,place_id FROM customer_places WHERE customer_id=$1 ORDER BY CASE kind WHEN \'home\' THEN 0 WHEN \'work\' THEN 1 ELSE 2 END,updated_at DESC',[customer.id]);return Response.json({places:result.rows.map(item)},{headers:{'Cache-Control':'no-store'}})}catch(error){return unavailable(error)}}
export async function POST(request:Request){if(!sameOrigin(request))return Response.json({error:'Invalid request origin.'},{status:403});const customer=await getCustomer();if(!customer)return Response.json({error:'Sign in to save places.'},{status:401});try{const input=saveSchema.parse(await request.json()),name=input.name||(input.kind==='home'?'Home':input.kind==='work'?'Work':'Favorite'),db=database();let result;if(input.kind==='favorite')result=await db.query('INSERT INTO customer_places (id,customer_id,kind,name,address,full_address,place_id) VALUES ($1,$2,$3,$4,$5,$6,$7) RETURNING id,kind,name,address,full_address,place_id',[randomUUID(),customer.id,input.kind,name,input.address,input.fullAddress,input.placeID||null]);else result=await db.query(`INSERT INTO customer_places (id,customer_id,kind,name,address,full_address,place_id) VALUES ($1,$2,$3,$4,$5,$6,$7) ON CONFLICT (customer_id,kind) WHERE kind IN ('home','work') DO UPDATE SET name=EXCLUDED.name,address=EXCLUDED.address,full_address=EXCLUDED.full_address,place_id=EXCLUDED.place_id,updated_at=now() RETURNING id,kind,name,address,full_address,place_id`,[randomUUID(),customer.id,input.kind,name,input.address,input.fullAddress,input.placeID||null]);return Response.json({place:item(result.rows[0])})}catch(error){if(error instanceof z.ZodError)return Response.json({error:'Choose a valid address.'},{status:400});return unavailable(error)}}
export async function DELETE(request:Request){if(!sameOrigin(request))return Response.json({error:'Invalid request origin.'},{status:403});const customer=await getCustomer();if(!customer)return Response.json({error:'Authentication required.'},{status:401});try{const input=removeSchema.parse(await request.json());await database().query('DELETE FROM customer_places WHERE id=$1 AND customer_id=$2',[input.id,customer.id]);return Response.json({ok:true})}catch(error){if(error instanceof z.ZodError)return Response.json({error:'Invalid saved place.'},{status:400});return unavailable(error)}}
