import {bookingCreateUrl} from '@/lib/autocab-booking-request';
import {splitSmsEndpoint} from '@/lib/sms-endpoint';
import {z} from 'zod';
import {isAdmin,sameOrigin,unavailable} from '@/lib/security';
import {database} from '@/lib/database';
import {readConfiguration,loadBookingPolicy} from '@/lib/app-configuration';
import {bookingPolicySchema} from '@/lib/booking-policy';
import {smsPolicySchema,identityPolicySchema} from '@/lib/customer-security-policy';
import {encryptCredentials,decryptCredentials} from '@/lib/credentials';
export async function GET(){if(!await isAdmin())return Response.json({error:'Administrator access required.'},{status:403});try{const result:Record<string,unknown>={bookings:await loadBookingPolicy()};for(const section of ['sms','identity']){const row=await readConfiguration(section),secrets=row.secrets_encrypted?decryptCredentials(row.secrets_encrypted):{};result[section]=(section==='sms'?smsPolicySchema:identityPolicySchema).parse(row.settings);result[section+'Secrets']=Object.fromEntries(Object.entries(secrets).map(([k,v])=>[k,Boolean(v)]))}result.liveBookingAttempts=(await database().query("SELECT quote_id,state,external_booking_id,created_at FROM web_booking_attempts ORDER BY created_at DESC LIMIT 10")).rows;return Response.json(result,{headers:{'Cache-Control':'no-store','X-Customer-Configuration':'v1'}})}catch(e){return unavailable(e)}}
export async function PUT(request:Request){if(!sameOrigin(request)||!await isAdmin())return Response.json({error:'Administrator access required.'},{status:403});try{const body=z.object({section:z.enum(['bookings','sms','identity']),settings:z.record(z.string(),z.unknown()),secrets:z.record(z.string(),z.string().max(20000)).default({})}).strict().parse(await request.json());const settings=(body.section==='bookings'?bookingPolicySchema:body.section==='sms'?smsPolicySchema:identityPolicySchema).parse(body.settings);const row=await readConfiguration(body.section),secrets:Record<string,string>=row.secrets_encrypted?decryptCredentials(row.secrets_encrypted):{};const allowed=body.section==='sms'?['token']:body.section==='identity'?['googleClientSecret','applePrivateKey']:[];for(const [k,v] of Object.entries(body.secrets)){if(!allowed.includes(k))throw new Error('Unknown secret field');if(v.trim())secrets[k]=v.trim()}
if(body.section==='bookings'&&bookingPolicySchema.parse(settings).liveBookingsEnabled){const endpoint=await database().query("SELECT c.base_url,e.path,e.method FROM api_endpoints e JOIN api_connections c ON c.id=e.connection_id WHERE c.provider='autocab' AND e.action_key='booking.create' AND e.enabled=true ORDER BY e.created_at DESC,c.created_at DESC LIMIT 1");if(!endpoint.rows[0])throw new Error('Configure an enabled booking.create API endpoint before enabling live bookings.');const e=endpoint.rows[0];bookingCreateUrl(e.base_url,e.path,e.method)}
if(body.section==='sms'){const p=smsPolicySchema.parse(settings);if(p.endpoint){const parsed=splitSmsEndpoint(p.endpoint);if(parsed.query)secrets.endpointQuery=parsed.query;else if(p.endpoint!==smsPolicySchema.parse(row.settings).endpoint)delete secrets.endpointQuery;(settings as {endpoint:string}).endpoint=parsed.endpoint;}if(p.enabled&&(!p.endpoint||!p.template.includes('{code}')))throw new Error('Enter an SMS endpoint and a template containing {code}.');if(new Set([p.phoneField,p.messageField,p.senderField]).size!==3)throw new Error('SMS field names must be different.');if(!p.enabled){const identity=identityPolicySchema.parse((await readConfiguration('identity')).settings);if(identity.registrationOtp||identity.newDeviceOtp||identity.everyLoginOtp)throw new Error('Disable OTP requirements before disabling SMS.')}}
if(body.section==='identity'){const p=identityPolicySchema.parse(settings);if((p.registrationOtp||p.newDeviceOtp||p.everyLoginOtp)&&!smsPolicySchema.parse((await readConfiguration('sms')).settings).enabled)throw new Error('Configure and enable SMS before requiring OTP.');if(p.googleEnabled&&(!p.googleClientId||!secrets.googleClientSecret))throw new Error('Google client ID and secret are required.');if(p.appleEnabled&&(!p.appleClientId||!p.appleTeamId||!p.appleKeyId||!secrets.applePrivateKey))throw new Error('Apple Service ID, Team ID, Key ID and private key are required.')}
await database().query('INSERT INTO app_configuration(section,settings,secrets_encrypted) VALUES($1,$2::jsonb,$3) ON CONFLICT(section) DO UPDATE SET settings=EXCLUDED.settings,secrets_encrypted=EXCLUDED.secrets_encrypted,updated_at=now()',[body.section,JSON.stringify(settings),Object.keys(secrets).length?encryptCredentials(secrets):'']);return Response.json({ok:true,settings,secretPresence:Object.fromEntries(Object.entries(secrets).map(([k,v])=>[k,Boolean(v)]))})}catch(e){return Response.json({error:e instanceof z.ZodError?e.issues[0]?.message:e instanceof Error?e.message:'Unable to save settings.'},{status:400})}}
