import {z} from 'zod';
import {isAdmin,sameOrigin,unavailable} from '@/lib/security';
import {database} from '@/lib/database';
import {readConfiguration,loadBookingPolicy} from '@/lib/app-configuration';
import {bookingPolicySchema} from '@/lib/booking-policy';
import {smsPolicySchema,identityPolicySchema} from '@/lib/customer-security-policy';
import {encryptCredentials,decryptCredentials} from '@/lib/credentials';
export async function GET(){if(!await isAdmin())return Response.json({error:'Administrator access required.'},{status:403});try{const result:Record<string,unknown>={bookings:await loadBookingPolicy()};for(const section of ['sms','identity']){const row=await readConfiguration(section),secrets=row.secrets_encrypted?decryptCredentials(row.secrets_encrypted):{};result[section]=(section==='sms'?smsPolicySchema:identityPolicySchema).parse(row.settings);result[section+'Secrets']=Object.fromEntries(Object.entries(secrets).map(([k,v])=>[k,Boolean(v)]))}return Response.json(result,{headers:{'Cache-Control':'no-store','X-Customer-Configuration':'v1'}})}catch(e){return unavailable(e)}}
export async function PUT(request:Request){if(!sameOrigin(request)||!await isAdmin())return Response.json({error:'Administrator access required.'},{status:403});try{const body=z.object({section:z.enum(['bookings','sms','identity']),settings:z.record(z.string(),z.unknown()),secrets:z.record(z.string(),z.string().max(20000)).default({})}).strict().parse(await request.json());const settings=(body.section==='bookings'?bookingPolicySchema:body.section==='sms'?smsPolicySchema:identityPolicySchema).parse(body.settings);const row=await readConfiguration(body.section),secrets:Record<string,string>=row.secrets_encrypted?decryptCredentials(row.secrets_encrypted):{};const allowed=body.section==='sms'?['token']:body.section==='identity'?['googleClientSecret','applePrivateKey']:[];for(const [k,v] of Object.entries(body.secrets)){if(!allowed.includes(k))throw new Error('Unknown secret field');if(v.trim())secrets[k]=v.trim()}
if(body.section==='sms'){const p=smsPolicySchema.parse(settings);if(p.endpoint){const u=new URL(p.endpoint);if(u.protocol!=='https:'||u.username||u.password||u.hash||u.search||!u.hostname.includes('.')||/^(localhost|127\.|10\.|192\.168\.|169\.254\.|172\.(1[6-9]|2[0-9]|3[01])\.)/.test(u.hostname)||u.hostname.includes(':'))throw new Error('Use a public HTTPS SMS endpoint without credentials or query parameters.')}if(p.enabled&&(!p.endpoint||!p.template.includes('{code}')))throw new Error('Enter an SMS endpoint and a template containing {code}.');if(new Set([p.phoneField,p.messageField,p.senderField]).size!==3)throw new Error('SMS field names must be different.');if(!p.enabled){const identity=identityPolicySchema.parse((await readConfiguration('identity')).settings);if(identity.registrationOtp||identity.newDeviceOtp)throw new Error('Disable OTP requirements before disabling SMS.')}}
if(body.section==='identity'){const p=identityPolicySchema.parse(settings);if((p.registrationOtp||p.newDeviceOtp)&&!smsPolicySchema.parse((await readConfiguration('sms')).settings).enabled)throw new Error('Configure and enable SMS before requiring OTP.');if(p.googleEnabled&&(!p.googleClientId||!secrets.googleClientSecret))throw new Error('Google client ID and secret are required.');if(p.appleEnabled&&(!p.appleClientId||!p.appleTeamId||!p.appleKeyId||!secrets.applePrivateKey))throw new Error('Apple Service ID, Team ID, Key ID and private key are required.')}
await database().query('INSERT INTO app_configuration(section,settings,secrets_encrypted) VALUES($1,$2::jsonb,$3) ON CONFLICT(section) DO UPDATE SET settings=EXCLUDED.settings,secrets_encrypted=EXCLUDED.secrets_encrypted,updated_at=now()',[body.section,JSON.stringify(settings),Object.keys(secrets).length?encryptCredentials(secrets):'']);return Response.json({ok:true})}catch(e){return Response.json({error:e instanceof z.ZodError?e.issues[0]?.message:e instanceof Error?e.message:'Unable to save settings.'},{status:400})}}
