'use client';
import {FormEvent,useCallback,useEffect,useState} from 'react';
import {Braces,ChevronDown,ChevronRight,KeyRound,Link2,Plus,RefreshCw,Server,Trash2,X} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';

type Connection={id:string;name:string;base_url:string;auth_type:'none'|'api_key'|'bearer'|'basic';api_key_header:string};
type Endpoint={id:string;connection_id:string;name:string;action_key:string;method:string;path:string;description:string;enabled:boolean};
const emptyConnection={name:'Autocab Production',baseUrl:'',authType:'api_key',apiKeyHeader:'x-api-key',token:'',username:'',password:''};
const emptyEndpoint={connectionId:'',name:'',actionKey:'',method:'GET',path:'',description:''};

export default function ApiConnections(){
 const [connections,setConnections]=useState<Connection[]>([]),[endpoints,setEndpoints]=useState<Endpoint[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const [connectionForm,setConnectionForm]=useState(emptyConnection),[endpointForm,setEndpointForm]=useState(emptyEndpoint),[showConnection,setShowConnection]=useState(false),[showEndpoint,setShowEndpoint]=useState(false),[open,setOpen]=useState<Record<string,boolean>>({});
 const refresh=useCallback(async()=>{setLoading(true);setError('');try{const response=await fetch('/api/admin/autocab');const data=await response.json() as {connections:Connection[];endpoints:Endpoint[];error?:string};if(!response.ok)throw new Error(data.error);setConnections(data.connections);setEndpoints(data.endpoints);setEndpointForm(form=>({...form,connectionId:form.connectionId||data.connections[0]?.id||''}))}catch(reason){setError(reason instanceof Error?reason.message:'Unable to load Autocab APIs.')}finally{setLoading(false)}},[]);
 useEffect(()=>{
  // The initial request hydrates this client-only configuration manager.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  void refresh();
 },[refresh]);
 async function send(payload:unknown){setBusy(true);setError('');setMessage('');try{const response=await fetch('/api/admin/autocab',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await response.json() as {error?:string};if(!response.ok)throw new Error(data.error);await refresh();setMessage('Saved successfully.')}catch(reason){setError(reason instanceof Error?reason.message:'Unable to save.')}finally{setBusy(false)}}
 async function addConnection(event:FormEvent){event.preventDefault();await send({type:'connection',...connectionForm});setConnectionForm(emptyConnection);setShowConnection(false)}
 async function addEndpoint(event:FormEvent){event.preventDefault();await send({type:'endpoint',...endpointForm});setEndpointForm(form=>({...emptyEndpoint,connectionId:form.connectionId}));setShowEndpoint(false)}
 async function remove(type:'connection'|'endpoint',id:string){if(!confirm(`Delete this ${type} configuration?`))return;setBusy(true);setError('');try{const response=await fetch('/api/admin/autocab',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({type,id})});const data=await response.json() as {error?:string};if(!response.ok)throw new Error(data.error);await refresh()}catch(reason){setError(reason instanceof Error?reason.message:'Unable to delete.')}finally{setBusy(false)}}
 return <div className="api-manager">
  <div className="config-section-title"><div className="config-icon"><Braces/></div><div><h3>Autocab API connections</h3><p>Add the connection once, then register every Autocab API endpoint you want to use as a flow action.</p></div><span className="config-status"><span/>{connections.length} connection{connections.length===1?'':'s'}</span></div>
  <div className="api-actions"><Button type="button" onClick={()=>setShowConnection(value=>!value)}><Plus/>Add connection</Button><Button type="button" variant="outline" disabled={!connections.length} onClick={()=>setShowEndpoint(value=>!value)}><Braces/>Add API endpoint</Button><Button type="button" variant="ghost" onClick={()=>void refresh()} disabled={loading}><RefreshCw/>Refresh</Button></div>
  {error&&<p className="error-message" role="alert">{error}</p>}{message&&<p className="saved-message" role="status">{message}</p>}
  {showConnection&&<form className="api-form" onSubmit={addConnection}><div className="form-heading"><div><strong>New Autocab connection</strong><p>Credentials are encrypted before they are stored.</p></div><button type="button" onClick={()=>setShowConnection(false)} aria-label="Close"><X/></button></div><div className="form-grid"><label>Connection name<Input required value={connectionForm.name} onChange={event=>setConnectionForm({...connectionForm,name:event.target.value})}/></label><label>API base URL<Input type="url" required placeholder="https://api.autocab.net" value={connectionForm.baseUrl} onChange={event=>setConnectionForm({...connectionForm,baseUrl:event.target.value})}/></label><label>Authentication<select value={connectionForm.authType} onChange={event=>setConnectionForm({...connectionForm,authType:event.target.value as typeof connectionForm.authType})}><option value="api_key">API key</option><option value="bearer">Bearer token</option><option value="basic">Username and password</option><option value="none">No authentication</option></select></label>{connectionForm.authType==='api_key'&&<label>Header name<Input required value={connectionForm.apiKeyHeader} onChange={event=>setConnectionForm({...connectionForm,apiKeyHeader:event.target.value})}/></label>}{(connectionForm.authType==='api_key'||connectionForm.authType==='bearer')&&<label className="full-field">{connectionForm.authType==='api_key'?'API key':'Bearer token'}<Input type="password" required autoComplete="new-password" value={connectionForm.token} onChange={event=>setConnectionForm({...connectionForm,token:event.target.value})}/></label>}{connectionForm.authType==='basic'&&<><label>Username<Input required autoComplete="off" value={connectionForm.username} onChange={event=>setConnectionForm({...connectionForm,username:event.target.value})}/></label><label>Password<Input type="password" required autoComplete="new-password" value={connectionForm.password} onChange={event=>setConnectionForm({...connectionForm,password:event.target.value})}/></label></>}</div><Button disabled={busy} type="submit"><KeyRound/>{busy?'Saving…':'Save encrypted connection'}</Button></form>}
  {showEndpoint&&<form className="api-form" onSubmit={addEndpoint}><div className="form-heading"><div><strong>Add an Autocab API endpoint</strong><p>This endpoint becomes an action available in the Flow Builder.</p></div><button type="button" onClick={()=>setShowEndpoint(false)} aria-label="Close"><X/></button></div><div className="form-grid"><label>Connection<select required value={endpointForm.connectionId} onChange={event=>setEndpointForm({...endpointForm,connectionId:event.target.value})}>{connections.map(connection=><option key={connection.id} value={connection.id}>{connection.name}</option>)}</select></label><label>Action name<Input required placeholder="Update booking" value={endpointForm.name} onChange={event=>setEndpointForm({...endpointForm,name:event.target.value,actionKey:event.target.value.toLowerCase().trim().replace(/[^a-z0-9]+/g,'.').replace(/^\.|\.$/g,'')})}/></label><label>Action key<Input required placeholder="booking.update" pattern="[a-z][a-z0-9_.-]{2,79}" value={endpointForm.actionKey} onChange={event=>setEndpointForm({...endpointForm,actionKey:event.target.value})}/></label><label>HTTP method<select value={endpointForm.method} onChange={event=>setEndpointForm({...endpointForm,method:event.target.value})}>{['GET','POST','PUT','PATCH','DELETE'].map(method=><option key={method}>{method}</option>)}</select></label><label className="full-field">Endpoint path<Input required placeholder="/bookings/{bookingId}" value={endpointForm.path} onChange={event=>setEndpointForm({...endpointForm,path:event.target.value})}/></label><label className="full-field">Description<textarea placeholder="What this API action does" value={endpointForm.description} onChange={event=>setEndpointForm({...endpointForm,description:event.target.value})}/></label></div><Button disabled={busy} type="submit"><Plus/>{busy?'Saving…':'Add API action'}</Button></form>}
  <div className="connection-list">{loading?<div className="api-empty">Loading connections…</div>:connections.length===0?<div className="api-empty"><Server/><strong>No Autocab connection yet</strong><p>Add the API base URL and authentication first. You can then add as many endpoints as required.</p></div>:connections.map(connection=>{const items=endpoints.filter(endpoint=>endpoint.connection_id===connection.id);const expanded=open[connection.id]??true;return <article className="connection-card" key={connection.id}><header><button type="button" className="connection-toggle" onClick={()=>setOpen(value=>({...value,[connection.id]:!expanded}))}>{expanded?<ChevronDown/>:<ChevronRight/>}<span className="connection-symbol"><Link2/></span><span><strong>{connection.name}</strong><small>{connection.base_url}</small></span></button><span className="auth-chip"><KeyRound/>{connection.auth_type.replace('_',' ')}</span><span className="endpoint-count">{items.length} API{items.length===1?'':'s'}</span><button className="delete-icon" type="button" aria-label={`Delete ${connection.name}`} disabled={busy} onClick={()=>void remove('connection',connection.id)}><Trash2/></button></header>{expanded&&<div className="endpoint-list">{items.length===0?<p>No API endpoints added to this connection.</p>:items.map(endpoint=><div className="endpoint-item" key={endpoint.id}><span className={`method method-${endpoint.method.toLowerCase()}`}>{endpoint.method}</span><div><strong>{endpoint.name}</strong><code>{endpoint.path}</code><small>{endpoint.action_key}{endpoint.description?` · ${endpoint.description}`:''}</small></div><span className="config-status ready"><span/>Available in flows</span><button className="delete-icon" type="button" aria-label={`Delete ${endpoint.name}`} disabled={busy} onClick={()=>void remove('endpoint',endpoint.id)}><Trash2/></button></div>)}</div>}</article>})}</div>
 </div>;
}
