'use client';
import {useEffect,useRef,useState} from 'react';
import {BadgePoundSterling,FlaskConical,LoaderCircle,MapPin,Search,X} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';

type Result={ok:boolean;capabilities:number[];pricePence?:number;cost?:number|null;bookingCost?:number|null;tariff?:Record<string,string|number|boolean>;error?:string};
type ResponseData={testOnly?:boolean;bookingCreated?:boolean;capabilityId?:number;service?:string;paymentMethod?:string;scheduledAt?:string|null;resolved?:{pickup:string;destination:string};control?:Result;discounted?:Result;error?:string};
type AddressChoice={address:string;fullAddress:Record<string,unknown>|null;placeID?:string|null;customAddressID?:string|number|null};
const pounds=(pence:number|undefined)=>typeof pence==='number'?new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP'}).format(pence/100):'—';
const amount=(value:number|null|undefined)=>typeof value==='number'?new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP'}).format(value):'—';
function ResultCard({title,result}:{title:string;result:Result}){
 const tariff=result.tariff&&Object.keys(result.tariff).length?Object.entries(result.tariff).map(([key,value])=>`${key}: ${value}`).join(' · '):'No tariff identifier returned';
 return <article className={`capability-test-result ${result.ok?'success':'failed'}`}><header><strong>{title}</strong><span>{result.capabilities.length?result.capabilities.join(', '):'No capabilities'}</span></header>{result.ok?<><b>{pounds(result.pricePence)}</b><dl><div><dt>Cost</dt><dd>{amount(result.cost)}</dd></div><div><dt>Booking cost</dt><dd>{amount(result.bookingCost)}</dd></div></dl><small>{tariff}</small></>:<p>{result.error}</p>}</article>;
}
function AddressAutocomplete({label,placeholder,onSelect}:{label:string;placeholder:string;onSelect:(choice:AddressChoice|null)=>void}){
 const [query,setQuery]=useState(''),[items,setItems]=useState<AddressChoice[]>([]),[open,setOpen]=useState(false),[loading,setLoading]=useState(false),[message,setMessage]=useState('');
 const sequence=useRef(0),selected=useRef(false),input=useRef<HTMLInputElement>(null);
 useEffect(()=>{if(selected.current){selected.current=false;return}const text=query.trim(),current=++sequence.current;if(text.length<2)return;const controller=new AbortController(),timer=setTimeout(async()=>{setLoading(true);setMessage('');try{const response=await fetch(`/api/address/search?q=${encodeURIComponent(text)}`,{cache:'no-store',signal:controller.signal}),data=await response.json() as {items?:AddressChoice[];error?:string};if(current!==sequence.current)return;if(!response.ok)throw new Error(data.error||'Address search is unavailable.');const next=data.items||[];setItems(next);setOpen(true);if(!next.length)setMessage('No matching addresses found.')}catch(reason){if(reason instanceof DOMException&&reason.name==='AbortError')return;if(current===sequence.current){setItems([]);setOpen(true);setMessage(reason instanceof Error?reason.message:'Address search is unavailable.')}}finally{if(current===sequence.current)setLoading(false)}},150);return()=>{clearTimeout(timer);controller.abort()}},[query]);
 async function choose(choice:AddressChoice){sequence.current++;setLoading(true);setMessage('');try{let resolved=choice;if(!resolved.fullAddress){if(!resolved.placeID)throw new Error('This address could not be resolved.');const response=await fetch(`/api/address/resolve?placeId=${encodeURIComponent(resolved.placeID)}`,{cache:'no-store'}),data=await response.json() as {item?:AddressChoice;error?:string};if(!response.ok||!data.item?.fullAddress)throw new Error(data.error||'This address could not be resolved.');resolved=data.item}selected.current=true;setQuery(resolved.address);setItems([]);setOpen(false);onSelect(resolved)}catch(reason){setMessage(reason instanceof Error?reason.message:'This address could not be resolved.');setOpen(true)}finally{setLoading(false)}}
 function clear(){sequence.current++;selected.current=true;setQuery('');setItems([]);setOpen(false);setMessage('');onSelect(null);requestAnimationFrame(()=>input.current?.focus())}
 return <label className="capability-address-field"><span className="field-label">{label}</span><span className="capability-address-input"><Search/><Input ref={input} required minLength={2} maxLength={250} autoComplete="off" placeholder={placeholder} value={query} onFocus={()=>{if(items.length||message)setOpen(true)}} onBlur={()=>setTimeout(()=>setOpen(false),150)} onChange={event=>{const next=event.target.value;onSelect(null);if(next.trim().length<2){sequence.current++;setItems([]);setOpen(false);setMessage('')}setQuery(next)}}/>{loading?<LoaderCircle className="spinning"/>:query?<button type="button" aria-label={`Clear ${label.toLowerCase()}`} onMouseDown={event=>event.preventDefault()} onClick={clear}><X/></button>:null}</span>{open&&<span className="capability-address-results">{items.map((item,index)=><button type="button" key={`${item.placeID||item.customAddressID||item.address}-${index}`} onMouseDown={event=>event.preventDefault()} onClick={()=>void choose(item)}><MapPin/><span>{item.address}</span></button>)}{message&&<small>{message}</small>}</span>}</label>;
}
export default function CapabilityQuoteTest(){
 const [capabilityId,setCapabilityId]=useState(42),[pickup,setPickup]=useState<AddressChoice|null>(null),[destination,setDestination]=useState<AddressChoice|null>(null),[service,setService]=useState<'asap'|'priority'|'guarantee'>('asap'),[paymentMethod,setPaymentMethod]=useState<'cash'|'card'>('cash');
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[result,setResult]=useState<ResponseData|null>(null);
 async function run(event:React.FormEvent){event.preventDefault();if(!pickup?.fullAddress||!destination?.fullAddress){setError('Select both addresses from the autocomplete results.');return}setBusy(true);setError('');setResult(null);try{const response=await fetch('/api/admin/capability-quote-test',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({capabilityId,pickup,destination,service,paymentMethod})}),data=await response.json() as ResponseData;if(!response.ok)throw new Error(data.error||'The comparison could not be completed.');setResult(data)}catch(reason){setError(reason instanceof Error?reason.message:'The comparison could not be completed.')}finally{setBusy(false)}}
 const difference=result?.control?.ok&&result.discounted?.ok&&typeof result.control.pricePence==='number'&&typeof result.discounted.pricePence==='number'?result.discounted.pricePence-result.control.pricePence:null;
 return <section className="capability-quote-test"><header><span><FlaskConical/></span><div><span className="pricing-chip">NO BOOKING CREATED</span><h4>Capability fare comparison</h4><p>Compare the same live Autocab quote without and with a capability. Saved booking settings are not changed.</p></div></header><form onSubmit={run}><div className="settings-grid"><AddressAutocomplete label="Pick-up address" placeholder="Start typing a pickup address" onSelect={setPickup}/><AddressAutocomplete label="Destination address" placeholder="Start typing a destination" onSelect={setDestination}/><label><span className="field-label">Capability ID</span><Input required type="number" min={1} max={1000000} value={capabilityId} onChange={event=>setCapabilityId(Number(event.target.value))}/></label><label><span className="field-label">Service</span><select value={service} onChange={event=>setService(event.target.value as 'asap'|'priority'|'guarantee')}><option value="asap">NOW · ASAP</option><option value="priority">Priority · ASAP</option><option value="guarantee">Guarantee · prebook</option></select></label><label><span className="field-label">Payment profile</span><select value={paymentMethod} onChange={event=>setPaymentMethod(event.target.value as 'cash'|'card')}><option value="cash">Cash</option><option value="card">Card</option></select></label></div><Button disabled={busy||!pickup?.fullAddress||!destination?.fullAddress}><FlaskConical/>{busy?'Comparing live quotes…':'Run A/B quote test'}</Button></form>{error&&<p className="error-message" role="alert">{error}</p>}{result?.resolved&&<p className="capability-test-route"><strong>Resolved route:</strong> {result.resolved.pickup} → {result.resolved.destination}</p>}{result?.control&&result.discounted&&<><div className="capability-test-results"><ResultCard title={`Control · without capability ${result.capabilityId??capabilityId}`} result={result.control}/><ResultCard title={`Discounted Fare · with capability ${result.capabilityId??capabilityId}`} result={result.discounted}/></div>{difference!==null&&<div className={`capability-test-verdict ${difference===0?'same':'changed'}`}><BadgePoundSterling/><span><strong>{difference===0?`Capability ${result.capabilityId??capabilityId} did not change the fare.`:`Fare changed by ${pounds(Math.abs(difference))}.`}</strong><small>{difference<0?'The capability returned a lower passenger fare.':difference>0?'The capability returned a higher passenger fare.':'It may only filter eligible drivers unless Autocab has another pricing rule.'}</small></span></div>}</>}</section>;
}
