'use client';
import {useState} from 'react';
import {BadgePoundSterling,FlaskConical} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';

type Result={ok:boolean;capabilities:number[];pricePence?:number;cost?:number|null;bookingCost?:number|null;tariff?:Record<string,string|number|boolean>;error?:string};
type ResponseData={testOnly?:boolean;bookingCreated?:boolean;capabilityId?:number;service?:string;paymentMethod?:string;scheduledAt?:string|null;resolved?:{pickup:string;destination:string};control?:Result;discounted?:Result;error?:string};
const pounds=(pence:number|undefined)=>typeof pence==='number'?new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP'}).format(pence/100):'—';
const amount=(value:number|null|undefined)=>typeof value==='number'?new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP'}).format(value):'—';
function ResultCard({title,result}:{title:string;result:Result}){
 const tariff=result.tariff&&Object.keys(result.tariff).length?Object.entries(result.tariff).map(([key,value])=>`${key}: ${value}`).join(' · '):'No tariff identifier returned';
 return <article className={`capability-test-result ${result.ok?'success':'failed'}`}><header><strong>{title}</strong><span>{result.capabilities.length?result.capabilities.join(', '):'No capabilities'}</span></header>{result.ok?<><b>{pounds(result.pricePence)}</b><dl><div><dt>Cost</dt><dd>{amount(result.cost)}</dd></div><div><dt>Booking cost</dt><dd>{amount(result.bookingCost)}</dd></div></dl><small>{tariff}</small></>:<p>{result.error}</p>}</article>;
}
export default function CapabilityQuoteTest(){
 const [capabilityId,setCapabilityId]=useState(42),[pickup,setPickup]=useState(''),[destination,setDestination]=useState(''),[service,setService]=useState<'priority'|'guarantee'>('priority'),[paymentMethod,setPaymentMethod]=useState<'cash'|'card'>('cash');
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[result,setResult]=useState<ResponseData|null>(null);
 async function run(event:React.FormEvent){event.preventDefault();setBusy(true);setError('');setResult(null);try{const response=await fetch('/api/admin/capability-quote-test',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({capabilityId,pickup,destination,service,paymentMethod})}),data=await response.json() as ResponseData;if(!response.ok)throw new Error(data.error||'The comparison could not be completed.');setResult(data)}catch(reason){setError(reason instanceof Error?reason.message:'The comparison could not be completed.')}finally{setBusy(false)}}
 const difference=result?.control?.ok&&result.discounted?.ok&&typeof result.control.pricePence==='number'&&typeof result.discounted.pricePence==='number'?result.discounted.pricePence-result.control.pricePence:null;
 return <section className="capability-quote-test"><header><span><FlaskConical/></span><div><span className="pricing-chip">NO BOOKING CREATED</span><h4>Capability fare comparison</h4><p>Compare the same live Autocab quote without and with a capability. Saved booking settings are not changed.</p></div></header><form onSubmit={run}><div className="settings-grid"><label><span className="field-label">Pick-up address</span><Input required minLength={5} maxLength={250} placeholder="Full pickup address" value={pickup} onChange={event=>setPickup(event.target.value)}/></label><label><span className="field-label">Destination address</span><Input required minLength={5} maxLength={250} placeholder="Full destination address" value={destination} onChange={event=>setDestination(event.target.value)}/></label><label><span className="field-label">Capability ID</span><Input required type="number" min={1} max={1000000} value={capabilityId} onChange={event=>setCapabilityId(Number(event.target.value))}/></label><label><span className="field-label">Service</span><select value={service} onChange={event=>setService(event.target.value as 'priority'|'guarantee')}><option value="priority">Priority · ASAP</option><option value="guarantee">Guarantee · prebook</option></select></label><label><span className="field-label">Payment profile</span><select value={paymentMethod} onChange={event=>setPaymentMethod(event.target.value as 'cash'|'card')}><option value="cash">Cash</option><option value="card">Card</option></select></label></div><Button disabled={busy}><FlaskConical/>{busy?'Comparing live quotes…':'Run A/B quote test'}</Button></form>{error&&<p className="error-message" role="alert">{error}</p>}{result?.resolved&&<p className="capability-test-route"><strong>Resolved route:</strong> {result.resolved.pickup} → {result.resolved.destination}</p>}{result?.control&&result.discounted&&<><div className="capability-test-results"><ResultCard title={`Control · without capability ${result.capabilityId??capabilityId}`} result={result.control}/><ResultCard title={`Discounted Fare · with capability ${result.capabilityId??capabilityId}`} result={result.discounted}/></div>{difference!==null&&<div className={`capability-test-verdict ${difference===0?'same':'changed'}`}><BadgePoundSterling/><span><strong>{difference===0?`Capability ${result.capabilityId??capabilityId} did not change the fare.`:`Fare changed by ${pounds(Math.abs(difference))}.`}</strong><small>{difference<0?'The capability returned a lower passenger fare.':difference>0?'The capability returned a higher passenger fare.':'It may only filter eligible drivers unless Autocab has another pricing rule.'}</small></span></div>}</>}</section>;
}
