'use client';
import {useEffect,useState} from 'react';
import {defaultBookingPolicy} from '@/lib/booking-policy';
import {smsPolicySchema,identityPolicySchema} from '@/lib/customer-security-policy';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
type Values=Record<string,string|number|boolean|number[]|null>;
const defaults={bookings:defaultBookingPolicy,sms:smsPolicySchema.parse({}),identity:identityPolicySchema.parse({})};
const labels:Record<string,string>={companyId:'Autocab company ID',accountCustomerId:'Card account customer ID (Web Booker Card / WBC)',cashAccountCustomerId:'Cash account customer ID (optional)',paymentMethod:'Payment method',priorityDelayMinutes:'Priority: add minutes to current time',minPrebookMinutes:'Guarantee Taxi: minimum advance notice (minutes)',priorityCapabilities:'Priority capability IDs',guaranteeCapabilities:'Guarantee capability IDs',saloonCapabilities:'Saloon capability IDs',estateCapabilities:'Estate capability IDs',xlCapabilities:'XL capability IDs',enabled:'Enable SMS delivery',endpoint:'SMS HTTPS endpoint',method:'HTTP request format',phoneField:'Phone parameter name',messageField:'Message parameter name',senderField:'Sender parameter name',sender:'Sender name',authHeader:'Authentication header',template:'OTP message template',registrationOtp:'Require SMS OTP at registration',newDeviceOtp:'Require SMS OTP on a new device',googleEnabled:'Enable Google sign-in',googleClientId:'Google OAuth client ID',appleEnabled:'Enable Apple sign-in',appleClientId:'Apple Services ID',appleTeamId:'Apple Team ID',appleKeyId:'Apple Key ID'};
export default function CustomerSettings({section}:{section:keyof typeof defaults}){
 const [lists,setLists]=useState<Record<string,string>>({});
 const [value,setValue]=useState<Values>(defaults[section]),[loaded,setLoaded]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[secrets,setSecrets]=useState<Record<string,string>>({}),[present,setPresent]=useState<Record<string,boolean>>({});
 useEffect(()=>{let active=true;fetch('/api/admin/customer-configuration',{cache:'no-store'}).then(async r=>{const data=await r.json() as {error?:string;bookings:Values;sms:Values;identity:Values;smsSecrets?:Record<string,boolean>;identitySecrets?:Record<string,boolean>};if(!r.ok)throw Error(data.error||'Unable to load settings');if(active){setValue(data[section]);setLists(Object.fromEntries(Object.entries(data[section]).filter(([,v])=>Array.isArray(v)).map(([k,v])=>[k,(v as number[]).join(',')])));setPresent(data[(section+'Secrets') as 'smsSecrets'|'identitySecrets']||{});setLoaded(true)}}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[section]);
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');setMessage('');try{const r=await fetch('/api/admin/customer-configuration',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({section,settings:{...value,...Object.fromEntries(Object.entries(lists).map(([k,v])=>[k,v.trim()?v.split(',').map(x=>Number(x.trim())):[]]))},secrets})}),data=await r.json() as {error?:string};if(!r.ok)throw Error(data.error||'Unable to save');setPresent(p=>({...p,...Object.fromEntries(Object.entries(secrets).filter(([,v])=>v).map(([k])=>[k,true]))}));setSecrets({});setMessage('Settings saved.')}catch(e){setError(e instanceof Error?e.message:'Unable to save')}finally{setBusy(false)}}
 const titles={bookings:'Booking rules',sms:'SMS gateway',identity:'Customer sign-in & verification'};
 return <section className="operations-settings"><h3>{titles[section]}</h3>{section==='bookings'&&<p>Rules apply to new quotes and their booking JSON. The card account is Web Booker Card / WBC (2155). Account customer ID maps to Autocab customerId; leave blank for non-account bookings. Card/Cash is saved locally and included in office notes; Autocab payment-specific fields require its payment API contract. Booking confirmation remains in test mode.</p>}{section==='sms'&&<p>Configure the provider endpoint and its parameter names. The message template must contain {'{code}'}. Enter the full header value, including Bearer if required. No SMS is sent by saving.</p>}{section==='identity'&&<p>Enable OTP after SMS is configured. A verified browser is trusted for 30 days; clearing its cookies triggers verification again. Email/password sign-in remains available.</p>}
 {error&&<p className="error-message" role="alert">{error}</p>}{message&&<p role="status">{message}</p>}<form onSubmit={save}><fieldset disabled={!loaded||busy}><div className="settings-grid">{Object.entries(value).map(([key,v])=><label key={key}>{labels[key]||key}{typeof v==='boolean'?<input type="checkbox" checked={v} onChange={e=>setValue({...value,[key]:e.target.checked})}/>:Array.isArray(v)?<Input value={lists[key]??v.join(',')} onChange={e=>setLists({...lists,[key]:e.target.value})}/>:key==='paymentMethod'||key==='method'?<select value={String(v)} onChange={e=>setValue({...value,[key]:e.target.value})}>{(key==='paymentMethod'?['card','cash']:['POST_JSON','POST_FORM','GET']).map(option=><option key={option}>{option}</option>)}</select>:(key==='accountCustomerId'||key==='cashAccountCustomerId')?<Input type="number" min={1} value={v===null?'':String(v)} onChange={e=>setValue({...value,[key]:e.target.value?Number(e.target.value):null})}/>:typeof v==='number'?<Input required type="number" min={key==='priorityDelayMinutes'?0:1} value={v} onChange={e=>setValue({...value,[key]:Number(e.target.value)})}/>:<Input value={String(v)} onChange={e=>setValue({...value,[key]:e.target.value})}/>}</label>)}
 {(section==='sms'?['token']:section==='identity'?['googleClientSecret','applePrivateKey']:[]).map(key=><label key={key}>{key} {present[key]?'(saved — leave blank to keep)':''}{key==='applePrivateKey'?<textarea rows={5} value={secrets[key]||''} autoComplete="off" onChange={e=>setSecrets({...secrets,[key]:e.target.value})}/>:<Input type="password" autoComplete="new-password" value={secrets[key]||''} onChange={e=>setSecrets({...secrets,[key]:e.target.value})}/>}</label>)}</div><Button type="submit">{busy?'Saving…':'Save settings'}</Button></fieldset></form>
 {section==='identity'&&<p>Provider return URLs:<br/><code>https://webapp.needacabplus.app/api/customer/auth/oauth/google/callback</code><br/><code>https://webapp.needacabplus.app/api/customer/auth/oauth/apple/callback</code></p>}</section>;
}
