'use client';
import {useEffect,useState} from 'react';
import {defaultBookingPolicy} from '@/lib/booking-policy';
import {smsPolicySchema,identityPolicySchema} from '@/lib/customer-security-policy';
import {Button} from '@/components/ui/button';
import BookingCapabilities from './booking-capabilities';
import BookingReferenceAudit from './booking-reference-audit';
import SmsTest from './sms-test';
import {Input} from '@/components/ui/input';
type Values=Record<string,string|number|boolean|number[]|null>;
const defaults={bookings:defaultBookingPolicy,sms:smsPolicySchema.parse({}),identity:identityPolicySchema.parse({})};
const labels:Record<string,string>={cashEnabled:'Enable cash',cardEnabled:'Enable card',liveBookingsEnabled:'Enable live bookings',accountName:'Card account name',cashAccountName:'Cash account name',bookingCapabilities:'Booking capability IDs',companyId:'Autocab company ID',accountCustomerId:'Card account ID (customerId)',cashAccountCustomerId:'Cash account customer ID (optional)',paymentMethod:'Payment method',priorityDelayMinutes:'Priority: add minutes to current time',minPrebookMinutes:'Guarantee Taxi: minimum advance notice (minutes)',enabled:'Enable SMS delivery',endpoint:'SMS HTTPS endpoint',method:'HTTP request format',phoneField:'Phone parameter name',messageField:'Message parameter name',senderField:'Sender parameter name',sender:'Sender name',authHeader:'Authentication header',template:'OTP message template',registrationOtp:'Require SMS OTP at registration',everyLoginOtp:'Require SMS OTP at every sign-in',newDeviceOtp:'Require SMS OTP on a new device',googleEnabled:'Enable Google sign-in',googleClientId:'Google OAuth client ID',appleEnabled:'Enable Apple sign-in',appleClientId:'Apple Services ID',appleTeamId:'Apple Team ID',appleKeyId:'Apple Key ID'};
export default function CustomerSettings({section}:{section:keyof typeof defaults}){
 const [attempts,setAttempts]=useState<{quote_id:string;state:string;external_booking_id:string|null;created_at:string}[]>([]);
 const [visibleIds,setVisibleIds]=useState<Record<string,boolean>>({});
 const [numberDrafts,setNumberDrafts]=useState<Record<string,string>>({});
 const [lists,setLists]=useState<Record<string,string>>({});
 const [value,setValue]=useState<Values>(defaults[section]),[loaded,setLoaded]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[secrets,setSecrets]=useState<Record<string,string>>({}),[present,setPresent]=useState<Record<string,boolean>>({});
 useEffect(()=>{let active=true;fetch('/api/admin/customer-configuration',{cache:'no-store'}).then(async r=>{const data=await r.json() as {liveBookingAttempts?:typeof attempts;error?:string;bookings:Values;sms:Values;identity:Values;smsSecrets?:Record<string,boolean>;identitySecrets?:Record<string,boolean>};if(!r.ok)throw Error(data.error||'Unable to load settings');if(active){setValue(data[section]);setAttempts(data.liveBookingAttempts||[]);setLists(Object.fromEntries(Object.entries(data[section]).filter(([,v])=>Array.isArray(v)).map(([k,v])=>[k,(v as number[]).join(',')])));setPresent(data[(section+'Secrets') as 'smsSecrets'|'identitySecrets']||{});setLoaded(true)}}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[section]);
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');setMessage('');try{for(const [key,draft] of Object.entries(numberDrafts)){if(!draft.trim()||!Number.isFinite(Number(draft)))throw new Error('Enter a valid value for '+(labels[key]||key)+'.')}const r=await fetch('/api/admin/customer-configuration',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({section,settings:{...value,...Object.fromEntries(Object.entries(numberDrafts).map(([key,draft])=>[key,Number(draft)])),...Object.fromEntries(Object.entries(lists).map(([k,v])=>[k,v.trim()?v.split(',').map(x=>Number(x.trim())):[]]))},secrets})}),data=await r.json() as {error?:string;settings?:Values;secretPresence?:Record<string,boolean>};if(!r.ok)throw Error(data.error||'Unable to save');setPresent(p=>({...p,...Object.fromEntries(Object.entries(secrets).filter(([,v])=>v).map(([k])=>[k,true]))}));if(data.settings){setValue(data.settings);setNumberDrafts({});}if(data.secretPresence)setPresent(data.secretPresence);setSecrets({});setMessage('Settings saved.')}catch(e){setError(e instanceof Error?e.message:'Unable to save')}finally{setBusy(false)}}

 const titles={bookings:'Bookings',sms:'SMS gateway',identity:'Customer sign-in & verification'};
 const update=(key:string,next:Values[string])=>{setValue(current=>({...current,[key]:next}));setError('');setMessage('')};
 const descriptions:Record<string,string>={cashEnabled:'Customers can choose cash and pay the driver.',cardEnabled:'Customers can choose card. Live card confirmation requires the payment integration.',liveBookingsEnabled:'Send confirmed cash bookings to Autocab. When off, bookings are test previews only.',registrationOtp:'Verify the customer’s mobile number when they create an account.',everyLoginOtp:'Ask for a fresh code at every sign-in, including trusted devices.',newDeviceOtp:'Ask for a code on an unfamiliar device. Verified devices are trusted for 30 days.',googleEnabled:'Let customers sign in with their Google account.',appleEnabled:'Let customers sign in with their Apple account.',enabled:'Allow the application to send verification messages.'};
 function field(key:string){const v=value[key];if(v===undefined)return null;const id=section+'-'+key;
  if(typeof v==='boolean')return <label className="customer-setting-toggle" key={key} htmlFor={id}><span><strong>{labels[key]||key}</strong><small>{descriptions[key]}</small></span><input id={id} type="checkbox" checked={v} onChange={e=>update(key,e.target.checked)}/></label>;
  if(key==='googleClientId'||key==='appleClientId')return <div className="customer-setting-field" key={key}><label htmlFor={id}>{labels[key]}</label><div className="customer-masked-field"><Input id={id} type={visibleIds[key]?'text':'password'} autoComplete="off" spellCheck={false} required={key==='googleClientId'&&Boolean(value.googleEnabled)} value={String(v)} onChange={e=>update(key,e.target.value)}/><button type="button" aria-controls={id} aria-label={(visibleIds[key]?'Hide ':'Show ')+labels[key]} aria-pressed={Boolean(visibleIds[key])} onClick={()=>setVisibleIds(current=>({...current,[key]:!current[key]}))}>{visibleIds[key]?'Hide':'Show'}</button></div></div>;
  return <label className="customer-setting-field" key={key} htmlFor={id}><span>{labels[key]||key}</span>{key==='template'?<textarea id={id} rows={4} maxLength={300} value={String(v)} onChange={e=>update(key,e.target.value)}/>:Array.isArray(v)?<Input id={id} value={lists[key]??v.join(',')} onChange={e=>{setLists({...lists,[key]:e.target.value});setError('')}}/>:key==='paymentMethod'||key==='method'?<select id={id} value={String(v)} onChange={e=>update(key,e.target.value)}>{(key==='paymentMethod'?['card','cash']:['POST_JSON','POST_FORM','GET']).map(option=><option key={option}>{option}</option>)}</select>:(key==='accountCustomerId'||key==='cashAccountCustomerId')?<Input id={id} type="number" min={1} value={v===null?'':String(v)} onChange={e=>update(key,e.target.value?Number(e.target.value):null)}/>:typeof v==='number'?<Input id={id} required type="number" step={1} min={key==='priorityDelayMinutes'?0:1} max={key==='priorityDelayMinutes'?180:key==='minPrebookMinutes'?10080:undefined} value={numberDrafts[key]??String(v)} onFocus={e=>e.target.select()} onChange={e=>{setNumberDrafts(current=>({...current,[key]:e.target.value}));setError('');setMessage('')}} onBlur={e=>{const draft=e.target.value;if(draft.trim()&&Number.isFinite(Number(draft)))setNumberDrafts(current=>({...current,[key]:String(Number(draft))}))}}/>:<Input id={id} required={key==='googleClientId'&&Boolean(value.googleEnabled)} value={String(v)} onChange={e=>update(key,e.target.value)}/>}</label>;
 }
 function secretField(key:string,title:string){const id=section+'-'+key;return <label className="customer-setting-field" htmlFor={id} key={key}><span className="customer-secret-title">{title}{present[key]&&<span className="customer-secret-saved">Saved securely</span>}</span>{key==='applePrivateKey'?<textarea id={id} placeholder={present[key]?'Saved — enter a new key only to replace it':'Enter private key'} rows={5} value={secrets[key]||''} autoComplete="off" onChange={e=>{setSecrets({...secrets,[key]:e.target.value});setError('')}}/>:<Input id={id} placeholder={present[key]?'Saved — enter a new key only to replace it':'Enter secret key'} type="password" required={key==='googleClientSecret'&&Boolean(value.googleEnabled)&&!present[key]} autoComplete="new-password" value={secrets[key]||''} onChange={e=>{setSecrets({...secrets,[key]:e.target.value});setError('')}}/>}<small>{present[key]?'Your key is stored. This empty field does not mean it was deleted. Leave it blank to keep the saved key.':'Stored securely; never shown after saving.'}</small></label>}
 function callback(provider:string){return <div className="customer-provider-callback"><span>Authorized redirect URI</span><code>https://webapp.needacabplus.app/api/customer/auth/oauth/{provider}/callback</code></div>}
 return <section className="operations-settings customer-settings"><header className="customer-settings-heading"><h3>{titles[section]}</h3><p>{section==='identity'?'Manage SMS verification and the ways customers can sign in. Email and password remain available.':section==='sms'?'Connect your SMS provider to deliver verification codes. Saving settings does not send a message.':'Configure accounts, vehicle requirements and pickup times for new bookings.'}</p></header>
 <form onSubmit={save}><fieldset disabled={!loaded||busy}>
 {section==='identity'?<><section className="customer-settings-group"><header><h4>SMS verification</h4><p>Configure SMS delivery before enabling verification.</p></header><div className="customer-toggle-list">{['registrationOtp','everyLoginOtp','newDeviceOtp'].map(field)}</div>{Boolean(value.everyLoginOtp)&&<p className="customer-settings-hint">Every sign-in is enabled, so verification also applies to trusted devices.</p>}</section><div className="customer-provider-grid"><section className="customer-settings-group"><header><h4>Google</h4><p>Use the credentials from Google Cloud.</p></header>{field('googleEnabled')}<div className="customer-provider-fields">{field('googleClientId')}{secretField('googleClientSecret','Google client secret')}</div>{callback('google')}</section><section className="customer-settings-group"><header><h4>Apple</h4><p>Use the credentials from Apple Developer.</p></header>{field('appleEnabled')}<div className="customer-provider-fields">{['appleClientId','appleTeamId','appleKeyId'].map(field)}{secretField('applePrivateKey','Apple private key')}</div>{callback('apple')}</section></div></>:<>
 {section==='sms'&&<div className="customer-settings-preset"><Button type="button" onClick={()=>{setValue({...value,endpoint:'https://orionconnect.co.uk/api/endpoint/webhook',method:'POST_JSON',phoneField:'customer_phone',messageField:'message',sender:'',template:'Your Need A Cab Plus verification code is {code}. It expires in {seconds} seconds.'});setError('')}}>Use Orion SMS settings</Button><p>Paste the complete signed webhook URL below. In Orion, use the SMS template {'{{message}}'}. Signed URL parameters are encrypted after saving.</p>{present.endpointQuery&&<p>Signed parameters are saved. Keep the endpoint unchanged to retain them.</p>}</div>}
 {section==='sms'&&field('enabled')}{section==='bookings'?<>
 <BookingReferenceAudit/>
 <section className="customer-settings-group"><header><h4>Webapp payments</h4><p>Enable cash, card or both. If both are off, new bookings are paused.</p></header><div className="customer-toggle-list">{['cashEnabled','cardEnabled','liveBookingsEnabled'].map(field)}</div>{!value.cashEnabled&&!value.cardEnabled&&<p role="status">Bookings paused: enable at least one payment method.</p>}{Boolean(value.liveBookingsEnabled)&&<p className="customer-settings-hint">Cash bookings will be sent to Autocab for dispatch. Live card bookings remain unavailable until payment processing is connected.</p>}</section><section className="customer-settings-group"><header><h4>Autocab accounts</h4><p>Use the account name as a label. The account ID is sent to Autocab as customerId. Leave the ID blank for a non-account booking.</p></header><div className="settings-grid customer-fields-grid">{['accountName','accountCustomerId','cashAccountName','cashAccountCustomerId','companyId'].map(field)}</div></section>
 <section className="customer-settings-group"><header><h4>Booking capabilities</h4><p>Choose from the enabled capabilities returned by Autocab. Only your selected capabilities are sent with each booking.</p></header><BookingCapabilities value={value.bookingCapabilities as number[]||[]} disabled={!loaded||busy} onChange={ids=>{update('bookingCapabilities',ids);setLists(current=>({...current,bookingCapabilities:ids.join(',')}))}}/></section>
 <section className="customer-settings-group"><header><h4>Pickup times</h4></header><div className="settings-grid customer-fields-grid">{['priorityDelayMinutes','minPrebookMinutes'].map(field)}</div></section>
 </>:<div className="settings-grid customer-fields-grid">{Object.keys(value).filter(key=>key!=='enabled'&&key!=='authHeader').map(field)}</div>}
 {section==='sms'&&<details className="customer-sms-advanced"><summary>Advanced authentication (optional)</summary><p>Orion uses the signature in your saved endpoint URL. Leave the header value blank unless your SMS provider specifically requires it.</p><div className="settings-grid customer-fields-grid">{field('authHeader')}{secretField('token','Authentication header value')}</div></details>}{section==='bookings'&&<p className="customer-settings-hint">Saved account IDs and capabilities apply to new quotes and their booking payloads. The live booking switch controls whether cash confirmations are sent to Autocab.</p>}</>}
 <footer className="customer-settings-actions"><Button type="submit">{busy?'Saving…':'Save settings'}</Button><span>Changes apply after saving.</span></footer></fieldset>
 {error&&<p className="error-message" role="alert">{error}</p>}{message&&<p className="customer-settings-success" role="status">{message}</p>}</form>{section==='bookings'&&attempts.length>0&&<details className="customer-sms-advanced"><summary>Recent live booking requests</summary><p>Unknown or sending requests need verification in Autocab before a new booking is made.</p>{attempts.map(attempt=><p key={attempt.quote_id}><strong>{attempt.state}</strong> · {attempt.external_booking_id?'Autocab #'+attempt.external_booking_id:'NAC-'+attempt.quote_id} · {new Date(attempt.created_at).toLocaleString()}</p>)}</details>}{section==='sms'&&<SmsTest/>}</section>;
}
