'use client';
import {useEffect,useState} from 'react';
import {defaultBookingPolicy} from '@/lib/booking-policy';
import {smsPolicySchema,identityPolicySchema} from '@/lib/customer-security-policy';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
type Values=Record<string,string|number|boolean|number[]|null>;
const defaults={bookings:defaultBookingPolicy,sms:smsPolicySchema.parse({}),identity:identityPolicySchema.parse({})};
const labels:Record<string,string>={companyId:'Autocab company ID',accountCustomerId:'Card account customer ID (Web Booker Card / WBC)',cashAccountCustomerId:'Cash account customer ID (optional)',paymentMethod:'Payment method',priorityDelayMinutes:'Priority: add minutes to current time',minPrebookMinutes:'Guarantee Taxi: minimum advance notice (minutes)',priorityCapabilities:'Priority capability IDs',guaranteeCapabilities:'Guarantee capability IDs',saloonCapabilities:'Saloon capability IDs',estateCapabilities:'Estate capability IDs',xlCapabilities:'XL capability IDs',enabled:'Enable SMS delivery',endpoint:'SMS HTTPS endpoint',method:'HTTP request format',phoneField:'Phone parameter name',messageField:'Message parameter name',senderField:'Sender parameter name',sender:'Sender name',authHeader:'Authentication header',template:'OTP message template',registrationOtp:'Require SMS OTP at registration',everyLoginOtp:'Require SMS OTP at every sign-in',newDeviceOtp:'Require SMS OTP on a new device',googleEnabled:'Enable Google sign-in',googleClientId:'Google OAuth client ID',appleEnabled:'Enable Apple sign-in',appleClientId:'Apple Services ID',appleTeamId:'Apple Team ID',appleKeyId:'Apple Key ID'};
export default function CustomerSettings({section}:{section:keyof typeof defaults}){
 const [visibleIds,setVisibleIds]=useState<Record<string,boolean>>({});
 const [lists,setLists]=useState<Record<string,string>>({});
 const [value,setValue]=useState<Values>(defaults[section]),[loaded,setLoaded]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[secrets,setSecrets]=useState<Record<string,string>>({}),[present,setPresent]=useState<Record<string,boolean>>({});
 useEffect(()=>{let active=true;fetch('/api/admin/customer-configuration',{cache:'no-store'}).then(async r=>{const data=await r.json() as {error?:string;bookings:Values;sms:Values;identity:Values;smsSecrets?:Record<string,boolean>;identitySecrets?:Record<string,boolean>};if(!r.ok)throw Error(data.error||'Unable to load settings');if(active){setValue(data[section]);setLists(Object.fromEntries(Object.entries(data[section]).filter(([,v])=>Array.isArray(v)).map(([k,v])=>[k,(v as number[]).join(',')])));setPresent(data[(section+'Secrets') as 'smsSecrets'|'identitySecrets']||{});setLoaded(true)}}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[section]);
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');setMessage('');try{const r=await fetch('/api/admin/customer-configuration',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({section,settings:{...value,...Object.fromEntries(Object.entries(lists).map(([k,v])=>[k,v.trim()?v.split(',').map(x=>Number(x.trim())):[]]))},secrets})}),data=await r.json() as {error?:string;settings?:Values;secretPresence?:Record<string,boolean>};if(!r.ok)throw Error(data.error||'Unable to save');setPresent(p=>({...p,...Object.fromEntries(Object.entries(secrets).filter(([,v])=>v).map(([k])=>[k,true]))}));if(data.settings)setValue(data.settings);if(data.secretPresence)setPresent(data.secretPresence);setSecrets({});setMessage('Settings saved.')}catch(e){setError(e instanceof Error?e.message:'Unable to save')}finally{setBusy(false)}}

 const titles={bookings:'Booking rules',sms:'SMS gateway',identity:'Customer sign-in & verification'};
 const update=(key:string,next:Values[string])=>{setValue(current=>({...current,[key]:next}));setError('');setMessage('')};
 const descriptions:Record<string,string>={registrationOtp:'Verify the customer’s mobile number when they create an account.',everyLoginOtp:'Ask for a fresh code at every sign-in, including trusted devices.',newDeviceOtp:'Ask for a code on an unfamiliar device. Verified devices are trusted for 30 days.',googleEnabled:'Let customers sign in with their Google account.',appleEnabled:'Let customers sign in with their Apple account.',enabled:'Allow the application to send verification messages.'};
 function field(key:string){const v=value[key];if(v===undefined)return null;const id=section+'-'+key;
  if(typeof v==='boolean')return <label className="customer-setting-toggle" key={key} htmlFor={id}><span><strong>{labels[key]||key}</strong><small>{descriptions[key]}</small></span><input id={id} type="checkbox" checked={v} onChange={e=>update(key,e.target.checked)}/></label>;
  if(key==='googleClientId'||key==='appleClientId')return <div className="customer-setting-field" key={key}><label htmlFor={id}>{labels[key]}</label><div className="customer-masked-field"><Input id={id} type={visibleIds[key]?'text':'password'} autoComplete="off" spellCheck={false} required={key==='googleClientId'&&Boolean(value.googleEnabled)} value={String(v)} onChange={e=>update(key,e.target.value)}/><button type="button" aria-controls={id} aria-label={(visibleIds[key]?'Hide ':'Show ')+labels[key]} aria-pressed={Boolean(visibleIds[key])} onClick={()=>setVisibleIds(current=>({...current,[key]:!current[key]}))}>{visibleIds[key]?'Hide':'Show'}</button></div></div>;
  return <label className="customer-setting-field" key={key} htmlFor={id}><span>{labels[key]||key}</span>{Array.isArray(v)?<Input id={id} value={lists[key]??v.join(',')} onChange={e=>{setLists({...lists,[key]:e.target.value});setError('')}}/>:key==='paymentMethod'||key==='method'?<select id={id} value={String(v)} onChange={e=>update(key,e.target.value)}>{(key==='paymentMethod'?['card','cash']:['POST_JSON','POST_FORM','GET']).map(option=><option key={option}>{option}</option>)}</select>:(key==='accountCustomerId'||key==='cashAccountCustomerId')?<Input id={id} type="number" min={1} value={v===null?'':String(v)} onChange={e=>update(key,e.target.value?Number(e.target.value):null)}/>:typeof v==='number'?<Input id={id} required type="number" min={key==='priorityDelayMinutes'?0:1} value={v} onChange={e=>update(key,Number(e.target.value))}/>:<Input id={id} required={key==='googleClientId'&&Boolean(value.googleEnabled)} value={String(v)} onChange={e=>update(key,e.target.value)}/>}</label>;
 }
 function secretField(key:string,title:string){const id=section+'-'+key;return <label className="customer-setting-field" htmlFor={id} key={key}><span className="customer-secret-title">{title}{present[key]&&<span className="customer-secret-saved">Saved securely</span>}</span>{key==='applePrivateKey'?<textarea id={id} placeholder={present[key]?'Saved — enter a new key only to replace it':'Enter private key'} rows={5} value={secrets[key]||''} autoComplete="off" onChange={e=>{setSecrets({...secrets,[key]:e.target.value});setError('')}}/>:<Input id={id} placeholder={present[key]?'Saved — enter a new key only to replace it':'Enter secret key'} type="password" required={key==='googleClientSecret'&&Boolean(value.googleEnabled)&&!present[key]} autoComplete="new-password" value={secrets[key]||''} onChange={e=>{setSecrets({...secrets,[key]:e.target.value});setError('')}}/>}<small>{present[key]?'Your key is stored. This empty field does not mean it was deleted. Leave it blank to keep the saved key.':'Stored securely; never shown after saving.'}</small></label>}
 function callback(provider:string){return <div className="customer-provider-callback"><span>Authorized redirect URI</span><code>https://webapp.needacabplus.app/api/customer/auth/oauth/{provider}/callback</code></div>}
 return <section className="operations-settings customer-settings"><header className="customer-settings-heading"><h3>{titles[section]}</h3><p>{section==='identity'?'Manage SMS verification and the ways customers can sign in. Email and password remain available.':section==='sms'?'Connect your SMS provider to deliver verification codes. Saving settings does not send a message.':'Configure accounts, vehicle requirements and pickup times for new bookings.'}</p></header>
 <form onSubmit={save}><fieldset disabled={!loaded||busy}>
 {section==='identity'?<><section className="customer-settings-group"><header><h4>SMS verification</h4><p>Configure SMS delivery before enabling verification.</p></header><div className="customer-toggle-list">{['registrationOtp','everyLoginOtp','newDeviceOtp'].map(field)}</div>{Boolean(value.everyLoginOtp)&&<p className="customer-settings-hint">Every sign-in is enabled, so verification also applies to trusted devices.</p>}</section><div className="customer-provider-grid"><section className="customer-settings-group"><header><h4>Google</h4><p>Use the credentials from Google Cloud.</p></header>{field('googleEnabled')}<div className="customer-provider-fields">{field('googleClientId')}{secretField('googleClientSecret','Google client secret')}</div>{callback('google')}</section><section className="customer-settings-group"><header><h4>Apple</h4><p>Use the credentials from Apple Developer.</p></header>{field('appleEnabled')}<div className="customer-provider-fields">{['appleClientId','appleTeamId','appleKeyId'].map(field)}{secretField('applePrivateKey','Apple private key')}</div>{callback('apple')}</section></div></>:<>
 {section==='sms'&&<div className="customer-settings-preset"><Button type="button" onClick={()=>{setValue({...value,endpoint:'https://orionconnect.co.uk/api/endpoint/webhook',method:'POST_JSON',phoneField:'customer_phone',messageField:'message',sender:'',template:'Your Need A Cab Plus verification code is {code}. It expires in 5 minutes.'});setError('')}}>Use Orion SMS settings</Button><p>Paste the complete signed webhook URL below. In Orion, use the SMS template {'{{message}}'}. Signed URL parameters are encrypted after saving.</p>{present.endpointQuery&&<p>Signed parameters are saved. Keep the endpoint unchanged to retain them.</p>}</div>}
 {section==='sms'&&field('enabled')}<div className="settings-grid customer-fields-grid">{Object.keys(value).filter(key=>key!=='enabled').map(field)}{section==='sms'&&secretField('token','Authentication header value')}</div>
 {section==='bookings'&&<p className="customer-settings-hint">Card account: Web Booker Card / WBC (2155). Leave an account ID blank for non-account bookings. Booking confirmation remains in test mode.</p>}</>}
 <footer className="customer-settings-actions"><Button type="submit">{busy?'Saving…':'Save settings'}</Button><span>Changes apply after saving.</span></footer></fieldset>
 {error&&<p className="error-message" role="alert">{error}</p>}{message&&<p className="customer-settings-success" role="status">{message}</p>}</form></section>;
}
