'use client';
import {useEffect,useState} from 'react';
import {CheckCircle2,Map,Search} from 'lucide-react';
import {defaultMapSettings,type MapSettings as MapSettingsValue} from '@/lib/map-settings-schema';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';

export default function MapSettings(){
 const [value,setValue]=useState<MapSettingsValue>(defaultMapSettings),[apiKey,setApiKey]=useState(''),[apiKeyConfigured,setApiKeyConfigured]=useState(false),[loaded,setLoaded]=useState(false),[busy,setBusy]=useState(false),[testing,setTesting]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
 useEffect(()=>{let active=true;fetch('/api/admin/map-settings',{cache:'no-store'}).then(async response=>{const data=await response.json() as {settings?:MapSettingsValue;apiKeyConfigured?:boolean;error?:string};if(!response.ok||!data.settings)throw new Error(data.error||'Unable to load map settings.');if(active){setValue(data.settings);setApiKeyConfigured(Boolean(data.apiKeyConfigured));setLoaded(true)}}).catch(reason=>{if(active)setError(reason instanceof Error?reason.message:'Unable to load map settings.')});return()=>{active=false}},[]);
 const update=<K extends keyof MapSettingsValue>(key:K,next:MapSettingsValue[K])=>{setValue(current=>({...current,[key]:next}));setError('');setMessage('')};
 async function save(event:React.FormEvent){event.preventDefault();setBusy(true);setError('');setMessage('');try{const response=await fetch('/api/admin/map-settings',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({settings:value,apiKey})}),data=await response.json() as {error?:string;apiKeyConfigured?:boolean};if(!response.ok)throw new Error(data.error||'Unable to save map settings.');setApiKey('');setApiKeyConfigured(Boolean(data.apiKeyConfigured));setMessage('Map settings saved. New webapp sessions will use them.')}catch(reason){setError(reason instanceof Error?reason.message:'Unable to save map settings.')}finally{setBusy(false)}}
 async function test(){setTesting(true);setError('');setMessage('');try{const response=await fetch('/api/admin/map-settings/test',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({apiKey,style:value.mapTilerLightStyle})}),data=await response.json() as {message?:string;error?:string};if(!response.ok)throw new Error(data.error||'MapTiler connection failed.');setMessage(data.message||'MapTiler connection is working.')}catch(reason){setError(reason instanceof Error?reason.message:'MapTiler connection failed.')}finally{setTesting(false)}}
 return <section className="operations-settings customer-settings map-settings-panel"><header className="customer-settings-heading"><h3>Maps & address search</h3><p>Choose the map customers see and the service used for address, place and GPS searches.</p></header><form onSubmit={save}><fieldset disabled={!loaded||busy}>
  <div className="customer-provider-grid">
   <section className="customer-settings-group"><header><span className="map-settings-icon"><Map/></span><div><h4>Map display</h4><p>Controls the basemap. Live cars, route guidance and pickup markers stay in our application.</p></div></header><label className="customer-setting-field"><span>Map provider</span><select value={value.mapProvider} onChange={event=>update('mapProvider',event.target.value as MapSettingsValue['mapProvider'])}><option value="openstreetmap">OpenStreetMap</option><option value="maptiler">MapTiler Cloud</option></select></label>{value.mapProvider==='maptiler'&&<div className="settings-grid customer-fields-grid"><label className="customer-setting-field"><span>Light map style</span><Input value={value.mapTilerLightStyle} onChange={event=>update('mapTilerLightStyle',event.target.value)}/><small>MapTiler style ID, for example streets-v4.</small></label><label className="customer-setting-field"><span>Dark map style</span><Input value={value.mapTilerDarkStyle} onChange={event=>update('mapTilerDarkStyle',event.target.value)}/><small>MapTiler style ID, for example dark.</small></label></div>}</section>
   <section className="customer-settings-group"><header><span className="map-settings-icon"><Search/></span><div><h4>Addresses & places</h4><p>Controls autocomplete, the fast GPS address preview and nearby named places.</p></div></header><label className="customer-setting-field"><span>Search provider</span><select value={value.searchProvider} onChange={event=>update('searchProvider',event.target.value as MapSettingsValue['searchProvider'])}><option value="openstreetmap">Current open map search</option><option value="maptiler">MapTiler Geocoding</option></select></label><div className="settings-grid customer-fields-grid"><label className="customer-setting-field"><span>Country</span><Input maxLength={2} value={value.country} onChange={event=>update('country',event.target.value.toLowerCase())}/></label><label className="customer-setting-field"><span>Language</span><Input maxLength={2} value={value.language} onChange={event=>update('language',event.target.value.toLowerCase())}/></label><label className="customer-setting-field"><span>Nearby place radius (metres)</span><Input type="number" min={10} max={250} value={value.nearbyPlaceRadiusMetres} onChange={event=>update('nearbyPlaceRadiusMetres',Number(event.target.value))}/></label></div></section>
  </div>
  <section className="customer-settings-group maptiler-key-group"><header><h4>MapTiler Cloud key</h4><p>The key is encrypted at rest. Map rendering exposes it to the browser as required by MapTiler, so keep Allowed HTTP Origins enabled in MapTiler Cloud.</p></header><label className="customer-setting-field"><span className="customer-secret-title">API key{apiKeyConfigured&&<span className="customer-secret-saved"><CheckCircle2/>Saved securely</span>}</span><Input type="password" autoComplete="new-password" placeholder={apiKeyConfigured?'Saved — enter a new key only to replace it':'Paste the MapTiler API key'} value={apiKey} onChange={event=>{setApiKey(event.target.value);setError('');setMessage('')}}/><small>Leave blank to retain the saved key. The key is never returned by the admin API.</small></label><div className="customer-settings-actions"><Button type="button" variant="outline" disabled={testing||(!apiKeyConfigured&&!apiKey.trim())} onClick={test}>{testing?'Testing…':'Test MapTiler connection'}</Button><span>Tests both the selected map style and a Plymouth address search.</span></div></section>
  <p className="customer-settings-hint">Autocab still validates the selected address and booking zone before quotes or bookings are created. Changing the map provider does not change fares.</p>
  <footer className="customer-settings-actions"><Button type="submit">{busy?'Saving…':'Save map settings'}</Button><span>Provider changes apply after saving and refreshing the webapp.</span></footer>
 </fieldset>{error&&<p className="error-message" role="alert">{error}</p>}{message&&<p className="customer-settings-success" role="status">{message}</p>}</form></section>;
}
