'use client';
import {BadgePercent,Gift,Sparkles,UserRoundCheck,UserRoundX} from 'lucide-react';
import type {QuotePolicy} from '@/lib/quote-policy';
import {Input} from '@/components/ui/input';

function Switch({checked,onChange,label}:{checked:boolean;onChange:(value:boolean)=>void;label:string}){return <button type="button" className={`settings-toggle ${checked?'on':''}`} role="switch" aria-checked={checked} aria-label={label} onClick={()=>onChange(!checked)}><span/></button>}
const rewardOptions=<><option value="percentage">Fare discount (%)</option><option value="fixed">Fixed credit (£)</option><option value="points">Loyalty points</option></>;

export default function MarketingSettings({value,onChange}:{value:QuotePolicy;onChange:(next:QuotePolicy)=>void}){
 const promotions=value.promotions;
 const updateRetention=(change:Partial<typeof promotions.retention>)=>onChange({...value,promotions:{...promotions,retention:{...promotions.retention,...change}}});
 const updateReengagement=(change:Partial<typeof promotions.reengagement>)=>onChange({...value,promotions:{...promotions,reengagement:{...promotions.reengagement,...change}}});
 return <div className="membership-settings marketing-settings">
  <section className="membership-intro marketing-intro"><div><span><Sparkles/></span><div><h4>Marketing & customer growth</h4><p>Configure loyalty, retention, re-engagement and promotion guardrails from one place. Nothing is sent until its feature is enabled.</p></div></div><label><span>{promotions.enabled?'Enabled':'Disabled'}</span><Switch checked={promotions.enabled} onChange={enabled=>onChange({...value,promotions:{...promotions,enabled}})} label="Enable marketing promotions"/></label></section>
  <section className="growth-rule-card"><header><span><Gift/></span><div><h4>Loyalty programme</h4><p>Reward completed journeys and distance. Loyalty remains separate from paid membership.</p></div><Switch checked={value.loyalty.enabled} onChange={enabled=>onChange({...value,loyalty:{...value.loyalty,enabled}})} label="Enable loyalty points"/></header><div className="settings-grid">{([['pointsPerCompletedRide','Points per completed ride',1],['pointsPerMile','Points per mile',0.1],['pencePerPoint','Value of one point (pence)',1],['minimumRedemptionPoints','Minimum points to redeem',1],['maximumFareDiscountPercent','Maximum fare discount',0.1],['pointsExpireMonths','Points expire after (months)',1]] as const).map(([field,label,step])=><label key={field}>{label}<Input type="number" min={field==='pencePerPoint'||field==='minimumRedemptionPoints'||field==='pointsExpireMonths'?1:0} step={step} value={value.loyalty[field]} onChange={event=>onChange({...value,loyalty:{...value.loyalty,[field]:Number(event.target.value)}})}/></label>)}</div></section>
  <div className="marketing-strategy-grid">
   <section className="growth-rule-card"><header><span><UserRoundCheck/></span><div><h4>Customer retention</h4><p>Reward active customers after they complete enough journeys inside the selected period.</p></div><Switch checked={promotions.retention.enabled} onChange={enabled=>updateRetention({enabled})} label="Enable customer retention"/></header><div className="settings-grid"><label>Minimum completed rides<Input type="number" min="1" max="1000" step="1" value={promotions.retention.minimumCompletedRides} onChange={event=>updateRetention({minimumCompletedRides:Number(event.target.value)})}/></label><label>Measured over<div className="input-with-unit"><Input type="number" min="1" max="3650" step="1" value={promotions.retention.lookbackDays} onChange={event=>updateRetention({lookbackDays:Number(event.target.value)})}/><span>days</span></div></label><label>Reward type<select value={promotions.retention.rewardType} onChange={event=>updateRetention({rewardType:event.target.value as typeof promotions.retention.rewardType})}>{rewardOptions}</select></label><label>Reward value<Input type="number" min="0" max="100000" step={promotions.retention.rewardType==='points'?1:.01} value={promotions.retention.rewardValue} onChange={event=>updateRetention({rewardValue:Number(event.target.value)})}/></label><label>Reward validity<div className="input-with-unit"><Input type="number" min="1" max="365" step="1" value={promotions.retention.validityDays} onChange={event=>updateRetention({validityDays:Number(event.target.value)})}/><span>days</span></div></label></div></section>
   <section className="growth-rule-card"><header><span><UserRoundX/></span><div><h4>Customer re-engagement</h4><p>Bring inactive customers back with a time-limited personalised reward.</p></div><Switch checked={promotions.reengagement.enabled} onChange={enabled=>updateReengagement({enabled})} label="Enable customer re-engagement"/></header><div className="settings-grid"><label>Customer inactive for<div className="input-with-unit"><Input type="number" min="1" max="3650" step="1" value={promotions.reengagement.inactiveDays} onChange={event=>updateReengagement({inactiveDays:Number(event.target.value)})}/><span>days</span></div></label><label>Reward type<select value={promotions.reengagement.rewardType} onChange={event=>updateReengagement({rewardType:event.target.value as typeof promotions.reengagement.rewardType})}>{rewardOptions}</select></label><label>Reward value<Input type="number" min="0" max="100000" step={promotions.reengagement.rewardType==='points'?1:.01} value={promotions.reengagement.rewardValue} onChange={event=>updateReengagement({rewardValue:Number(event.target.value)})}/></label><label>Offer validity<div className="input-with-unit"><Input type="number" min="1" max="365" step="1" value={promotions.reengagement.validityDays} onChange={event=>updateReengagement({validityDays:Number(event.target.value)})}/><span>days</span></div></label></div></section>
  </div>
  <section className="growth-rule-card"><header><span><Sparkles/></span><div><h4>Promotion & AI guardrails</h4><p>Control stacking and the maximum discount. AI-created campaigns always start as drafts.</p></div></header><div className="promotion-guardrails"><label><input type="checkbox" checked={promotions.allowWithMembership} onChange={event=>onChange({...value,promotions:{...promotions,allowWithMembership:event.target.checked}})}/>Allow promotions with membership fares</label><label><input type="checkbox" checked={promotions.allowWithLoyalty} onChange={event=>onChange({...value,promotions:{...promotions,allowWithLoyalty:event.target.checked}})}/>Allow promotions with loyalty redemption</label><label><input type="checkbox" checked={promotions.aiDraftsEnabled} onChange={event=>onChange({...value,promotions:{...promotions,aiDraftsEnabled:event.target.checked}})}/>Allow the AI agent to propose campaign drafts</label><label>Maximum promotion discount<div className="input-with-unit"><Input type="number" min="0" max="100" step="0.1" value={promotions.maximumFareDiscountPercent} onChange={event=>onChange({...value,promotions:{...promotions,maximumFareDiscountPercent:Number(event.target.value)}})}/><span>%</span></div></label></div><p className="campaign-safety"><BadgePercent/>Manual approval remains mandatory. The AI agent cannot publish a campaign by itself.</p></section>
 </div>
}
