'use client';
import {BadgePercent,Crown,Gift,Sparkles} from 'lucide-react';
import {membershipTierIds,type MembershipTierId,type QuotePolicy} from '@/lib/quote-policy';
import {Input} from '@/components/ui/input';

function Switch({checked,onChange,label}:{checked:boolean;onChange:(value:boolean)=>void;label:string}){return <button type="button" className={`settings-toggle ${checked?'on':''}`} role="switch" aria-checked={checked} aria-label={label} onClick={()=>onChange(!checked)}><span/></button>}
const addonFields=[['priorityAddonPercent','Priority'],['prebookAddonPercent','Pre-book'],['guaranteeAddonPercent','Guarantee']] as const;

export default function MembershipSettings({value,onChange}:{value:QuotePolicy;onChange:(next:QuotePolicy)=>void}){
 const membership=value.membership;
 function updateTier(id:MembershipTierId,change:Partial<(typeof membership.tiers)[MembershipTierId]>){onChange({...value,membership:{...membership,tiers:{...membership.tiers,[id]:{...membership.tiers[id],...change}}}})}
 return <div className="membership-settings">
  <section className="membership-intro"><div><span><Crown/></span><div><h4>Paid membership fares</h4><p>Members pay the configured final service addon. Non-members keep the standard service fare and can still receive quiet-time Smart Fare.</p></div></div><label><span>{membership.enabled?'Enabled':'Disabled'}</span><Switch checked={membership.enabled} onChange={enabled=>onChange({...value,membership:{...membership,enabled}})} label="Enable membership fares"/></label></section>
  <div className="membership-billing"><label>Billing interval<select value={membership.billingInterval} onChange={event=>onChange({...value,membership:{...membership,billingInterval:event.target.value as 'month'|'year'}})}><option value="month">Monthly</option><option value="year">Yearly</option></select></label><p>An active paid subscription assigns one tier. Prices below define the plan catalogue; Stripe checkout will use the active catalogue.</p></div>
  <div className="membership-tier-grid">{membershipTierIds.map(id=>{const tier=membership.tiers[id];return <article key={id} className={`membership-tier-card tier-${id}`}><header><div><span className="membership-tier-icon"><Crown/></span><Input aria-label={`${tier.name} name`} value={tier.name} onChange={event=>updateTier(id,{name:event.target.value})}/></div><Switch checked={tier.enabled} onChange={enabled=>updateTier(id,{enabled})} label={`Enable ${tier.name}`}/></header><label>Subscription price<div className="input-with-unit"><span>£</span><Input type="number" min="0" max="1000" step="0.01" value={tier.monthlyPrice} onChange={event=>updateTier(id,{monthlyPrice:Number(event.target.value)})}/><span>/{membership.billingInterval==='month'?'mo':'yr'}</span></div></label><div className="membership-addons">{addonFields.map(([field,label])=><label key={field}>{label} final addon<div className="input-with-unit"><Input type="number" min="0" max="100" step="0.1" placeholder="Standard" value={tier[field]??''} onChange={event=>updateTier(id,{[field]:event.target.value===''?null:Number(event.target.value)})}/><span>%</span></div></label>)}</div><small>Blank keeps the normal service addon. 0% charges only the Autocab fare.</small></article>})}</div>
  <section className="growth-rule-card"><header><span><Gift/></span><div><h4>Loyalty points</h4><p>Separate from paid membership. Points can reward completed journeys and travelled distance.</p></div><Switch checked={value.loyalty.enabled} onChange={enabled=>onChange({...value,loyalty:{...value.loyalty,enabled}})} label="Enable loyalty points"/></header><div className="settings-grid">{([['pointsPerCompletedRide','Points per completed ride',1],['pointsPerMile','Points per mile',0.1],['pencePerPoint','Value of one point (pence)',1],['minimumRedemptionPoints','Minimum points to redeem',1],['maximumFareDiscountPercent','Maximum fare discount',0.1],['pointsExpireMonths','Points expire after (months)',1]] as const).map(([field,label,step])=><label key={field}>{label}<Input type="number" min={field==='pencePerPoint'||field==='minimumRedemptionPoints'||field==='pointsExpireMonths'?1:0} step={step} value={value.loyalty[field]} onChange={event=>onChange({...value,loyalty:{...value.loyalty,[field]:Number(event.target.value)}})}/></label>)}</div></section>
  <section className="growth-rule-card"><header><span><Sparkles/></span><div><h4>Promotions & AI campaigns</h4><p>Campaigns may target precise customer segments. AI-created campaigns always start as drafts.</p></div><Switch checked={value.promotions.enabled} onChange={enabled=>onChange({...value,promotions:{...value.promotions,enabled}})} label="Enable promotions"/></header><div className="promotion-guardrails"><label><input type="checkbox" checked={value.promotions.allowWithMembership} onChange={event=>onChange({...value,promotions:{...value.promotions,allowWithMembership:event.target.checked}})}/>Allow promotions with membership fares</label><label><input type="checkbox" checked={value.promotions.allowWithLoyalty} onChange={event=>onChange({...value,promotions:{...value.promotions,allowWithLoyalty:event.target.checked}})}/>Allow promotions with loyalty redemption</label><label><input type="checkbox" checked={value.promotions.aiDraftsEnabled} onChange={event=>onChange({...value,promotions:{...value.promotions,aiDraftsEnabled:event.target.checked}})}/>Allow the AI agent to propose campaign drafts</label><label>Maximum promotion discount<div className="input-with-unit"><Input type="number" min="0" max="100" step="0.1" value={value.promotions.maximumFareDiscountPercent} onChange={event=>onChange({...value,promotions:{...value.promotions,maximumFareDiscountPercent:Number(event.target.value)}})}/><span>%</span></div></label></div><p className="campaign-safety"><BadgePercent/>Manual approval is mandatory. The AI agent cannot activate or publish a campaign by itself.</p></section>
 </div>
}
