'use client';
import {useEffect,useState} from 'react';
import {Gauge,ReceiptText,Sparkles} from 'lucide-react';
import {defaultQuotePolicy,type QuotePolicy} from '@/lib/quote-policy';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import HelpTip from './help-tip';

const tips={
 base:'Autocab calculates the passenger fare first. The selected Priority or Guarantee addition is then added to that fare.',
 priority:'Used for ASAP bookings. Choose either a percentage controlled by demand levels or one fixed amount.',
 guarantee:'Used for prebookings. Choose either one percentage or one fixed amount.',
 demand:'The assistant compares unassigned bookings due soon with vehicles currently marked CLEAR. It selects the Low, Medium or High Priority percentage.',
 validity:'How long the displayed quote can be confirmed before the app asks Autocab for a fresh price.',
 thresholds:'The ratio is waiting bookings divided by CLEAR vehicles. At or above a threshold, the corresponding demand level is selected.',
 window:'Only unassigned bookings due inside this time window are counted by the demand assistant.',
 fallback:'This level is used in manual mode and whenever the live vehicle feed is older than two minutes.',
 response:'The field and unit used to read the passenger fare from the Autocab quote response.',
};

function LabelText({children,tip}:{children:React.ReactNode;tip:string}){return <span className="field-label">{children}<HelpTip text={tip}/></span>}

export default function QuoteSettings({embedded=false}:{embedded?:boolean}){
 const [value,setValue]=useState(defaultQuotePolicy),[loaded,setLoaded]=useState(false),[busy,setBusy]=useState(true),[error,setError]=useState(''),[message,setMessage]=useState(''),[snapshot,setSnapshot]=useState('');
 useEffect(()=>{let active=true;fetch('/api/admin/quote-settings',{cache:'no-store'}).then(async r=>{const data=await r.json() as {policy:QuotePolicy;demand:{mode:string;waiting:number;clear:number};error?:string};if(!r.ok)throw new Error(data.error);if(active){setValue(data.policy);setLoaded(true);setSnapshot(data.demand.mode==='automatic'?`${data.demand.waiting} waiting bookings / ${data.demand.clear} CLEAR vehicles`:data.demand.mode==='manual-fallback'?'Vehicle feed is stale. Manual demand level is used.':'Manual demand level')}}).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setBusy(false)});return()=>{active=false}},[]);
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');setMessage('');try{const r=await fetch('/api/admin/quote-settings',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(value)}),data=await r.json() as {error?:string};if(!r.ok)throw new Error(data.error);setMessage('Live fare settings saved. New quotes will use these values.')}catch(e){setError(e instanceof Error?e.message:'Unable to save')}finally{setBusy(false)}}
 const priorityPercentage=value.priorityUpliftMode==='percentage',guaranteePercentage=value.guaranteeUpliftMode==='percentage';
 const content=<>
  <header className="pricing-section-heading"><span><ReceiptText/></span><div><h4>Live webapp fares</h4><p>Autocab supplies the base fare. Priority is for ASAP journeys; Guarantee is for prebookings.</p></div><HelpTip text={tips.base}/></header>
  {error&&<p className="error-message" role="alert">{error}</p>}{message&&<p className="saved-message" role="status">{message}</p>}
  <form className="operations-form" onSubmit={save}><fieldset disabled={busy||!loaded}>
   <div className="pricing-topline"><label className="pricing-enable"><input type="checkbox" checked={value.enabled} onChange={e=>setValue({...value,enabled:e.target.checked})}/><span><strong>Enable real Autocab quotes</strong><small>Use live Autocab fares in the customer booking app.</small></span></label><label><LabelText tip={tips.validity}>Quote valid for</LabelText><div className="input-with-unit"><Input type="number" required min="60" max="600" step="1" value={value.quoteValiditySeconds} onChange={e=>setValue({...value,quoteValiditySeconds:Number(e.target.value)})}/><span>seconds</span></div></label></div>
   <div className="service-price-grid">
    <section className="service-price-card"><div className="service-price-title"><div><span className="pricing-chip">ASAP</span><h5>Priority booking</h5></div><HelpTip text={tips.priority}/></div><label><span className="field-label">Addition type</span><select value={value.priorityUpliftMode} onChange={e=>setValue({...value,priorityUpliftMode:e.target.value as QuotePolicy['priorityUpliftMode']})}><option value="percentage">Percentage (%)</option><option value="fixed">Fixed amount (£)</option></select></label>{priorityPercentage?<p className="pricing-selection-note"><Sparkles/>The Demand assistant chooses the active percentage below.</p>:<label><span className="field-label">Amount added to Autocab fare</span><div className="input-with-unit"><span>£</span><Input type="number" min="0" max="1000" step="0.01" value={value.priorityFixedAmount} onChange={e=>setValue({...value,priorityFixedAmount:Number(e.target.value)})}/></div></label>}</section>
    <section className="service-price-card"><div className="service-price-title"><div><span className="pricing-chip">PREBOOK</span><h5>Guarantee Taxi</h5></div><HelpTip text={tips.guarantee}/></div><label><span className="field-label">Addition type</span><select value={value.guaranteeUpliftMode} onChange={e=>setValue({...value,guaranteeUpliftMode:e.target.value as QuotePolicy['guaranteeUpliftMode']})}><option value="percentage">Percentage (%)</option><option value="fixed">Fixed amount (£)</option></select></label>{guaranteePercentage?<label><span className="field-label">Percentage added to Autocab fare</span><div className="input-with-unit"><Input type="number" min="0" max="100" step="0.1" value={value.guaranteePercent} onChange={e=>setValue({...value,guaranteePercent:Number(e.target.value)})}/><span>%</span></div></label>:<label><span className="field-label">Amount added to Autocab fare</span><div className="input-with-unit"><span>£</span><Input type="number" min="0" max="1000" step="0.01" value={value.guaranteeFixedAmount} onChange={e=>setValue({...value,guaranteeFixedAmount:Number(e.target.value)})}/></div></label>}</section>
   </div>
   {priorityPercentage&&<section className="demand-assistant"><header><div className="demand-icon"><Sparkles/></div><div><span className="pricing-chip">SMART HELPER</span><h5>Demand assistant</h5><p>Automatically selects the Priority percentage from current demand. It never changes the Guarantee fare.</p></div><HelpTip text={tips.demand}/></header><div className="settings-grid"><label><span className="field-label">Assistant mode</span><select value={value.demandMode} onChange={e=>setValue({...value,demandMode:e.target.value as QuotePolicy['demandMode']})}><option value="automatic">Automatic from live demand</option><option value="manual">Manual demand level</option></select></label><label><LabelText tip={tips.fallback}>Manual level / fallback</LabelText><select value={value.manualDemand} onChange={e=>setValue({...value,manualDemand:e.target.value as QuotePolicy['manualDemand']})}><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option></select></label></div><div className="demand-levels">{(['low','medium','high'] as const).map(level=><label key={level}><span>{level[0].toUpperCase()+level.slice(1)} demand</span><div className="input-with-unit"><Input type="number" min="0" max="100" step="0.1" value={value[`${level}Percent`]} onChange={e=>setValue({...value,[`${level}Percent`]:Number(e.target.value)})}/><span>%</span></div></label>)}</div>{value.demandMode==='automatic'&&<div className="settings-grid demand-thresholds"><label><LabelText tip={tips.thresholds}>Medium threshold</LabelText><Input type="number" min="0.01" max="100" step="0.01" value={value.mediumRatio} onChange={e=>setValue({...value,mediumRatio:Number(e.target.value)})}/></label><label><LabelText tip={tips.thresholds}>High threshold</LabelText><Input type="number" min="0.01" max="100" step="0.01" value={value.highRatio} onChange={e=>setValue({...value,highRatio:Number(e.target.value)})}/></label><label><LabelText tip={tips.window}>Booking window</LabelText><div className="input-with-unit"><span>±</span><Input type="number" min="1" max="120" step="1" value={value.demandWindowMinutes} onChange={e=>setValue({...value,demandWindowMinutes:Number(e.target.value)})}/><span>min</span></div></label></div>}<div className="demand-status"><Gauge/><span><strong>Current signal:</strong> {snapshot || 'Loading live demand…'}</span></div></section>}
   <details className="pricing-advanced"><summary>Advanced Autocab response settings <HelpTip text={tips.response}/></summary><div className="settings-grid"><label><span className="field-label">Fare field in quote response</span><Input required value={value.pricePath} onChange={e=>setValue({...value,pricePath:e.target.value})}/><small>Expected value: outward.price</small></label><label><span className="field-label">Fare unit</span><select value={value.priceUnit} onChange={e=>setValue({...value,priceUnit:e.target.value as QuotePolicy['priceUnit']})}><option value="gbp">Pounds (£)</option><option value="pence">Pence</option></select></label></div></details>
   <div className="pricing-save-row"><Button disabled={busy} type="submit">{busy?'Saving…':'Save live fare settings'}</Button><span>Percentage and fixed amount are never combined for the same service.</span></div>
  </fieldset></form>
 </>;
 return embedded?<section className="pricing-workspace-section">{content}</section>:<section className="operations-settings pricing-workspace-section">{content}</section>;
}
