'use client';
import {useEffect,useState} from 'react';
import {Gauge,ReceiptText,Sparkles} from 'lucide-react';
import {defaultQuotePolicy,type QuotePolicy} from '@/lib/quote-policy';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import HelpTip from './help-tip';
import CapabilityQuoteTest from './capability-quote-test';
import SmartFareSettings from './smart-fare-settings';

const tips={
 base:'Autocab calculates the passenger fare first. The selected Priority or Guarantee addition is then added to that fare.',
 priority:'Used for ASAP bookings. Choose either a percentage controlled by demand levels or one fixed amount.',
 guarantee:'Used for prebookings. Choose either one percentage or one fixed amount.',
 demand:'The assistant compares unassigned bookings due soon with vehicles currently marked CLEAR. Demand is active only when bookings are greater than CLEAR vehicles.',
 validity:'How long the displayed quote can be confirmed before the app asks Autocab for a fresh price.',
 window:'Only unassigned bookings due inside this time window are counted by the demand assistant.',
 response:'The field and unit used to read the passenger fare from the Autocab quote response.',
};
const days=['Sun','Mon','Tue','Wed','Thu','Fri','Sat'];

function LabelText({children,tip}:{children:React.ReactNode;tip:string}){return <span className="field-label">{children}<HelpTip text={tip}/></span>}
function Switch({checked,onChange,label}:{checked:boolean;onChange:(checked:boolean)=>void;label:string}){return <button type="button" className={`settings-toggle ${checked?'on':''}`} role="switch" aria-checked={checked} aria-label={label} onClick={()=>onChange(!checked)}><span/></button>}

export default function QuoteSettings({embedded=false}:{embedded?:boolean}){
 const [value,setValue]=useState(defaultQuotePolicy),[loaded,setLoaded]=useState(false),[busy,setBusy]=useState(true),[error,setError]=useState(''),[message,setMessage]=useState(''),[snapshot,setSnapshot]=useState('');
 useEffect(()=>{let active=true;fetch('/api/admin/quote-settings',{cache:'no-store'}).then(async r=>{const data=await r.json() as {policy:QuotePolicy;demand:{mode:string;waiting:number|null;clear:number|null};error?:string};if(!r.ok)throw new Error(data.error);if(active){setValue(data.policy);setLoaded(true);setSnapshot(data.demand.mode==='automatic'?`${data.demand.waiting} waiting bookings / ${data.demand.clear} CLEAR vehicles`:data.demand.mode==='manual-fallback'?'Vehicle feed is stale — base percentage is used.':data.demand.mode==='scheduled-off'?'Outside the configured days or hours.':data.demand.mode==='disabled'?'Dynamic pricing is off.':'Base percentage is used.')}}).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setBusy(false)});return()=>{active=false}},[]);
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');setMessage('');try{const r=await fetch('/api/admin/quote-settings',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(value)}),data=await r.json() as {error?:string};if(!r.ok)throw new Error(data.error);setMessage('Live fare settings saved. New quotes will use these values.')}catch(e){setError(e instanceof Error?e.message:'Unable to save')}finally{setBusy(false)}}
 const priorityPercentage=value.priorityUpliftMode==='percentage',guaranteePercentage=value.guaranteeUpliftMode==='percentage';
 const content=<>
  <header className="pricing-section-heading"><span><ReceiptText/></span><div><h4>Live webapp fares</h4><p>NOW offers normal or Smart Fares. Priority and Guarantee add their configured service charge to the Autocab fare.</p></div><HelpTip text={tips.base}/></header>
  {error&&<p className="error-message" role="alert">{error}</p>}{message&&<p className="saved-message" role="status">{message}</p>}
  <form className="operations-form" onSubmit={save}><fieldset disabled={busy||!loaded}>
   <SmartFareSettings value={value} onChange={setValue} disabled={busy||!loaded}/>
   <div className="pricing-topline"><label className="pricing-enable"><input type="checkbox" checked={value.enabled} onChange={e=>setValue({...value,enabled:e.target.checked})}/><span><strong>Enable real Autocab quotes</strong><small>Use live Autocab fares in the customer booking app.</small></span></label><label><LabelText tip={tips.validity}>Quote valid for</LabelText><div className="input-with-unit"><Input type="number" required min="60" max="600" step="1" value={value.quoteValiditySeconds} onChange={e=>setValue({...value,quoteValiditySeconds:Number(e.target.value)})}/><span>seconds</span></div></label></div>
   <div className="service-price-grid">
    <section className="service-price-card"><div className="service-price-title"><div><span className="pricing-chip">ASAP</span><h5>Priority booking</h5></div><HelpTip text={tips.priority}/></div><label><span className="field-label">Addition type</span><select value={value.priorityUpliftMode} onChange={e=>setValue({...value,priorityUpliftMode:e.target.value as QuotePolicy['priorityUpliftMode']})}><option value="percentage">Percentage (%)</option><option value="fixed">Fixed amount (£)</option></select></label>{priorityPercentage?<><label><span className="field-label">Base percentage added to Autocab fare<HelpTip text="This percentage is used when dynamic pricing is off or when there are enough CLEAR vehicles for the waiting bookings."/></span><div className="input-with-unit"><Input type="number" min="0" max="100" step="0.1" value={value.lowPercent} onChange={e=>setValue({...value,lowPercent:Number(e.target.value)})}/><span>%</span></div></label><p className="pricing-selection-note"><Sparkles/>Dynamic pricing can replace this with the demand percentage when bookings exceed CLEAR cars.</p></>:<label><span className="field-label">Amount added to Autocab fare</span><div className="input-with-unit"><span>£</span><Input type="number" min="0" max="1000" step="0.01" value={value.priorityFixedAmount} onChange={e=>setValue({...value,priorityFixedAmount:Number(e.target.value)})}/></div></label>}</section>
    <section className="service-price-card"><div className="service-price-title"><div><span className="pricing-chip">PREBOOK</span><h5>Guarantee Taxi</h5></div><HelpTip text={tips.guarantee}/></div><label><span className="field-label">Addition type</span><select value={value.guaranteeUpliftMode} onChange={e=>setValue({...value,guaranteeUpliftMode:e.target.value as QuotePolicy['guaranteeUpliftMode']})}><option value="percentage">Percentage (%)</option><option value="fixed">Fixed amount (£)</option></select></label>{guaranteePercentage?<label><span className="field-label">Percentage added to Autocab fare</span><div className="input-with-unit"><Input type="number" min="0" max="100" step="0.1" value={value.guaranteePercent} onChange={e=>setValue({...value,guaranteePercent:Number(e.target.value)})}/><span>%</span></div></label>:<label><span className="field-label">Amount added to Autocab fare</span><div className="input-with-unit"><span>£</span><Input type="number" min="0" max="1000" step="0.01" value={value.guaranteeFixedAmount} onChange={e=>setValue({...value,guaranteeFixedAmount:Number(e.target.value)})}/></div></label>}</section>
   </div>
   {priorityPercentage&&<section className="demand-assistant"><header><div className="demand-icon"><Sparkles/></div><div><span className="pricing-chip">SMART HELPER</span><h5>Demand & dynamic pricing</h5><p>Uses the demand percentage only when waiting bookings are greater than CLEAR vehicles.</p></div><div className="demand-heading-actions"><span>{value.dynamicPricingEnabled?'On':'Off'}</span><Switch checked={value.dynamicPricingEnabled} onChange={dynamicPricingEnabled=>setValue({...value,dynamicPricingEnabled})} label="Enable dynamic demand pricing"/><HelpTip text={tips.demand}/></div></header>{value.dynamicPricingEnabled&&<><div className="demand-rule-callout"><strong>Demand rule</strong><span>Waiting bookings &gt; CLEAR vehicles</span></div><div className="settings-grid"><label><span className="field-label">Demand percentage added to Autocab fare</span><div className="input-with-unit"><Input type="number" min="0" max="100" step="0.1" value={value.demandPercent} onChange={e=>setValue({...value,demandPercent:Number(e.target.value)})}/><span>%</span></div></label><label><LabelText tip={tips.window}>Bookings counted within</LabelText><div className="input-with-unit"><span>±</span><Input type="number" min="1" max="120" step="1" value={value.demandWindowMinutes} onChange={e=>setValue({...value,demandWindowMinutes:Number(e.target.value)})}/><span>min</span></div></label></div><div className="dynamic-schedule"><div><strong>Limit automatic dynamic pricing to selected days and hours</strong><small>When off, the demand rule can operate at any time.</small></div><Switch checked={value.dynamicScheduleEnabled} onChange={dynamicScheduleEnabled=>setValue({...value,dynamicScheduleEnabled})} label="Enable the dynamic pricing schedule"/></div>{value.dynamicScheduleEnabled&&<div className="dynamic-schedule-editor"><div className="day-picker">{days.map((day,index)=><button type="button" key={day} className={value.dynamicDays.includes(index)?'active':''} onClick={()=>setValue({...value,dynamicDays:value.dynamicDays.includes(index)?value.dynamicDays.length===1?value.dynamicDays:value.dynamicDays.filter(item=>item!==index):[...value.dynamicDays,index].sort()})}>{day}</button>)}</div><div className="settings-grid"><label><span className="field-label">From time</span><Input type="time" value={value.dynamicStartTime} onChange={e=>setValue({...value,dynamicStartTime:e.target.value})}/></label><label><span className="field-label">To time</span><Input type="time" value={value.dynamicEndTime} onChange={e=>setValue({...value,dynamicEndTime:e.target.value})}/></label></div><small>Times use Europe/London. Overnight intervals such as 22:00–04:00 are supported.</small></div>}</>}<div className="demand-status"><Gauge/><span><strong>Current signal:</strong> {value.dynamicPricingEnabled?(snapshot || 'Loading live demand…'):'Dynamic pricing is off — base Priority percentage is used.'}</span></div></section>}
   <details className="pricing-advanced"><summary>Advanced Autocab response settings <HelpTip text={tips.response}/></summary><div className="settings-grid"><label><span className="field-label">Fare field in quote response</span><Input required value={value.pricePath} onChange={e=>setValue({...value,pricePath:e.target.value})}/><small>Expected value: outward.price</small></label><label><span className="field-label">Fare unit</span><select value={value.priceUnit} onChange={e=>setValue({...value,priceUnit:e.target.value as QuotePolicy['priceUnit']})}><option value="gbp">Pounds (£)</option><option value="pence">Pence</option></select></label></div></details>
   <div className="pricing-save-row"><Button disabled={busy} type="submit">{busy?'Saving…':'Save live fare settings'}</Button><span>Percentage and fixed amount are never combined for the same service.</span></div>
  </fieldset></form>
 </>;
 return embedded?<section className="pricing-workspace-section">{content}<CapabilityQuoteTest/></section>:<section className="operations-settings pricing-workspace-section">{content}<CapabilityQuoteTest/></section>;
}
