'use client';
import {useRef,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
export default function SmsTest(){
 const [expanded,setExpanded]=useState(false);
 const [phone,setPhone]=useState(''),[message,setMessage]=useState('Need A Cab Plus\nThis is a test SMS.'),[busy,setBusy]=useState(false),[result,setResult]=useState(''),[error,setError]=useState('');const sending=useRef(false);
 async function send(event:React.FormEvent){event.preventDefault();if(sending.current)return;sending.current=true;setBusy(true);setResult('');setError('');try{const response=await fetch('/api/admin/sms-test',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({phone,message})});const data=await response.json() as {error?:string;message?:string};if(!response.ok)throw new Error(data.error||'Unable to send test SMS.');setResult(data.message||'Gateway accepted the test SMS.')}catch(e){setError(e instanceof Error?e.message:'The request could not be confirmed. Check the phone before retrying.')}finally{sending.current=false;setBusy(false)}}
 return <section className="customer-settings-group sms-test-panel"><header className="sms-test-heading"><div><h4>Test SMS gateway</h4><p>Send a real test message using your saved gateway settings. Save configuration changes above before testing.</p></div><button className="customer-disclosure-button" type="button" aria-expanded={expanded} aria-controls="sms-test-content" onClick={()=>setExpanded(open=>!open)}>{expanded?'Hide test SMS ▴':'Show test SMS ▾'}</button></header><form id="sms-test-content" hidden={!expanded} onSubmit={send}><fieldset disabled={busy}><div className="sms-test-grid"><div className="sms-test-fields"><label className="customer-setting-field" htmlFor="sms-test-phone"><span>Recipient phone number</span><Input id="sms-test-phone" type="tel" autoComplete="tel" placeholder="+44 7…" required maxLength={40} value={phone} onChange={e=>setPhone(e.target.value)}/></label><label className="customer-setting-field" htmlFor="sms-test-message"><span>Test message</span><textarea id="sms-test-message" rows={6} required maxLength={1600} value={message} onChange={e=>setMessage(e.target.value)}/><small>Press Enter for a new line. {message.length} / 1600 characters.</small></label></div><div className="sms-test-preview"><span>Message preview</span><div>{message||'Your message will appear here.'}</div></div></div><footer className="customer-settings-actions"><Button type="submit" disabled={busy||!phone.trim()||!message.trim()}>{busy?'Sending…':'Send test SMS'}</Button><span>Sent to the number above. Provider SMS charges may apply.</span></footer></fieldset>{result&&<p role="status" className="customer-settings-success">{result}</p>}{error&&<p role="alert" className="error-message">{error}</p>}</form></section>
}
