'use client';
import {FormEvent,useCallback,useEffect,useMemo,useState} from 'react';
import {Check,Copy,Edit3,Plus,RefreshCw,Trash2,Webhook,X} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';

type Provider={id:string;name:string;description:string;base_url:string;api_key_header:string;enabled:boolean};
type Hook={id:string;provider_id:string;name:string;description:string;event_type:string;event_url_suffix:string;event_filter_recipe:string;enabled:boolean};
type ProviderForm={name:string;description:string;baseUrl:string;apiKeyHeader:string;apiKey:string;enabled:boolean};
type HookForm={name:string;description:string;eventUrlSuffix:string;eventType:string;eventFilterRecipe:string;enabled:boolean};

const eventTypes=['Booking Dispatch Accepted','Booking Arrived','Booking Cancelled','Booking Complete','Booking Created','Booking Dispatch Offered','Booking Modified','No Fare','Passenger On Board','Booking Recovered','Booking Rejected','Booking Running Late','Credit Note Issued','Customer Transaction Made','Docket Modified','Driver Paid In/Out','Driver Sheet Created','Driver Shift Started/Ended','Invoice Created','Vehicle Data Changed','Vehicle Tracks Changed'];
const emptyProvider:ProviderForm={name:'',description:'',baseUrl:'https://webhook.needacabplus.app',apiKeyHeader:'x-api-key',apiKey:'',enabled:true};
const emptyHook:HookForm={name:'',description:'',eventUrlSuffix:'/',eventType:'Booking Created',eventFilterRecipe:'',enabled:true};

export default function WebhookProviders(){
 const [providers,setProviders]=useState<Provider[]>([]),[hooks,setHooks]=useState<Hook[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const [selectedId,setSelectedId]=useState(''),[providerModal,setProviderModal]=useState(false),[editingProvider,setEditingProvider]=useState<Provider|null>(null),[hookModal,setHookModal]=useState(false),[editingHook,setEditingHook]=useState<Hook|null>(null),[copied,setCopied]=useState('');
 const [providerForm,setProviderForm]=useState<ProviderForm>(emptyProvider),[hookForm,setHookForm]=useState<HookForm>(emptyHook);
 const selected=providers.find(item=>item.id===selectedId);const providerHooks=useMemo(()=>hooks.filter(item=>item.provider_id===selectedId),[hooks,selectedId]);
 const refresh=useCallback(async()=>{setLoading(true);setError('');try{const response=await fetch('/api/admin/webhook-providers');const data=await response.json() as {providers:Provider[];webhooks:Hook[];error?:string};if(!response.ok)throw new Error(data.error);setProviders(data.providers);setHooks(data.webhooks);setSelectedId(current=>data.providers.some(item=>item.id===current)?current:data.providers[0]?.id||'')}catch(reason){setError(reason instanceof Error?reason.message:'Unable to load webhook providers.')}finally{setLoading(false)}},[]);
 useEffect(()=>{
  // Load the provider catalogue when the Webhook tab opens.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  void refresh();
 },[refresh]);
 function openCreateProvider(){setEditingProvider(null);setProviderForm(emptyProvider);setProviderModal(true)}
 function openEditProvider(provider:Provider){setEditingProvider(provider);setProviderForm({name:provider.name,description:provider.description,baseUrl:provider.base_url,apiKeyHeader:provider.api_key_header,apiKey:'',enabled:provider.enabled});setProviderModal(true)}
 function openCreateHook(){setEditingHook(null);setHookForm(emptyHook);setHookModal(true)}
 function openEditHook(hook:Hook){setEditingHook(hook);setHookForm({name:hook.name,description:hook.description,eventUrlSuffix:hook.event_url_suffix,eventType:hook.event_type,eventFilterRecipe:hook.event_filter_recipe,enabled:hook.enabled});setHookModal(true)}
 async function request(method:'POST'|'PUT'|'DELETE',payload:unknown){setBusy(true);setError('');setMessage('');try{const response=await fetch('/api/admin/webhook-providers',{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await response.json() as {id?:string;error?:string};if(!response.ok)throw new Error(data.error);await refresh();setMessage('Saved successfully.');return data}catch(reason){setError(reason instanceof Error?reason.message:'Unable to save webhook settings.');return null}finally{setBusy(false)}}
 async function saveProvider(event:FormEvent){event.preventDefault();const result=await request(editingProvider?'PUT':'POST',{type:'provider',...(editingProvider?{id:editingProvider.id}:{}),...providerForm});if(result){setProviderModal(false);setEditingProvider(null);if(result.id)setSelectedId(result.id)}}
 async function saveHook(event:FormEvent){event.preventDefault();if(!selected)return;const result=await request(editingHook?'PUT':'POST',{type:'webhook',...(editingHook?{id:editingHook.id}:{}),providerId:selected.id,...hookForm});if(result){setHookModal(false);setEditingHook(null)}}
 async function remove(type:'provider'|'webhook',id:string){if(!confirm(`Delete this ${type} and its saved configuration?`))return;await request('DELETE',{type,id})}
 async function copy(value:string){await navigator.clipboard.writeText(value);setCopied(value);setTimeout(()=>setCopied(''),1600)}
 return <div className="webhook-manager">
  <div className="config-section-title"><div className="config-icon"><Webhook/></div><div><h3>Webhook providers</h3><p>Create a provider, then add the event webhooks it should handle.</p></div><span className="config-status ready"><span/>{providers.length} provider{providers.length===1?'':'s'}</span></div>
  <div className="api-actions"><Button type="button" onClick={openCreateProvider}><Plus/>Add provider</Button><Button type="button" variant="outline" disabled={!selected} onClick={openCreateHook}><Webhook/>Add webhook</Button><Button type="button" variant="ghost" onClick={()=>void refresh()} disabled={loading}><RefreshCw/>Refresh</Button></div>
  {error&&<p className="error-message" role="alert">{error}</p>}{message&&<p className="saved-message" role="status">{message}</p>}
  {loading?<div className="api-empty">Loading webhook providers…</div>:providers.length===0?<div className="api-empty"><Webhook/><strong>No webhook provider yet</strong><p>Add the provider base URL and security key, then register each event webhook.</p><Button type="button" onClick={openCreateProvider}><Plus/>Add first provider</Button></div>:<div className="provider-workspace"><aside className="provider-picker">{providers.map(provider=><button type="button" className={provider.id===selectedId?'active':''} key={provider.id} onClick={()=>setSelectedId(provider.id)}><span className="connection-symbol"><Webhook/></span><span><strong>{provider.name}</strong><small>{provider.enabled?'Enabled':'Disabled'} · {hooks.filter(item=>item.provider_id===provider.id).length} webhook(s)</small></span></button>)}</aside>{selected&&<section className="provider-editor"><header><div><span className="eyebrow">PROVIDER SETTINGS</span><h3>{selected.name}</h3><p>{selected.description||'No provider description.'}</p></div><div><Button type="button" variant="outline" onClick={()=>openEditProvider(selected)}><Edit3/>Edit provider</Button><Button type="button" variant="ghost" className="danger-button" onClick={()=>void remove('provider',selected.id)} disabled={busy}><Trash2/>Delete</Button></div></header><div className="provider-facts"><div><span>STATUS</span><strong className={selected.enabled?'online':''}>{selected.enabled?'Enabled':'Disabled'}</strong></div><div><span>PROVIDER BASE URL</span><code>{selected.base_url}</code></div><div><span>API KEY HEADER</span><code>{selected.api_key_header||'Not configured'}</code></div></div><div className="webhook-list-heading"><div><span className="eyebrow">WEBHOOKS</span><h3>Event subscriptions</h3></div><Button type="button" onClick={openCreateHook}><Plus/>Add webhook</Button></div>{providerHooks.length===0?<div className="api-empty compact"><Webhook/><strong>No webhooks in this provider</strong><p>Add the first event and its URL suffix.</p></div>:<div className="webhook-table"><div className="webhook-table-head"><span>Enabled</span><span>Name</span><span>Event type</span><span>Destination URL</span><span/></div>{providerHooks.map(hook=>{const url=`${selected.base_url}${hook.event_url_suffix}`;return <div className="webhook-row" key={hook.id}><span className={`hook-state ${hook.enabled?'enabled':''}`}>{hook.enabled?<Check/>:<X/>}</span><span><strong>{hook.name}</strong><small>{hook.description}</small></span><span>{hook.event_type}</span><span className="url-cell"><code>{url}</code><button type="button" aria-label="Copy destination URL" onClick={()=>void copy(url)}>{copied===url?<Check/>:<Copy/>}</button></span><span className="row-actions"><button type="button" onClick={()=>openEditHook(hook)} aria-label={`Edit ${hook.name}`}><Edit3/></button><button type="button" onClick={()=>void remove('webhook',hook.id)} aria-label={`Delete ${hook.name}`}><Trash2/></button></span></div>})}</div>}</section>}</div>}
  {providerModal&&<Modal title={editingProvider?`Edit provider — ${editingProvider.name}`:'Add provider'} close={()=>setProviderModal(false)}><form onSubmit={saveProvider} className="webhook-form"><Toggle checked={providerForm.enabled} onChange={enabled=>setProviderForm({...providerForm,enabled})}/><label>Name *<Input required value={providerForm.name} onChange={event=>setProviderForm({...providerForm,name:event.target.value})}/></label><label className="full-field">Description<textarea value={providerForm.description} onChange={event=>setProviderForm({...providerForm,description:event.target.value})}/></label><label className="full-field">Provider Base URL *<Input type="url" required placeholder="https://webhook.needacabplus.app" value={providerForm.baseUrl} onChange={event=>setProviderForm({...providerForm,baseUrl:event.target.value})}/></label><label>API Key Header Name<Input placeholder="x-api-key" value={providerForm.apiKeyHeader} onChange={event=>setProviderForm({...providerForm,apiKeyHeader:event.target.value})}/></label><label>API Key<Input type="password" autoComplete="new-password" placeholder={editingProvider?'Leave empty to keep existing key':''} value={providerForm.apiKey} onChange={event=>setProviderForm({...providerForm,apiKey:event.target.value})}/></label><div className="modal-actions"><Button type="button" variant="outline" onClick={()=>setProviderModal(false)}>Cancel</Button><Button disabled={busy} type="submit">{busy?'Saving…':'Save provider'}</Button></div></form></Modal>}
  {hookModal&&<Modal title={editingHook?`Edit webhook — ${editingHook.name}`:'Add webhook'} close={()=>setHookModal(false)}><form onSubmit={saveHook} className="webhook-form"><Toggle checked={hookForm.enabled} onChange={enabled=>setHookForm({...hookForm,enabled})}/><label>Name *<Input required value={hookForm.name} onChange={event=>setHookForm({...hookForm,name:event.target.value})}/></label><label className="full-field">Description<textarea value={hookForm.description} onChange={event=>setHookForm({...hookForm,description:event.target.value})}/></label><label className="full-field">Event URL Suffix *<Input required placeholder="/driversInfo" value={hookForm.eventUrlSuffix} onChange={event=>setHookForm({...hookForm,eventUrlSuffix:event.target.value})}/><small>Full URL: {selected?.base_url}{hookForm.eventUrlSuffix}</small></label><label className="full-field">Event Type *<select required value={hookForm.eventType} onChange={event=>setHookForm({...hookForm,eventType:event.target.value})}>{eventTypes.map(type=><option key={type}>{type}</option>)}</select></label><label className="full-field">Event Filter Recipe<textarea placeholder="Optional JSON or filter expression" value={hookForm.eventFilterRecipe} onChange={event=>setHookForm({...hookForm,eventFilterRecipe:event.target.value})}/></label><div className="modal-actions"><Button type="button" variant="outline" onClick={()=>setHookModal(false)}>Cancel</Button><Button disabled={busy} type="submit"><Plus/>{busy?'Saving…':editingHook?'Save changes':'Create webhook'}</Button></div></form></Modal>}
 </div>;
}

function Modal({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){return <div className="webhook-modal-backdrop" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)close()}}><section className="webhook-modal" role="dialog" aria-modal="true" aria-label={title}><header><h2>{title}</h2><button type="button" onClick={close} aria-label="Close"><X/></button></header><div>{children}</div></section></div>}
function Toggle({checked,onChange}:{checked:boolean;onChange:(value:boolean)=>void}){return <label className="enabled-toggle"><span>Enabled</span><button type="button" role="switch" aria-checked={checked} className={checked?'on':''} onClick={()=>onChange(!checked)}><span/></button></label>}
